### ISSUE TITLE
Game stutters when placing or breaking blocks

### ISSUE THREAD

**Issue by DeleteMetaInf** [Krutoy242/Enigmatica2Expert-Extended#100]
### Description

The game stutters significantly when placing or breaking blocks, which is quite frustrating as the game freezes for a split second every time a block is placed or broken. This happens with _all_ blocks, including vanilla blocks and solid blocks. The world is quite new, and it’s been happening since I started it. It happens in all chunks, even ones where nothing has been built. `alwaysSetupTerrainOffThread` in forge.cfg is enabled as it is by default. OptiFine is not installed. I tried setting the mipmap level to 0, but that didn’t make a difference. 8.2 GB RAM is allocated, and memory usage isn’t going above 61%.

I used to have this issue back when playing Enigmatica 2 some years ago, but that time, it wasn’t a problem until I got a sizeable base with lots of tile entities ticking. This time, in E2E: Expert - Extended, it’s happening on a brand new world. Not sure what could be causing this, and I haven’t been able to find a fix.

**Modpack version:** 0.69.0 (latest)

### To reproduce

Place or break blocks. Press alt + F3 to see the frame time graph.

https://user-images.githubusercontent.com/59761487/188511859-d04053af-a515-4793-979e-db046ae618d8.mp4

**Comment by Krutoy242** [comment]
Try to remove  `Entity Culling` mod with it dependency.

**Comment by DeleteMetaInf** [comment]
Entity Culling isn’t installed (it’s not in E2E - Extended anymore, but its library mod [RenderLib](https://www.curseforge.com/minecraft/mc-mods/renderlib) is, so you may want to remove that in the next release), but I did some testing and after a couple hours, figured out it was caused by Better Foliage, which I added to the pack, so my bad on that one! Went ahead and submitted an issue on its issue tracker (#440), but it’s doubtful it’ll be fixed considering 1.12.2 is an old version, and it was also reported over three years ago but remains an issue.
