### ISSUE TITLE
Chisel blocks have no connected textures

### ISSUE THREAD

**Issue by DeleteMetaInf** [Krutoy242/Enigmatica2Expert-Extended#101]
### Description

Chisel blocks don’t have connected textures despite CTM being in the pack.

![2022-09-06_03 55 56](https://user-images.githubusercontent.com/59761487/188530946-abcd0743-95ab-48a4-97e1-14aecc4cd4a4.png)

**Modpack version:** 0.69.0 (latest)

### To reproduce

Place Chisel blocks that have connected textures.

**Comment by Krutoy242** [comment]
Im unable to reproduce the issue:
![image](https://user-images.githubusercontent.com/936618/188571115-7f37bf74-4b83-4485-9fc7-f071c3f857ba.png)

1. Did you have Optifine installed?
2. Did you changed any graphic settings?
3. Did you add any other mods?
4. Do you have other resource packs installed?
5. Does this issue persist after modpack reload?

**Comment by DeleteMetaInf** [comment]
Turns out I’m just an idiot. The blocks I was trying to use don’t _have_ connected textures. Tested with other blocks from Chisel, and they connect just fine.
