### ISSUE TITLE
Can’t create flux by throwing redstone dust into lava

### ISSUE THREAD

**Issue by DeleteMetaInf** [Krutoy242/Enigmatica2Expert-Extended#102]
### Description

Creating flux by throwing redstone dust into lava isn’t possible despite the recipe in HEI.

![Flux recipe](https://user-images.githubusercontent.com/59761487/188678240-d413320e-9afd-4b2f-99bf-fca1bd91b5f4.png)

![Flux](https://user-images.githubusercontent.com/59761487/188678129-80936dd7-2c0f-4ee2-9795-4eac77e62579.gif)

**Modpack version:** 0.69.0 (latest)

### To reproduce

Throw redstone dust into lava.

**Comment by Krutoy242** [comment]
Thank you for the report!
Yes, this interaction is not working and I don't know how to disable it.
I would try one more thing, but probably this issue would stay.
