### ISSUE TITLE
[Suggestion] Tooltip for Reinforced Coke Brick

### ISSUE THREAD

**Issue by Neffrex** [Krutoy242/Enigmatica2Expert-Extended#103]
I just tried to make the multiblock structure for the **_improved coke oven_** realizing afterwards that it's disabled. 

I noticed that there's no entry in the **_engineer's manual_** for it, but I still tried to make it.

A tooltip on the **_reinforced coke brick_** saying that the **_improved coke oven_** is disabled would've been very useful, so I'm just suggesting it as a possible improvement.

I attached an image of the multiblock structure in case I did it wrong and it's not disabled.
(3x2x3 reinforced coke brick, 3x1x3 steel sheetmetal, 1 hopper)

![2022-09-07_22 06 09](https://user-images.githubusercontent.com/52071446/188967281-bcd8643d-5f8a-4669-8fc3-3010bdd54eb2.png)

**Comment by DeleteMetaInf** [comment]
I believe you did it incorrectly, as the improved blast furnace is assembled using a 3×3 cube of reinforced coke brick, without any steel sheetmetal.

**Comment by DeleteMetaInf** [comment]
I believe you did it incorrectly, as the [improved blast furnace](https://ftb.fandom.com/wiki/Improved_Blast_Furnace) is assembled using a 3×3 cube of reinforced coke brick, without any steel sheetmetal.

![Improved blast furnace](https://user-images.githubusercontent.com/59761487/188984791-4db64000-b360-4568-a045-397c6f0c228c.png)

**Comment by Neffrex** [comment]
Yes, that's the way to make an improved blast furnace, but I was trying to make an improved **coke oven**, to create creosote oil and coal coke. 

This one right here:
![image](https://user-images.githubusercontent.com/52071446/188992768-8e8c37be-c961-4348-9004-efd2da747225.png)

**Comment by Krutoy242** [comment]
Thank you for report! 
Yes, I could add tooltip and probably note in quest book.
