### ISSUE TITLE
Compressed blocks in smeltery producing wrong amount of output

### ISSUE THREAD

**Issue by Neffrex** [Krutoy242/Enigmatica2Expert-Extended#105]
## Description
Compressed blocks don't smelt into the proper amount of liquid they should.
In example, a single compressed cobblestone block smelts into **1 block** (a.k.a **4 ingots** or **288mb**) of seared stone
instead of **2 blocks and 1 ingot** (a.k.a **9 ingots** or **648mb**)

I'm **not** in the last modpack version, but I'm pretty sure it's the same for the last version as I haven't seen any changelog statement related to this issue

(It seems that it's interpreting the compressed blocks as 2x2 instead of 3x3 compression)

**To Reproduce**
Smelt any (smeltable) compressed block in the smeltery

**Screenshots**
Some screenshots of the jei recipes showing the issue:
![1x Cobble](https://user-images.githubusercontent.com/52071446/189542744-1911f369-8190-4576-a2b4-6190dc04855a.png)
![1x Sand](https://user-images.githubusercontent.com/52071446/189542746-d5deb7d1-1e35-431d-830f-9e7b1046233f.png)
![2x Cobble](https://user-images.githubusercontent.com/52071446/189542736-01808192-0906-4f14-b45b-656c88d1be5f.png)
![2x Sand](https://user-images.githubusercontent.com/52071446/189542737-e109a5f7-e2d5-4beb-844a-e6178dbf3752.png)
![3x Cobble](https://user-images.githubusercontent.com/52071446/189542739-e20ad3a5-1628-47d4-ac48-78ccc4d80d3f.png)
![3x Sand](https://user-images.githubusercontent.com/52071446/189542740-f8f6e80b-7fc1-4748-905a-13147166f675.png)
![4x Cobble](https://user-images.githubusercontent.com/52071446/189542741-b23d33e2-cfc4-4e8b-b450-3fa384416304.png)
![4x Sand](https://user-images.githubusercontent.com/52071446/189542743-d744d1fe-ab1a-4cf2-b6ca-ab98d5d96157.png)

**Modpack version** `v0.67.0`

**Comment by Krutoy242** [comment]
This is **intended** behavior, added by me.

It would be too powerful to smelt so fast so big amounts of stone/sand in one run.

- If you have infinite amount of stones you can throw compressed without care
- If you want efficiency, you need to smelt blocks one by one

One trick: If you want x8 stone smelting you can make Large Stone Plates and smelt them.

**Comment by Neffrex** [comment]
I get your point, it would be too overpowered to do it that fast, but wouldn't it be fairer to make the smelting take far longer instead of reducing the amount of resulting material?

**Comment by Krutoy242** [comment]
I cant do this with provided API.
Smelting time calculated by `amount * melt_temperature`. I can't change `melt_temperature`, because it would make even 1 block smelt longer.

**Comment by Neffrex** [comment]
Ooh, okay, I didn't know it wasn't possible to do it. That concludes this issue then. Thanks for replying!
