### ISSUE TITLE
/defaultworldgenerator-port

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#108]
Choose A default world type:

1) Normal Overworld   [2940eb21-2775-11ec-bf95-c65cd4d55599]
2) Skyblock (Beta)   [8f2fe6d1-29ea-11ec-a2fa-c65cd4d55599]

Type "/defaultworldgenerator-port <the number for the server's worldtype>
Alternativly add the uuid as the value of "defaultworldgenerator-port" in server.properties

What it want from me???????????????? And why its not automate?????????????

**Comment by DarkStas** [comment]
Right answer:
/defaultworldgenerator-port 1
do no why it didn't work at start.

**Comment by Krutoy242** [comment]
Thank you for sharing your solution!
