### ISSUE TITLE
Please add to mining level number of that level, not only name, like "iron(4)", or "stone(2).

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#109]
Please add to mining level number of that level, not only name, like "iron(4)", or "stone(2). Most of all needed in Sharpening kit, because I (or any new users) dont know will I upgdate tool, or degrade.

**Comment by Krutoy242** [comment]
Yeah. nice idea, i could add that.

**Comment by Krutoy242** [comment]
Its actually looks weird now. Numbers repeated two times.

![image](https://user-images.githubusercontent.com/936618/192239781-a3023855-8dbe-4c31-a302-b4a6b6bdf080.png)

I think, i could leave this without changes. Players who want to know numbers, could see in quest book:
![image](https://user-images.githubusercontent.com/936618/192240116-b3066cc2-8518-4427-8ad0-9ccbe218a23a.png)
