### ISSUE TITLE
XP boost to tools based on Y (more when Y-0)

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#110]
Why not make XP boost gain to tools based on penalty of mining speed per Y. Make that player will gain same XP per min on Y-0 and Y-100 (so reduction of speed based on Y will not reduce XP gain, with no reason, like I think). 
Or even give some boost to tool XP gain the more near you to Y-0 (so it will be like 2x per min on Y-0).

**Comment by DarkStas** [comment]
This 2 min to harvest obsidian, it must give like 200x XP...

**Comment by Krutoy242** [comment]
Nice idea, but i dont know how to make this possible.
`Tool Progression` mod give no handles for changing xp gaining.

**Comment by Krutoy242** [comment]
I don't know how to change that.
If you know the way - feel free to comment and open this issue again.
