### ISSUE TITLE
betteranimalsplus or many mobs (as a whole) are causing lags

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#111]
betteranimalsplus, or mobs from it causing lags (3 fps game play). Thanks to LagGoggles I found what caused lags.
When I profiled lagged game (3 fps) there was like 20 mobs with us/t over 5000 (from betteranimalsplus), one us/t over 20 000 (from betteranimalsplus mob like whale) and skeleton and creeper with us/t over 4000, after delete there still left skeleton and creeper with us/t over 4000, and all another mobs take like 1-2 mobs - 2000 and other 1000 and less. 

Is it normal for mobs to take so much perf? (based on that vanila almost all another mobs take max 1000 us/t per mob or even less)

**Comment by DarkStas** [comment]
Ah and some more information, when I started game on dedicated server (with all mods, and it was too 3 fps), and logged to that server on start point there was like 200 mobs, most of it, like 120 was pixels (that green blot) and all other mobs, so may be its really bug with Mobs and their calculation...

**Comment by Krutoy242** [comment]
Seems like you have just bad video card.
I just made performance profile with lot of Whales on screen.

Yes, they show big numbers. But this actually **nano** seconds. So game would run 60 FPS if there is `16,000,000` nano-seconds consumed (16ms). And all Whales took only 2 ms.

![image](https://user-images.githubusercontent.com/936618/191903712-968eee27-fadb-45b2-ad8a-8fd6bc9ce7ec.png)
![image](https://user-images.githubusercontent.com/936618/191903740-6744ceae-39b9-4264-a44e-d18ef30cc209.png)

Anyway, try to remove `betteranimalsplus` and say if problem still exist.

**Comment by DarkStas** [comment]
Like I tried to write, when I started to try to play game (I tried to start it solo and with server on another comp) and all the time I got 3 fps that didn't unlag, even after 20 min (even when server on another comp, yes, server was not perf lagging, its was like 10-40% CPU, but when I spawn on starting point (on server) there was like 200 mobs, 120 pixels (that green blot) and etc., I didn't try to play with server without betteranimalsplus and tried then another time with solo game, and it was still 3 fps, than I found that there are LagGoggles and most of the lag for me was first meow.betteranimalsplus.whale and it was like 30% and another betteranimalsplus mobs, so it take like 50-90% of perf only to compute mobs from betteranimalsplus, I deleted this mods, and like I write, solo game started perfectly fine, 60fps in 30 sec and 100 fps in 5 min.

May be it was because of mods that reduce performance when minimizing game, for me it can have some performance reduction cases. I will try to figure out what mod reduce performance when minimizing and try without it but with betteranimalsplus mods.

**Comment by DarkStas** [comment]
Its better to ask it here, is FpsReducer is the only mod that help me reduce game performance?

**Comment by Krutoy242** [comment]
> FpsReducer is the only mod that help me reduce game performance?

Probably yes. Maybe there is other mods, but don't know others.

**Comment by Krutoy242** [comment]
So, is problem with "Pixels" still actual? I still don't get what mod you talking about.
