### ISSUE TITLE
ScalingGUIs and Waila(Hwyla) take performance like all another 300 mods together (FPS in LagGoggles)

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#112]
ScalingGUIs and Waila(hwyla) take performance like all another 300 mods together.

![image](https://user-images.githubusercontent.com/41925337/191872958-6eca19c0-893b-4092-ab1a-c62dd7139b36.png)

Will delete ScalingGUIs and Hwyla (Waila) + WailaHarvestability + Wawla. 
Will change Hwyla (Waila) (like we could see Hwyla (Waila) take 2.200.000 ns/F (2nd place) and Wawla 330.000 ns/F) (7nth place) with The one probe + 3 addons, and will write perf of it here.

**Comment by DarkStas** [comment]
The one probe +thaumic-one-probe (I still didnt open thaum and as of now it did not show me aspects, so how I think its based on my level in thaum) + topaddons + topextras and take like 500.000 ns/F (in top 20 in FPS of LagGoggles showed only the one probe). 

It shows info no worse than Waila (but still there no number near harvest level).

**Comment by DarkStas** [comment]
It feels like without ScalingGUIs and Hwyla (Waila) + WailaHarvestability + Wawla its load much faster...

**Comment by Krutoy242** [comment]
This 13% tick time most likely caused not by `ScalingGUI`. Seems like `ScalingGui` only calls its method to draw whole GUI, and LagGoggles show it as reason.
Most likely, removing `ScalingGUI` will not have any effect, only GUI rendering function would be redirected to another name.

There is my profiler. As you can see, only 3% when many objects on screen

![image](https://user-images.githubusercontent.com/936618/191902171-0fbc131e-ff27-4479-8779-9e474d0661f2.png)

![image](https://user-images.githubusercontent.com/936618/191902595-cd83ac20-975a-439b-933a-4c6316884075.png)

Use `/sparkc profiler` command to see what **actually** causing FPS lag.

**Comment by DarkStas** [comment]
Maybe yes, because after I deleted them there no perf difference.
I will close this theme.
