### ISSUE TITLE
Is it intended to get Liquifacted Coal so hard?

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#114]
Is it intended to get Liquifacted Coal so hard? And because of it Steel and Dark Steel. 

or even not 'hard', you can't make it at all, cos there loop, if you need to craft Liquifacted Coal you need Void Crystal, but to get Void crystal you need Steel, but to get steel you need Liquifacted Coal.... There only 2 ways to get Liquifacted Coal and both of them can't be crafted...

Yes there ways to get alloys without Liquifacted Coal, but all of them need Steel..................................... Like for Steel Casing (need Steel) or Machine Frame (need Void Crystal, and to craft machine that craft Void Crystal you need Steel)

**Comment by Krutoy242** [comment]
> Liquifacted Coal so hard? 
Yes, this change derived from original E2E modpack

Simpliest way to obtain Steel - throw Iron in Blast Furnace
![image](https://user-images.githubusercontent.com/936618/192135720-8603d612-6809-4663-a61e-ff6ea5b94845.png)

For questions about crafting items, please consider to join `E2E-E` Discord server: https://discord.gg/P2MTyxHZtw

**Comment by DarkStas** [comment]
Thanks, but this theme is more to change recipe to get more easy Liquifacted Coal, like why not change recipe for machine that give Liquifacted Coal to more common. And question about "is it intended" was to know, how author of this modpack thinks. 

Like for me we need to understand what Tier is Steel (osmium(5) based on jei items for harvest), and based on it we could change craft of machines that do Liquifacted Coal to be like with Iron or Lead (3-4lvl), because I already on 8 lvl and can't get resources of 5 lvl...

Or is it intended?

**Comment by Krutoy242** [comment]
> is it intended

Yes. 

> I already on 8 lvl and can't get resources of 5 lvl...

Steel can be obtained on Level 3

**Comment by DarkStas** [comment]
> Steel can be obtained on Level 3

Don't know how, Like I say, on 8 lvl I could not get it. Even with your help with Blast Furnace I could not make it, because there is block based on health and I was at 14 (of 15 needed), so I played 3 more hours to unlock Blast Furnace and get to Nether and there farm nether bricks.

**Comment by Krutoy242** [comment]
> Blast Furnace and get to Nether

You dont need Nether to build Blast Furnace.
You can get blaze powder:

1. From Empty Rod
2. From Cinderpearls
3. From Dead Ferrous-Juniper leaves

> Machine Frame absurdly and improperly hard to craft

Its not my idea. Since `Enigmatica 2: Expert - Extended` is addon for `Enigmatica 2: Expert`, most recipes derived from there.

**Comment by DarkStas** [comment]
Awesome modpack (pick and synergy of mods), awesome your work to optimize work of mods and playability, but recipes is a ****. No logic in creating of hardness, no Tiering, no QoL, the only task is to randomly make game hardly. Why ME is like T12 tier, OK with machines that give ton of recourses or ton on dmg/def/life, but ME, its only task is QoL...

Could you please say where are recipes saved to delete them.

**Comment by DarkStas** [comment]
Its folder scripts/craft, but after I deleted it there are some craft that didn't work.

**Comment by Krutoy242** [comment]
> Why ME is like T12 tier,

To encourage players use other mechanics, like Thermal Logistics. Did you try this mod already?

**Comment by Krutoy242** [comment]
I feel like i answered all your questions.
If there is more - feel free to write again.
