### ISSUE TITLE
Cyclic Magma/Powered Diamond Anvils don't repair Thaumic Wonders stones

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#115]
The Magma Anvil and Powered Diamond Anvil from Cyclic do not repair the Alchemist's, Transmuter's, and Alienist's Stones from Thaumic Wonders.
These items are crafted with 0 durability, making them cumbersome to use.

**Comment by Krutoy242** [comment]
Thanks for the report.

Is Stones from Wonders have actually 0 durability? They should have at least 64 or 128 at start, and then easily combined with each other.
Maybe durability bar so tiny it's like like zero?

They are not intended to be repaired since they are not tools.

Also, did you tried arcane repairer? (or how it called, I forgot)

**Comment by stiffchub** [comment]
You're right, they do start out with 128 durability. They have a max durability of 65534, which makes it look like they have none to start with. My mistake.

From my testing, I could only find that the Energetic Infuser from Thermal Expansion upgraded with the Flux Reconstruction augment can repair them, aside from simply combining them.

It would make sense for the Thaumic Restorer to work with it, but it doesn't allow for them to be inserted into it at all. The restorer is also from Thaumic Tinkerer, whereas the stones are from Thaumic Wonders. In the [source code for the restorer](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/dev/src/main/java/com/nekokittygames/thaumictinkerer/common/blocks/BlockRepairer.java), it uses the isItemValidForSlot function for determining whether or not it can be repaired, which I'm not sure if crafttweaker supports it in 1.12.2.

**Comment by Krutoy242** [comment]
No, CT can't fix that class things. So probably combining is only the way.

Also, do you know how to insert stone with automation? I actually don't know.

**Comment by stiffchub** [comment]
If you mean into the chamber itself, then I don't think you can. I think it functions almost identically to the infernal furnace, which will only accept items from the top hole, and the result gets spit out the front. The block where the liquid was placed in the multiblock is the only portion that allows pipes to connect to it, even then, it will still only accept items from the top and outputs from the front. It'll output directly into pipes connected to the front.

I wasn't able to push or pull the stones into the chamber at all. Piping them directly into the input simply caused it to spit the stones out the front.

**Comment by Krutoy242** [comment]
Ok, thank you for info.

**Comment by Krutoy242** [comment]
So, since i cant change behavior of Anvils, i would close this issue.
Feel free to comment if i missed some kind of solution.
