### ISSUE TITLE
Immersive Engineering External Heater doesn't affect Thaumic additions Mithrillium Smeltery

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#116]
The External Heater from Immersive Engineering doesn't provide heat to the Mithrillium Smeltery from Thaumic additions: Reconstructed. The same setup works for the normal/thaumium/void smelteries from base Thaumcraft.
I assume this issue extends to the Adamanite and Mithminite smelteries as well, but I haven't tested it.

**Comment by Krutoy242** [comment]
# 😲

Actually, I never knew this compatibility even exist!

Seems like this is Thaumic Additions problem, and I can't do much with that.

Isn't arcane bellows should do the work same good?

**Comment by stiffchub** [comment]
Arcane bellows do not work on smelteries.

I did some testing and found that the Resistive Heater from Mekanism is also compatible with base Thaumcraft smelteries, but still isn't compatible with Thaumic additions smelteries.
It does seem like the issue is with Thaumic additions itself.

**Comment by Krutoy242** [comment]
Ok, thank you for tests. I don't know what I could do there. You could try to make issue report to TA issue tracker.

**Comment by stiffchub** [comment]
Done. Don't know when there will be a fix for it though, seeing how old many of the issues on their tracker are.
[Here's the link for it.](https://gitlab.com/DragonForge/ThaumicAdditions/-/issues/133)

**Comment by Krutoy242** [comment]
Since i cant fix this issue from my side, i would close issue.
