### ISSUE TITLE
Mod Director for mods not hosted on CurseForge?

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#12]
Not really an issue, but just wanted to let you know about Mod Director if you didn't know it already: https://www.curseforge.com/minecraft/mc-mods/moddirector

It can download mods like SoundPhysics and OptiFine which aren't hosted on CurseForge, so your modpack can be approved whenever you decide to publish it.

**Comment by Krutoy242** [comment]
I added this mod on [latest release](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v0.38).

What non-CF mods you could suggest for this pack, other then Sound Physics?

**Comment by evanbones** [comment]
Nice! Looks like a cool update!

Is Nutrition included in the pack? I can't remember. And IIRC there's an OpenComputers addon that isn't hosted on CurseForge.

**Comment by Krutoy242** [comment]
> Nutrition

The SolCarrot uses nutritions yes, but its another mod i guess, that hosted on curseforge.

> IIRC there's an OpenComputers addon

It was `Computronix`, but i removed it from pack already.
