### ISSUE TITLE
Rattus and Mythus Vis Seed not plantable

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#120]
The Rattus and Mythus Vis seeds can't be planted in any kind of soil.
You still get the error message when trying to plant them outside of the emptiness and planets.
They also don't appear in JEI, even though the pods they produce do.

I think this might be due to Rattus and Mythus being from Rats and Ice and Fire.
Adding the seeds directly into the script may fix the issue.

**Comment by Krutoy242** [comment]
Adding seeds directly in what script? I don't get it.

**Comment by stiffchub** [comment]
The thaumicadditions_seeds.zs file.

**Comment by Krutoy242** [comment]
> The thaumicadditions_seeds.zs file.

Changing this file wont have effects, because events not even fired.

Seems like this is Thaumic Additions bug - added seeds registered wrongly. If i would be unable to fix that, i would probably just remove their recipes.
