### ISSUE TITLE
Conflux Ranks Bug

### ISSUE THREAD

**Issue by lockian** [Krutoy242/Enigmatica2Expert-Extended#124]
## Description

The conflux ranks do not apply when a quest chain is completed. The reason for this is the commands such as

/rank add @p conflux_i

should be

/ranks add @p conflux_i

**To Reproduce**

1. Complete all quests for conflux rank 1
2. Click the tick to accept the conflux reward
3. Rank does not apply

**Modpack version** `v0.71.0`

**Comment by Krutoy242** [comment]
Thank you for report and solution! Would be done.
