### ISSUE TITLE
About the products of magic beans

### ISSUE THREAD

**Issue by chicknice** [Krutoy242/Enigmatica2Expert-Extended#127]
The magic bean product is too BUG. I can use cardboard boxes to pack many "Timewood Clocks" at the beginning, and then use Cyclic's "Harvester" to obtain a lot of very expensive things at the beginning. For example, EIO's Grinding Ball and Deep Mob Learning's Model. Various expensive gemstones of Biomes O 'Plenty and Territorial Artifact. It's too much too much too much too easy to get these precise things in the early days. For some reasons, our conversation is not very convenient. Contact me and send an email to woqinqi@outlook.com @Krutoy242

**Comment by Krutoy242** [comment]
Github Issues is good place for discuss.

Can you show me your setup?
Thats because even 20 "Timewood Clocks" make Beans grows only 1 per 2-3 minutes.
That mean that you need about several real hours to get something really relevant.

But yeah, probably i could cut list of items and remove most valuable of them.

**Comment by chicknice** [comment]
I'm sorry, my English is not very good, I try my best to express my meaning

I use v0.70.0. Here is a 10 minute test
Accelerate the growth of magic beans through "Rich Soil Farmland" and "Timewood Clock", and stack enough "Timewood Clock" to make magic beans mature immediately
[cid:6af8d55f-2e33-4f93-b076-34de360b94ed]

Test process: Although magic beans cannot be planted on the "Fermented Dirt" manually.But the "Farmer" of Actual Additions,It can be planted
37 Timewood Clocks are used for stack acceleration
Cyclic's Harvester uses range harvesting mode
This can operate at almost full efficiency
[cid:2a1d17e6-4d9c-40d7-9c3e-276c05f7def1][cid:a7073a55-016a-463c-bff7-2c61c2814c9b][cid:135e158e-9c03-43ea-89ea-f57d3596fd7b]

The materials needed for construction are very cheap
[cid:8471e76a-1463-46d1-86b1-60451f6953f5]

But can get very expensive things
[cid:c847a047-1877-4468-b77e-8be67867087e][cid:b9517eef-273a-4f3f-82f3-0f480ca77b0c][cid:37472e89-f06e-4c71-9ba3-f242865ad04d][cid:65b7a1f2-60c4-4c45-be50-5824bab2de1f][cid:7cd7888b-3f08-434d-ae99-ae4ac50ef7b7]

This can be done at a very early stage,There is no need to look at it or even expensive pipes. It is simply Freedom Zero purchase

Please delete the special product of magic bean directly

thank you
E2e-e It's great, I love it
My name is Qinn
________________________________
发件人: Krutoy242 ***@***.***>
发送时间: 2022年10月11日 3:10
收件人: Krutoy242/Enigmatica2Expert-Extended ***@***.***>
抄送: chicknice ***@***.***>; Author ***@***.***>
主题: Re: [Krutoy242/Enigmatica2Expert-Extended] About the products of magic beans (Issue #127)


Github Issues is good place for discuss.

Can you show me your setup?
Thats because even 20 "Timewood Clocks" make Beans grows only 1 per 2-3 minutes.
That mean that you need about several real hours to get something really relevant.

But yeah, probably i could cut list of items and remove most valuable of them.

―

**Comment by Krutoy242** [comment]
It feels like your message should contain pictures. But there is no pictures 😟

Anyway, yeah, i could remove too-valuable items from drop list.

**Comment by chicknice** [comment]
I sent it by email, I didn't use GitHub, and after a few hours I tried to figure out how to send pictures on it. In my case, Twitter has a firewall. My vpn is down.
 Maybe you could give me an email address. It would be easier

发自我的iPhone

在 2022年10月12日，16:11，Krutoy242 ***@***.***> 写道：

﻿

I don't know what appendix you talking about, but there is how this post looks for me:
[image]<https://user-images.githubusercontent.com/936618/195287553-7b881c1b-41b2-4822-9e4e-3f075c9313ec.png>

**Comment by chicknice** [comment]
1. ok，first test ten minute collection

![1](https://user-images.githubusercontent.com/115498320/195389363-874be854-46be-479b-bdca-83274e539d9c.png)

2.building structure
![2](https://user-images.githubusercontent.com/115498320/195389736-0ad833b4-2600-4949-a983-28aea796e0ce.png)

3.Conduct a collection
![3](https://user-images.githubusercontent.com/115498320/195389891-8c802b7f-525b-40c5-9d0c-a4f025447993.png)
![4](https://user-images.githubusercontent.com/115498320/195393741-be3d7901-4350-4a41-b8eb-af37e99f4c16.png)

![5](https://user-images.githubusercontent.com/115498320/195389919-99a26f36-8389-4907-812c-431dedce1e3c.png)
g)

4.Some products collected in ten minutes

![7](https://user-images.githubusercontent.com/115498320/195394215-26ecb695-8403-4d2f-9fef-f2a6a0213b3f.png)
![8](https://user-images.githubusercontent.com/115498320/195394265-88ca64a7-3631-4743-a319-6dc767aadcbc.png)
5.Simple processing
![9](https://user-images.githubusercontent.com/115498320/195394500-d4f53a6b-06f4-4534-a7c7-5cce04f4facd.png)
![10](https://user-images.githubusercontent.com/115498320/195394509-b0890a43-a485-42f9-8fa1-f1b1677f6a24.png)
![11](https://user-images.githubusercontent.com/115498320/195394523-f53ffe47-393e-4884-9669-6102e169d930.png)

Note that this is just the harvest of ten minutes of testing, which is too abnormal. It not only shortens many setting steps. Many technologies can be skipped at the beginning
So I think this is very unreasonable

Finally, I'm sorry because I can't（Maybe it should be incomprehension？forgive me for my poor English.........） use github to make communication difficult @Krutoy242 😊

**Comment by Krutoy242** [comment]
Oh my. Thank you for screenshots and information!

Yes, this is unreasonable much of resources. I will cut them down. Thank you for help!
