### ISSUE TITLE
AE why is this

### ISSUE THREAD

**Issue by chicknice** [Krutoy242/Enigmatica2Expert-Extended#133]
Why can't my P2P channel expand?
![2022-10-25_02 46 35](https://user-images.githubusercontent.com/115498320/197604205-8617383d-2c65-4b57-b9de-c81b2db3e7d3.png)
![2022-10-25_02 46 47](https://user-images.githubusercontent.com/115498320/197604212-f02caae1-6a82-43c6-ba30-24ee51f2000e.png)
![2022-10-25_02 47 02](https://user-images.githubusercontent.com/115498320/197604216-4820a191-0f66-44f0-8039-b86a8a045a1c.png)

Pic 1, 2 P2P channels at the same frequency, also have energy
Figure 3, using the other way does not work

![2022-10-25_02 47 23](https://user-images.githubusercontent.com/115498320/197604835-6255bdf7-95d8-428f-b2dc-de995cc86534.png)

Look at this picture, 0/32, the AE controller does not give the cable channel

Am I using it in the wrong way?   I've always used it this way without a problem!   V0.74 is used

![Inked2022-10-25_02 47 23](https://user-images.githubusercontent.com/115498320/197605920-8d849e00-8833-4e7c-9859-5f679d9c8e92.jpg)
How to hide the content of the red area, I don't know how to set it, I haven't found it for a long time

**Comment by Krutoy242** [comment]
Thank you for the report!
I never encountered this issue myself, but could try to reproduce it soon.

Note that AE2 is actively developed right now, and i usually keep latest version. Try to check their github issues - maybe someone already reported same thing: https://github.com/PrototypeTrousers/Applied-Energistics-2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by Krutoy242** [comment]
I cant reproduce the issue. Maybe you connecting its wrong?

There is my setup - working fine:

![image](https://user-images.githubusercontent.com/936618/197756951-2ef41d15-c347-4885-97a4-147f807ac207.png)
![image](https://user-images.githubusercontent.com/936618/197757332-cd84e613-accb-4039-8996-0dd18e7f1894.png)
