### ISSUE TITLE
Forge hammer creates invalid items with multiple broken spawner types

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#137]
The forge hammer creates invalid items when crafted with broken spawners for wither skeletons, blizz, blitz, and basalz. Similar recipes create chunks that are used to craft seeds of the respective mob. These mobs don't have chunks, seeds, or essence items related to them.

**Comment by Krutoy242** [comment]
Thank you for the report!
Seems like I will need to add this recipes to blacklist.

**Comment by Krutoy242** [comment]
Fixed in next release.
