### ISSUE TITLE
Osgloglas unobtainable?

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#14]
![image](https://user-images.githubusercontent.com/74276616/139964273-6e338e84-2aba-4046-9dcf-7a04f5e6d182.png)

Glowstone Ingot and Refined Obsidian Ingots are both unsmeltable in the Tinkers' Smeltery. According to the quests, they should be smeltable. 

![image](https://user-images.githubusercontent.com/74276616/139964380-0a650dbc-a77b-4f8b-b786-3b3c25ef96cd.png)

Am I missing something or is this a bug?

**Comment by 2001zhaozhao** [comment]
There are special recipes for molten refined glowstone and obsidian, you can't melt the ingots directly unless using Thermal Expansion machines. You need to make them in certain machines and pipe it into a smeltery or transport manually with something like advanced ender bucket to make Osgloglas.

**Comment by 2001zhaozhao** [comment]
The quest book is wrong and could certainly use some editing though.

**Comment by evanbones** [comment]
I see, thanks!

**Comment by Krutoy242** [comment]
> The quest book is wrong and could certainly use some editing though.

True! Would fix next release.
