### ISSUE TITLE
Recommended to add Findme in whitelist of Particle Culling 

### ISSUE THREAD

**Issue by xy-233** [Krutoy242/Enigmatica2Expert-Extended#142]
config/particleculling.cfg
![image](https://user-images.githubusercontent.com/42868492/205599046-79f194d5-a283-4b51-8a7a-8ba3bc9e906f.png)
`com.buuz135.findme.proxy.client.ParticlePosition`
So I can find my items behind the wall

**Comment by Krutoy242** [comment]
Sounds good! Thank you for suggestion
