### ISSUE TITLE
Dupe bug about Tinkers' Complement and Chisel

### ISSUE THREAD

**Issue by mczph** [Krutoy242/Enigmatica2Expert-Extended#147]
## Description

If you use the Tinkers' Complement chisel to chisel an item that exceeds its durability, the chisel will be damaged immediately and the material will be thrown out. When you open the chisel UI screen again after repairing the chisel at the toolforge, the item will remain in the UI screen with the same amount of material left over from the damage.And you will get double amount of the items

**Modpack version** `0.84.0`

This bug is in all modpacks containing Tinkers' Complement and Chisel.It's necessary to fix and fok the mod to deal with problem since so many people are using these mods.If you really can't fix, just disabled it.

**Comment by Krutoy242** [comment]
I believe i could fix that, but not soon i guess.
I will need to fix Java code with Bansoukou i believe.

**Comment by mczph** [comment]
@Krutoy242 
https://github.com/Focamacho/DupeFix-Project/issues/63
try to use this mod

**Comment by Krutoy242** [comment]
> [focamacho/DupeFix-Project#63](https://github.com/focamacho/DupeFix-Project/issues/63) try to use this mod

Thanks, i would take a look.

**Comment by Krutoy242** [comment]
Since DupeFix can be installed on the server side only, each server maintainer can install it themself, and there is no need to provide it with the client.

In single-player games, there is no point in fighting against dupes, because anyone who wants to cheat can just go into creative mode.
