### ISSUE TITLE
Rats AI does partially work

### ISSUE THREAD

**Issue by JustaRandom** [Krutoy242/Enigmatica2Expert-Extended#155]
Hi,
Trying to work with the mod and seems that the rats are not doing anything:
     - Gathering items from the ground (nothing happens).
     - Doing actions with the upgrades (Works on a whim).
                  - Example: Put an harvester upgrade on a rat and it will work, quit and re-log and it will stop working.
                  - And sometimes it just doesn't do anything. (tried with fresh rat and already spawned)
 
I tried:
     - to do everything with the rats on a creative world and it is broken.
     - to replace the mod with the version from:
                  - Rats: Rebirth of the Plague --version 3.2.21 / (still the same problems).

Because there is nothing on the log, I do not know why.

Solutions?
     - Remove the mod. It just take space at this point for nothing, will mess the questbook but useless.
     - No idea, I am just throwing ideas at this point.

Thanks

**Comment by Krutoy242** [comment]
I removed mod `AI Reducer` and seems like it fixed it. Probably `AI Reducer` is the reason of issue.


https://user-images.githubusercontent.com/936618/214606625-ae81d051-5f45-4665-9ab4-600b1383b2a8.mp4

**Comment by JustaRandom** [comment]
Removing the mod `AI reducer` fix the default behaviour from the rat.
Still seems to be a bit weird when given an upgrade sometimes do something or not:
      - to "activate" the rat with the upgrade: a save and quit seems to fix it but i do not know for how long.

Thanks

**Comment by Krutoy242** [comment]
I used Fan to make rat move 😄
