### ISSUE TITLE
Quark roots generating in mid air

### ISSUE THREAD

**Issue by SteaSteaStea** [Krutoy242/Enigmatica2Expert-Extended#158]
[E2E-Extended-v0.89.0]

Hello,
I've noticed a small bug with the quark cave roots. Most of them seem to generate mirrored to their expected position.
![image](https://user-images.githubusercontent.com/76264934/217629934-c6e04ce2-7ad4-47a0-8f32-6698ea36cd06.png)

I don't remember seeing this bug on regular E2E (which didn't have the quark fork).

If someone can confirm this maybe you could consider disabling them. There's already so much extra clutter in caves - thaumcraft crystals, wines from mineshafts, the quark cave biomes, botania mushrooms, BoP mushrooms, etc.

**Comment by Krutoy242** [comment]
I see same problem.

I investigated and found, that they not spawned with wrong rotation. Instead, they spawned at wrong block position, because actually, they rotated accurate, just on one block shifted.

I will consider to disable them or tweak if can.

**Comment by Krutoy242** [comment]
Created issue on Quark:Rotn github https://github.com/Rebirth-of-the-Night/Quark/issues/16

**Comment by Krutoy242** [comment]
Fixed in next modpack version.
Thanks @ACGaming for help!
