### ISSUE TITLE
Mods suggestion

### ISSUE THREAD

**Issue by DarkStas** [Krutoy242/Enigmatica2Expert-Extended#160]
WTS (This mod is a simple utility that allows you to query which items can be placed in a specific slot by holding down Left-Alt.) - https://beta.curseforge.com/minecraft/mc-mods/whats-that-slotx  

bonsaitrees (A Minecraft mod adding a block that grows small trees in a single block space.) - https://beta.curseforge.com/minecraft/mc-mods/bonsai-trees

For Bonsai Trees there are many compatibility mods with other mods.

**Comment by DarkStas** [comment]
AgriCraft (AgriCraft is a mod which aims to bring crop breeding to Minecraft, this includes both improving your existing crops, or cross-breeding to mutate into new species of crops.) - https://www.curseforge.com/minecraft/mc-mods/agricraft

ThaumicAdditionsAgriCraftCompat  (Thaumic Additions: Reconstructed adds support for vis plants, which grow vis pods to provide pure Thaumcraft aspects for essentia. ) - https://beta.curseforge.com/minecraft/mc-mods/thaumicadditionsagricraftcompat

**Comment by Krutoy242** [comment]
Bonsai trees - one of the most suggested mod for E2E, and it's always declined. Bonsai trees anti-automation mod and spoiling main idea of modpack.

I will check WTS later. Did you try to install and run it on your own E2EE insurance?

**Comment by DarkStas** [comment]
WTS working fine. 

I suggest Bonsai trees for same purpose as compact machines, do not building plantation of 20 chunks of  trees and machines to auto cut them, but use little one block. Of course price something like Tier 3.

Didn't know that bees have this feature , will test it.

Can't see any way to increase capacity of Electric jetpack (and other armors with this jetpack), is there any?

Thanks for answers.

**Comment by mczph** [comment]
WTS is not so useful since you already hava HEI that can view recipes.And it cost a lot of time if the items amount is big.

**Comment by Krutoy242** [comment]
> Of course price something like Tier 3.

Since wood is Tier0 resource, when player reaches T3 tech, he would already have other types of wood farms already. So players should just skip bonsai and it would be dead mod.
Also, of you want "lot of wood from one block" feature, you can use Tree seeds from Musical Agriculture.

> Can't see any way to increase capacity of Electric jetpack (and other armors with this jetpack), is there any?

Discord is better place for questions like this. In short - you may use Lapotron Charger.

**Comment by Krutoy242** [comment]
> WTS is not so useful since you already hava HEI that can view recipes.And it cost a lot of time if the items amount is big.

Yeah, good point.
I was thinking what machine can be actually useful with this feature and can't find any.
Like, nobody use Portion Brewing Stand without JEI, for example.

**Comment by DarkStas** [comment]
How about Combo Armors to update capacity of jetpack and make some combination of armors.

**Comment by Krutoy242** [comment]
> How about Combo Armors to update capacity of jetpack and make some combination of armors.

I will check out this mod later.

**Comment by DarkStas** [comment]
And for me there some problems with mouse, when game load some staff there are mouse accelerate events... 
Tried "Raw Mouse Input" mod and mouse accelerate change to mouse lags.

**Comment by DarkStas** [comment]
Some problems with ME terminals (AE2) or whole net. It only update list of items when I go away for farm and then come back,

**Comment by Krutoy242** [comment]
> How about Combo Armors

The Combo Armors mod is too big. It adds so many types of armor, which will increase the load time of the game.

If `E2E-E` had little armor, I would add it. But the modpack already has a lot of variety of armor.

> when game load some staff there are mouse accelerate events

I dont understand what you talking about? I cant find problems with mouse.

> Some problems with ME terminals (AE2) or whole net. 

This issue called "Mods Suggestion". For problems and Crashes please write in Discord or create another issue.
Related to AE2 terminal - AE2 is in active development now, try to check out their GitHub - maybe problem already reported: https://github.com/PrototypeTrousers/Applied-Energistics-2

**Comment by Krutoy242** [comment]
> I dont understand what you talking about? 

Since no responce 2 weeks, im closing this issue.

Cant understand what mouse issues you talking about.

**Comment by Krutoy242** [comment]
Ok, thanks, i will try it.

**Comment by Krutoy242** [comment]
> I'd recommend giving it a try (even if you don't plan on adding it to the pack). You turn it OFF/ON with "/rawinput" (its ON by default after installing).

I just checked and it adds "jittering" to my mouse movement, like there is 3 normal frames and then 1 little bit frozen. This wont happen of `rawinput` is OFF.

So i guess, this depends on computer and would not work fine for everyone.
