### ISSUE TITLE
Multiple recipes still require Rattus for crucible/infusion.

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#166]
There are 5 crucible recipes and 2 infusion recipes that require Rattus, because most sources of Rattus are disabled, there is no way to do these recipes.

The 5 crucible recipes are for soul vials, one for the villager, iron golem, evoker, vindicator, and illusioner.

The 2 infusion recipes are for the gaia spirit and psionic rat brain. 

The iron golem, evoker, and illusioner soul vials aren't very useful in my opinion and can be removed entirely with no issue. The evoker is a source of totem of undying.

**Comment by Krutoy242** [comment]
Thank you for report!

This issue probably happen because i didn't updated cache file for aspects.
What version you play on?

**Comment by stiffchub** [comment]
I'm running the current version with a new instance so nothing should be cached.

**Comment by Krutoy242** [comment]
> I'm running the current version with a new instance so nothing should be cached.

There is two "current" versions right now: `v0.89.0` and `v0.91.0`. Which one of them you play?

Also, cache for aspects distributed with the modpack, they created on my machine.

**Comment by stiffchub** [comment]
0.89.0

**Comment by Krutoy242** [comment]
> 0.89.0

1. Remove `config\thaumicjei_itemstack_aspects.json`
2. Reload game and play until this file regererated
3. Reload game again. Rattus items should appear there

**Comment by Krutoy242** [comment]
So, did you tried this solution?

**Comment by stiffchub** [comment]
Yes, items now have Rattus.
