### ISSUE TITLE
Schematica: Missing/outdated Immersive Technology schematics

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#17]
Not a massive issue, but some of the immersive technology schematics are out of date.
For example:
- The mod is called Immersive Tech in the folder, but has been renamed to Immersive Technology
- The advanced coke oven is no longer craftable
- The melting crucible doesn't have a schematic
There's a couple of other multiblocks that can be found in the Engineer's Handbook that are missing schematics

**Comment by Krutoy242** [comment]
> The mod is called Immersive Tech in the folder, but has been renamed to Immersive Technology

Thanks, would rename it.

> The advanced coke oven is no longer craftable

Honestly i don't know why. Seems like one of IE addon developer removed it o_O.
This wont matter much i hope. Not sure if Advanced Coke Oven was this necessary, isn't it?

> There's a couple of other multiblocks that can be found in the Engineer's Handbook that are missing schematics

I would add this in TODO, but would be cool if someone would add this schematics and send me files, so i could add them to modpack!

**Comment by evanbones** [comment]
Looks like they thought it was unrealistic. Might be worth removing advanced coke bricks from JEI just so people don't waste their steel (like I did)?

I can maybe make some schematics if I have some spare time later

**Comment by Krutoy242** [comment]
> Might be worth removing advanced coke bricks from JEI just so people don't waste their steel (like I did)?

Soungs good! Added to TODO.

> I can maybe make some schematics if I have some spare time later

Schematics in low priority, so you have lot of time.

**Comment by Krutoy242** [comment]
Fixed via #40
