### ISSUE TITLE
Thaumic Additions research is still required but no longer obtainable

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#172]
With the rework of Thaumic Additions in the 0.91 version, it is no longer possible to obtain Thaumic Additions theories.
Many of the items from Thaumic Additions required Thaumic Additions theories in order to unlock, such as the void tools and robes.

I don't know if it's possible to change research requirements with craft tweaker.

I do know that the bit of code that determines research requirements for Thaumic Additions items is EnumKnowledgeType.THEORY, R_THAUMADDS found in the [KnowledgeTAR.java file](https://gitlab.com/DragonForge/ThaumicAdditions/-/blob/1.12.2/src/main/java/org/zeith/thaumicadditions/init/KnowledgeTAR.java) for the mod.

**Comment by Krutoy242** [comment]
I need to summon Thaumic Additions changes contributor here, maybe he could give answer @tabakasim

**Comment by TabakaSIM** [comment]
Yeah... I see the issue, i'm gonna fix that today!

**Comment by Krutoy242** [comment]
Fixed in https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v0.93.0
