### ISSUE TITLE
More mod suggestions: `Mekanism CE`

### ISSUE THREAD

**Issue by SteaSteaStea** [Krutoy242/Enigmatica2Expert-Extended#176]
Here's a few things I've come across.

[Mekanism 1.12.2 Community Edition](https://www.curseforge.com/minecraft/mc-mods/mekanism-1-12-2-ce) (Mostly bugfixes, should be compatible with old worlds)

[Mekanism Community Edition: GENERATORS](https://www.curseforge.com/minecraft/mc-mods/mekanism-ce-generators)

[PackagedAstral](https://www.curseforge.com/minecraft/mc-mods/packagedastral)

I could report back later to give some feedback on the Mekanism mod and if it causes any issues with the pack/prexisting worlds.

**Comment by Krutoy242** [comment]
> [PackagedAstral](https://www.curseforge.com/minecraft/mc-mods/packagedastral)

Yes, will be added next versions

> [Mekanism CE](https://www.curseforge.com/minecraft/mc-mods/mekanism-1-12-2-ce)

I want to ask you first - what features this Mekanism version has that we want? When I read the description, I don't see any benefits that this mod could provide.

**Comment by SteaSteaStea** [comment]
> > [Mekanism CE](https://www.curseforge.com/minecraft/mc-mods/mekanism-1-12-2-ce)
> 
> I want to ask you first - what features this Mekanism version has that we want? When I read the description, I don't see any benefits that this mod could provide.

There shouldn't be any new features. Just some optimizations and bugfixes:
"limit crystallizer to receive gas mutiples of recipe input" - this should fix gases getting stuck in machines and blocking your whole ore processing setup
"Fix Tier installer NullPointerException onItemUse" - I've had crashes from using tier installers in e2e, so I'm assuming this is what the fix is
"Optimize cable emitting" - I suppose this has to do with light updates though I may be wrong... anyways mekanism pipes/cables are the worst when it comes to optimization so I'm sure any kind of optimization would be nice to have

I haven't been able to find some more detailed info on all the fixes but the last update for Mekanism on 1.12 is from 2019. There's likely to be more bugfixes with this fork in the near future. Also if somebody comes across a bug a reports it here then it could be adressed by the people who maintain the fork since the official 1.12 version is out of support. 

Overall seems to be similar in concept to the AE2 Unofficial fork which the pack already has though Mek CE 1.12 has been around for just 2 months so it isn't nearly as fleshed out.

**Comment by Krutoy242** [comment]
Ok, i think i could try it
