### ISSUE TITLE
Thaumic additions Essentia Combiner hard crashes world when connected to filling transfuser

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#178]
The Essentia Combiner from Thaumic Additions hard crashes the world when a filling transfuser is connected to the output via tube.
The only solution I have found so far is to restore a backup that did not have the two blocks connected.

The Combiner itself is quite buggy, and seems to only work consistently with Essentia buffers.

It wasn't really an issue before, but with the amogus aspect now added with no source outside of the Combiner, it may become more of a problem. As of right now, amogus is required for a few recipes.

My suggestion is to replace amogus with an astral sorcery themed aspect and add a recipe for it to the starlight infuser.

**Comment by Krutoy242** [comment]
Thank you for the report, i will try to reproduce

**Comment by TabakaSIM** [comment]
About crash... Thaumcraft is 4,5 year old mod... That's probably a reason... (the crash itself was probably in the tubes logic)

I wasn't able to reproduce that crash 

As for Essentia combiner, it's working fine. It's true that it needs essentia buffer, but it is due to how thaumcraft tubes works (If you ever connected alembic with jar only using tubes, it just didn't work. The same is with essentia combiner)

![Screenshot - 2023-03-05 , 20_48_46](https://user-images.githubusercontent.com/78695622/222983107-d59a826c-038b-41db-97e8-fc3fd0b29e46.png)

**Comment by Krutoy242** [comment]
Also, @stiffchub provide crash logs please.

**Comment by stiffchub** [comment]
I made a clip of it happening. It may have to do with the amount of jars around. The setup has around 50 jars I think. I used to be able to get it to crash with no additional jars, but doesn't seem to do it now.

[crash-2023-03-06_09.39.04-server.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/10899493/crash-2023-03-06_09.39.04-server.txt)

[2023-03-06 09-38-59.webm](https://user-images.githubusercontent.com/112094041/223144192-c0ddaa48-1fe5-4b1a-8fb6-b325805ddffc.webm)


@TabakaSIM, just because a mod is old, doesn't mean it'll suddenly start breaking. Thaumcraft is very stable, and also not affiliated with Thaumic Additions.

**Comment by Krutoy242** [comment]
Thank you for the crash log, I will take a look later.

You can make your play easier by enabling `removeErroringTileEntities` in forge configs. You will not need to load backup with that option and would just continue playing, even without crash.

**Comment by Krutoy242** [comment]
I cant reproduce this issue. My Combiner working fine, and no other players reported same issue.

Seems like its only happens for your MC instance. I would like to help, but i don't know how (unless message above).
