### ISSUE TITLE
Mod Suggestion: `ModularMachinery: Community Edition`

### ISSUE THREAD

**Issue by KasumiNova** [Krutoy242/Enigmatica2Expert-Extended#181]
[ModularMachinery: Community Edition (MMCE)](https://www.curseforge.com/minecraft/mc-mods/modularmachinery-community-edition)

MMCE has better performance and compatibility, and is compatible with the existing ModularController.
It is also compatible with content from older game save and offers more interfaces for CraftTweaker.
However, the documentation on the mod page is not complete, so if you have the ability to read the source code, it may be a good choice, at least if it replaces MM.

**Comment by Krutoy242** [comment]
I will take a look on this, sounds interesting.

Through, I'm thinking to remove modular machines completely. So might not want to move on this.

**Comment by Krutoy242** [comment]
I decided to remove MM next patches so movind to MM:CE would be pointless
