### ISSUE TITLE
Mod suggestion: `IGIExteneded`

### ISSUE THREAD

**Issue by kierkking** [Krutoy242/Enigmatica2Expert-Extended#185]
The game information display is a very good mod for replacing and embodying HUD, it has the same expansion as Mystic Age, Blood Magic, Original, which you can find on CourseForge below is the link
https://www.curseforge.com/minecraft/mc-mods/igiexteneded
https://www.curseforge.com/minecraft/mc-mods/ingame-info-xml
Of course it also has Wiki using xml language, modify on config, my suggestion is to add, it supports hot reload and in-game enable and disable, the degree of freedom is very high, below is the wiki link
http://mc.lunatri.us/doc/legacy/igi/

**Comment by Krutoy242** [comment]
Thank you for suggestion, I will take a look.

**Comment by kierkking** [comment]
ok

**Comment by Krutoy242** [comment]
How to use this mod? I should study the wiki pages and add features to it?
What exactly features you would like to see in `E2E-E` provided by this mod?

**Comment by Krutoy242** [comment]
Also, cant launch modpack with it - causing crash

```less
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IGI Extended (igiextended)
Caused by: java.lang.NoClassDefFoundError: github/kasuminova/igiextended/Tags/IGIETags
    at github.kasuminova.igiextended.IGIExtended.postinit(IGIExtended.java:64)
```

**Comment by kierkking** [comment]
Sorry for my mistake, I didn't give the pre-link, because the author doesn't seem to give the pre-conditions on the course forge, these are two pre-loaded download links, which must be installed:
https://www.curseforge.com/minecraft/mc-mods/lunatriuscore
https://www.curseforge.com/minecraft/mc-mods/ingame-info-xml/files

**Comment by kierkking** [comment]
I would like to see memory usage, FPS, MSPT, TPS, TC6 aura and pollution in the game, as well as the LP level of blood magic, as well as the display of the four seasons, as well as armor, and the item information of the main hand and deputy can also be displayed on the game interface, thank you

**Comment by kierkking** [comment]
Here are some examples that I hope you will refer to
https://github.com/TCreopargh/GreedyCraft/blob/chinese/config/InGameInfo.xml
https://github.com/TCreopargh/GreedyCraft/blob/chinese/config/ingameinfoxml.cfg
The file is modified under the config folder

**Comment by Krutoy242** [comment]
> I would like to see memory usage, FPS, MSPT, TPS, TC6 aura and pollution in the game, as well as the LP level of blood magic, as well as the display of the four seasons, as well as armor, and the item information of the main hand and deputy can also be displayed on the game interface, thank you

We have everything this already available by once way or another.

I dont think i should need to remap whole F3 screen.

Also, messing up with configuring so much options would take a lot of time.

So, thank you for suggestion, but i dont believe this mod is give valuable benefits.

**Comment by kierkking** [comment]
ok
