### ISSUE TITLE
Terrible FPS when looking at the night sky

### ISSUE THREAD

**Issue by LuizLoyola** [Krutoy242/Enigmatica2Expert-Extended#19]
### Issue:
FPS heavily drops across the whole PC when looking at the night sky. Makes the game unplayable.
Average FPS when looking down (even at night): 115 FPS
Average FPS when looking up at the sky: 0~ FPS
GPU usage skyrockets, all the other apps (even when Minecraft is minimized) lags a lot.

### Reproduction Steps:
Literally look somewhere the sky is visible and is at night.

### Environment:
- Optifine: Yes
- GPU: Nvidia GTX 1650, 4K Monitor

### Observations:
- When the window is resized to something like Full HD, the FPS doesn't drop as much, but still drops from 150 FPS to 15 FPS with some terrible input lag.
- Slept on a bed through all the lag and low FPS. The FPS only came back up around 6:35 AM game time, prolly something related to Astral Sorcery Skybox?

# Images:
Looking down, at night, close to a village
![image](https://user-images.githubusercontent.com/20233048/151082587-78bcf9f6-ec40-445f-9f06-455b7e55065e.png)

Looking up, directly at the sky, same location as the last screenshot
![image](https://user-images.githubusercontent.com/20233048/151082769-0d9733cc-b1dc-4ca7-a846-1e4f72fc581b.png)

**Comment by LuizLoyola** [comment]
Adding to the issue: Also happens without Optifine, not as bad though.
Still drops the game and the whole PC to something like 1-2 FPS instead of 3 SPF (seconds per frame)

**Comment by LuizLoyola** [comment]
Found the issue. Definitely related to Dynamic Surroundings's Aurora.
Disabling it ingame through Mod Options solves the problem.

**Comment by Krutoy242** [comment]
Thank you for investigation!
I saw this problem too, but didn't know it was aurora.
Would be in next release.
