### ISSUE TITLE
Forestry bees do not produce secondary products if their base species' temp/humidity needs are unmet despite having temp/humidity tolerance

### ISSUE THREAD

**Issue by JustCallMeCharlie** [Krutoy242/Enigmatica2Expert-Extended#191]
## Description

Title, tested with Boggy bee and Austere bees in an industrial apiary, the bees have adequate temperature/humidity tolerance and are working and produce their main product, but not their secondary products until humidifier/temperature upgrades are installed.

**To Reproduce**
Make a boggy bee, give it max humidity tolerance and optional other tolerances (nocturnal etc) put in industrial apiary in an arid biome. wait for apiary to be active and producing its main product. the bee will never produce peat until humidifer upgrades are installed 

**Screenshots**
https://imgur.com/a/UDbKsVl

**Modpack version** `v0.89.0`

**Comment by Krutoy242** [comment]
Its called "Bee Speciality".

This is original, unchanged and vanilla Forestry bees mechanic.

https://ftb.fandom.com/wiki/Specialty

![image](https://user-images.githubusercontent.com/936618/227448149-eb1b8918-f695-452c-bd95-267a2a6800e7.png)

So, working as intended 😉
