### ISSUE TITLE
There is a problem with the priority of the drawer manager

### ISSUE THREAD

**Issue by wwxxyy123** [Krutoy242/Enigmatica2Expert-Extended#192]
My English is poor, so I can only explain my problems as clearly as possible.
Regarding the drawer controller, I recently upgraded my 0.89 version to 0.94 and I found that the item I entered into the drawer manager was no longer prioritized for the marked drawer but preferred for the drawer closest to the controller. I wonder if this is something you did on purpose or something went wrong.
For example, I put some stones in the drawer, and in version 0.89, when I enter stones into the manager, the stones will be preferentially entered into the drawer where the stones have been stored, and in version 0.94, the stones will be stored in the drawer close to the controller.

**Comment by Krutoy242** [comment]
Yes, i noticed this too.

This is most likely related to recent [Universal Tweaks](https://github.com/ACGaming/UniversalTweaks/issues) mod changes. Its recently change behavior of drawers to boost performance.

So i believe, it uses closes one now because its better for performance.

**Comment by wwxxyy123** [comment]
And I also found that the retrieval scope of the drawer manager is normal, but its interaction range is not normal, for example: I put three drawers vertically above a drawer manager, respectively with stones, dirt and diamonds, I can see these three items in the drawer manager, but when I use the funnel to input to the manager, stones and dirt can be entered normally, but diamonds cannot be imported.

**Comment by wwxxyy123** [comment]
Its interaction scope is not necessarily two, but there are cases where it is retrievable but not interactive. Also, when I wrap the manager in a circle with a drawer, it can't do anything interactive.

**Comment by Krutoy242** [comment]
Please attach screenshots of setups for last two problems

**Comment by wwxxyy123** [comment]
I don't quite understand what "set screenshot" means, this video may illustrate my problem. But this is an archive copied from version 0.89 to version 0.94, and in a new archive, there seems to be no such problem. When I have time, I may try to find the cause of this error.

Uploading 202303260808(1).mp4…

**Comment by wwxxyy123** [comment]
https://user-images.githubusercontent.com/128898550/227756744-c56f464e-c7ca-40a5-925d-a20228d4e03a.mp4

**Comment by wwxxyy123** [comment]
Yes, a similar problem arises in new archives, it seems that this error occurs when a certain number of stored items are stored?

**Comment by wwxxyy123** [comment]
You can take a few kinds of items from a drawer system with a lot of items and input them into the drawer manager with a catheter, and you will find that some items cannot be entered, specific types of items or those drawers that cannot be entered I did not analyze, which is too complicated.

**Comment by wwxxyy123** [comment]
Items that cannot be entered by a conduit can be interacted with through AE2 or  Integrated Terminals, and it seems that a conduit can be used to output from the manager, but it cannot be input with the manager.

**Comment by Krutoy242** [comment]
Can you help me with this issue little bit more?

I suspect mod `Universal Tweaks` as a reason for this issue.

Could you please follow this steps and answer is issue still happens
1. Create new Minecraft Instance
2. Install only mods `Storage Drawers` and `Universal Tweaks`. Use versions from `v0.94.0`
3. Install mod, that cant interact with drawers propertly (you mentioned EnderIO Conduits cant)
4. Launch a game and try to recreate all issues

If problem would persist with only this 3 mods installed, then i will investigate `Universal Tweaks` further.

P.S. Im using www.deepl.com as translator - you can use it to write messages too - very good result.

**Comment by wwxxyy123** [comment]
Okay, I'll try it.
Also I should mention that I didn't specifically say that EnderIO Conduits would interact correctly, I just used its handy filtering feature to try to see if it would output.

**Comment by wwxxyy123** [comment]
Yes, the error still occurs, both in terms of priority and interaction, and I simply added the jei、Storage Drawers 、 Universal Tweaks and their predecessors and a translation mod.

**Comment by wwxxyy123** [comment]
When I disabled Universal Tweaks, the drawer functioned properly again, and it does seem to be a problem with Universal Tweaks.

**Comment by Krutoy242** [comment]
Thank you for help! I will write about this issue to `Universal Tweaks` dev. Maybe he could fix that.

From now on, you can try to disable `Item Handlers` option in UT configs

![image](https://user-images.githubusercontent.com/936618/227762156-20363769-62e2-412a-a5fe-43443eea0155.png)
![image](https://user-images.githubusercontent.com/936618/227762167-6a93b0cc-c1f0-4243-ad3f-b1082f1dd434.png)
![image](https://user-images.githubusercontent.com/936618/227762175-5bb6d50c-e18f-4025-acb2-13a35c9b2cc6.png)
![image](https://user-images.githubusercontent.com/936618/227762182-8cb806b3-0c52-4287-97df-955108fb8b35.png)
![image](https://user-images.githubusercontent.com/936618/227762189-58eff31a-e38c-4ddb-a5e2-b76f38f98c4d.png)

**Comment by wwxxyy123** [comment]
Ok, when I disabled this option, the problem was solved.

**Comment by Krutoy242** [comment]
Fixed in 1.0.0
