### ISSUE TITLE
Sounds are playing multiple times and are generally distorted

### ISSUE THREAD

**Issue by SomeRandomPetey** [Krutoy242/Enigmatica2Expert-Extended#2]
This is a pretty general issue but I'll try to keep it in a good format

**Description of Issue**
Most sounds when played are being distorted, with some sounding like they're playing multiple times (swimming, walking) and others just not playing (quest completion sound)

**Steps to reproduce**
1. Play normally
2. Observe

**Expected Behavior**
Sounds should sound normal, with none of them being distorted in any way

**Actual Behavior**
Most sounds are distorted as mentioned before.

Notes: I *think* it's an issue with Sound Physics but not entirely sure

**Comment by Krutoy242** [comment]
Yes, this probably Sound Physics.
I will try to find reason, maybe there is configs that can change behaviour.

Can you please example what sounds not playing except quest completion? And what sounds repeating except walking and swiming?

**Comment by Krutoy242** [comment]
I spend this monthes trying to figure out what causing this.

First, i want to say that i cant hear **multiple sounds** anymore. I remember there was several times before.
Now, **walking** and **swimming** playing normally, one time.
Video with sound: https://imgur.com/irhQjFG
If multiple playing problems still happen - describe when in this thread.

Second, Sounds like **quest completion not playing**. I still continue looking for a reason, but removing Sound Physics wont fix this.

Also i found, that **sound playing on server can be different**. For example, in single-player world, i can ring ![Desk Bell](https://git.io/JtdJA "Desk Bell") from Bibliocraft, but on server it wont make sound 🤨

**Comment by Krutoy242** [comment]
I discovered, that removing `Sound Physics` fix *quest completion not playing* issue.
I will make a report to their repo then.

![Desk Bell](https://git.io/JtdJA "Desk Bell") issue on servers still need to be investigated.

**Comment by KreloX** [comment]
When the crafting sound from Dynamic Surroundings mod plays, it gets doubled end two variations of the sound play. You could try tweaking Dynamic Surroundings to fix the issues above if you haven't already.

**Comment by Krutoy242** [comment]
> When the crafting sound from Dynamic Surroundings mod plays, it gets doubled end two variations of the sound play. You could try tweaking Dynamic Surroundings to fix the issues above if you haven't already.

Yeah, i listen same. Probably i need to remove Dynamic Surrounding completely 😢

**Comment by Krutoy242** [comment]
Ok, seems like problem with ![Desk Bell](https://git.io/JtdJA "Desk Bell") was on Bibliocraft's side. It pointed in [last patch notes](https://www.curseforge.com/minecraft/mc-mods/bibliocraft/files/3647708).

**Comment by Krutoy242** [comment]
Since there no issue updates for 3 months and no one reported for same issue since then, i close the issue.

Also, in next release, `Dynamic Surroundings` mod would be optionable, that could fix issue too.
