### ISSUE TITLE
Bug: OTG missing preset

### ISSUE THREAD

**Issue by MortenJordan** [Krutoy242/Enigmatica2Expert-Extended#201]
I already installed the pack on v0.89 but gladly noticed v1.0 is out now. However when trying to generate the world with the new worldgen like shown in the changelog it's missing the BBOP preset which is the only one present in the screenshots. I can choose "AlienJungle", "BBOP-Extended" and "Void". Is BBOP-Extended the one to go with here?

**Comment by Krutoy242** [comment]
Yes, now BBOP called `BBOP-Extended` instead. I made changelog before i renamed it.

**Comment by MortenJordan** [comment]
Ah, alright my bad then. Thx for the quick reply
