### ISSUE TITLE
Logs yield 4 planks in crafting table

### ISSUE THREAD

**Issue by Neffrex** [Krutoy242/Enigmatica2Expert-Extended#202]
## Description
I noticed that if I put a log on the top left (first slot) of a crafting table it yields 4 planks instead of the normal 2 of any other slot.

**To Reproduce**
Put a log in the first slot of a crafting table, it should be clear that the output is 4 planks

![imagen](https://user-images.githubusercontent.com/52071446/232210085-59a8af27-f9b0-4912-9abf-520883e181ed.png)
![imagen](https://user-images.githubusercontent.com/52071446/232210106-b33e9714-b0cf-4957-9ef5-830886ffe430.png)

I managed to reproduce this behaviour in: Vanilla Crafting Table, Tinkers Crafting Station and Random Things Oak Crafting Table.

**Modpack version** `v1.0.0`

## Notes
I have 2 more mods added, but they're Client side only cosmetic mods: *Item Zoom* and *Item Physic Lite*

**Comment by Krutoy242** [comment]
Thank you for the report!

Yes, i noticed it too since version `v0.89.0` or even earlier. But i was need confirmation.

This sounds like an issue from CraftTweaker or its addons. I will try to fix that.

For now, take this as temporary bonus 😅

**Comment by git-confused** [comment]
possibly related: forestry wood in the top left slot produces 0 planks

**Comment by Krutoy242** [comment]
> possibly related: forestry wood in the top left slot produces 0 planks

Why information could be a clue.
Any wood from forestry? Other slots provide 2?

**Comment by git-confused** [comment]
I don't have the game open to check right now, but if I think the other slots gave 2 as usual

**Comment by mczph** [comment]
I have the same situation in my own modpack too.I tried to run the script with some mods in but failed to find the reason.Hope you can solve this one day.

**Comment by Krutoy242** [comment]
> I have the same situation in my own modpack too.I tried to run the script with some mods in but failed to find the reason.Hope you can solve this one day.
> 

Thank you for more info!

**Comment by friendlyhj** [comment]
It is an issue of Univeral Tweaks. I have submitted a PR to fix it.

**Comment by Krutoy242** [comment]
> It is an issue of Univeral Tweaks. I have submitted a PR to fix it.
> For now, you can disable `Crafting Cache` config.

Thank you for this information! 😲
