### ISSUE TITLE
MP mobs seem to have really long iFrames

### ISSUE THREAD

**Issue by MissPotato** [Krutoy242/Enigmatica2Expert-Extended#203]
## Description
Entities seem to have a lot of iframes after taking damage. Long enough for a creeper to fully charge before any more hits can be made. This stands true even with a full charge attack from a dragon bone and wood cleaver (so a pretty slow weapon). This is also really noticeable with even a vanilla bow as every other arrow will just bounce off.

Meanwhile, it seems like the player has way reduced iframes.

**To Reproduce**
1. Attack a mob
2. Attack again, hear "whiff" sound
3. Do no damage

**Modpack version** `v1.00.0`

**`debug.log` or Crash report**

**Comment by Krutoy242** [comment]
Thank you for the report!

Can you remove `Better Hurt Timer` mod and test if frames still too long?

**Comment by MissPotato** [comment]
Yes, it does seem that disabling that mod has made it so I can attack mobs again in multiplayer. I do see what this mod is trying to fix. I think it might be a bug caused by ping, as my ping is around 120. So 2-3 ticks of desync.

**Comment by Krutoy242** [comment]
> my ping is around 120

Ooof..
Can you report this issue here? https://github.com/BunnyCinnamon/BetterHurtTimer/issues

**Comment by MissPotato** [comment]
Yeah, will do!

**Comment by Krutoy242** [comment]
Fixed in next version since i decided to completely remove `BetterHurtTimer`
