### ISSUE TITLE
World from v0.89.0 cannot be loaded from v1.1.0 

### ISSUE THREAD

**Issue by HowdareyouBass** [Krutoy242/Enigmatica2Expert-Extended#206]
## Description

So i updated from version 0.89.0 to 1.1.0 and cannot load my world. It says "Cannot load world. The following OTG presets are not installed : Void". My world is not void type.

**To Reproduce**

1.Create world in v0.89.0
2.Update to v1.1.0
3.See error screen
4.Cry because all of your progreess could be gone.

**Screenshots**

![java_1CzYqvRFRm](https://user-images.githubusercontent.com/62214754/233271693-1dfc3bd6-05db-4e51-bf0f-b1a2c1f37ce7.png)
![java_br2rOBPDQM](https://user-images.githubusercontent.com/62214754/233271836-a998b972-e64e-43b9-8773-932cdf719dd9.png)

**Modpack version** `v1.1.0`

**Comment by Krutoy242** [comment]
Thank you for the report, we looking up for the solution.

**Comment by HowdareyouBass** [comment]
So i think i found temporary solution @Krutoy242 . What i've done is deleted dim-3 from save itself and OTG settings in save. Then i deleted void preset from Config.yaml in OTG. After that i copied Dimension.txt from new world that i created in v1.1.0 into my world and it worked.
![explorer_J8f6bmN9bx](https://user-images.githubusercontent.com/62214754/233286438-5a3b2e01-dded-4113-a0dc-2b21221aefbb.png)
![explorer_6FKklG1Myv](https://user-images.githubusercontent.com/62214754/233286446-45710238-382c-4bfd-8ffc-e9b44c2a71ea.png)
![notepad_6elOiYEE0s](https://user-images.githubusercontent.com/62214754/233286470-d525a30e-a05f-47b1-b489-90d155965f81.png)
![notepad_d2h7wEQ05H](https://user-images.githubusercontent.com/62214754/233286507-d004d649-6855-479f-a0d8-3486319ed5ab.png)
![Code_TuY9Ef48L5](https://user-images.githubusercontent.com/62214754/233286525-bcaeb242-5ae2-4f9e-a799-075d80d5065b.png)
![Code_1rygTFh05x](https://user-images.githubusercontent.com/62214754/233286561-90f0653f-7817-491a-af20-701130a29c63.png)
![Code_SR76STjpKz](https://user-images.githubusercontent.com/62214754/233286582-fc2b0161-47c7-4fc1-93e3-0df9d383276c.png)

**Comment by Krutoy242** [comment]
Thanks for detailed description of your fix. I will use this info to try to fix this for everyone.
