### ISSUE TITLE
Crash: `IllegalArgumentException: Cannot set property PropertyDirection` ...

### ISSUE THREAD

**Issue by asterane** [Krutoy242/Enigmatica2Expert-Extended#209]
## Description

`java.util.concurrent.ExecutionException:** java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block bithop:screwhop, it is not an allowed value`

The game crashes upon an attempt to craft with the ScrewHop (from the BitHop mod) in a crafting station. I had been attempting to craft a Smeltery Input. Note: only the items in the first two slots appeared at all; the other items I attempted to use to craft were destroyed. The issue recurs whenever a ScrewHop is placed in a Crafting Station slot.

**To Reproduce**

Place a ScrewHop item into a crafting station. If HEI was used, update the station by clicking an item.
Game crashes immediately, window remains open but empty.

**Modpack version** `v1.2.1`

**`debug.log` or Crash report**

[crash-2023-04-29_20.02.02-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11360348/crash-2023-04-29_20.02.02-client.txt)
[crash-2023-04-29_20.02.02-server.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11360349/crash-2023-04-29_20.02.02-server.txt)

**Comment by Krutoy242** [comment]
Thank you for the report! I most likely will remove this recipe.

**Comment by asterane** [comment]
Thanks for the pack! Just to clarify, I had been attempting to craft a vanilla Hopper, which appears to be the only recipe that uses the ScrewHop. This issue only happens with the Crafting Station (I believe because it renders the items on its top face).

I also found that it's possible to duplicate the ScrewHop item by dragging a stack across slots in a Crafting Table. Personally, my suggestion would be to remove the ScrewHop as it appears to have multiple interaction issues.
