### ISSUE TITLE
various suggestions

### ISSUE THREAD

**Issue by freopt** [Krutoy242/Enigmatica2Expert-Extended#21]
Born in a barn was implemented into forge like 4 years ago https://github.com/MinecraftForge/MinecraftForge/pull/4689

no mob spawning on trees features can be made in In Control very easily

from what I saw LootTableTweaker isn't even used and if it is switch to LootTweaker because its completely broken and hasn't been updated in 4 years

switch mystagradclochecompat to https://www.curseforge.com/minecraft/mc-mods/cloche-profit-peripheral

obfuscate and TESLA seemingly unused libraries/apis

switch quark to https://www.curseforge.com/minecraft/mc-mods/quark-rotn-edition

add https://www.curseforge.com/minecraft/mc-mods/flat-colored-blocks

unloader config needs to be exactly one entry (currently 2 although they're the same thing) otherwise it breaks https://github.com/Unnoen/Unloader/issues/5

doesn't seem like harvestcrafttweaker is getting updated so maybe just remove it

lastly personal opinion but there's just a lot of unnecessary bloat mods included, but it is extended so I can understand

**Comment by freopt** [comment]
also add
https://www.curseforge.com/minecraft/mc-mods/entity-culling
https://www.curseforge.com/minecraft/mc-mods/particle-culling

unless maybe theyre incompatible with something

**Comment by Krutoy242** [comment]
> Born in a barn 

✅ I didnt know. Nice catch! Would be removed next version.

> no mob spawning on trees

❓ Do you know modpack examples where this was implemented? Im not very good at InControl configs and dont know how to do this easily.

> LootTableTweaker isn't even used

✖ It used there https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/loot/LootTweaker.zs#L104
And i dont know how to replace it functionality with LootTweaker, because last one do not have functionality "remove from all tables".

> obfuscate seemingly unused libraries/apis

✅ Nice catch! Seems like it was used for some other mod that i removed.

> TESLA 

✖ Tesla used by **Industrial Foregoing**

> add https://www.curseforge.com/minecraft/mc-mods/flat-colored-blocks

✖ You just tells about bloating of mods, but Flat Colored Blocks is literally same as Little Tiles coloring capabilities. Its just the same and already included.

> switch mystagradclochecompat to https://www.curseforge.com/minecraft/mc-mods/cloche-profit-peripheral
> switch quark to https://www.curseforge.com/minecraft/mc-mods/quark-rotn-edition

✅ Thanks! Would do this next version.

> unloader config needs to be exactly one entry

✅ Ooo, i found that dimensions didnt unloaded, but thanks! Would be implemented

> harvestcrafttweaker is getting updated so maybe just remove it

✅ True, should do it.

> unnecessary bloat mods included

❓ Could you example this mods? Im trying to add all mods for a reason, not just sink them because i can.
Do you mean **Dynamic Surroundings** is unnecessary? Or maybe **Sound Physics**?

> also add https://www.curseforge.com/minecraft/mc-mods/entity-culling https://www.curseforge.com/minecraft/mc-mods/particle-culling

✅ Would try that. Through, not sure if other performance mods like Random Patches not did this already.

**Comment by freopt** [comment]
> > no mob spawning on trees

> ❓ Do you know modpack examples where this was implemented? Im not very good at InControl configs and dont know how to do this easily.

 I could do a PR

> > LootTableTweaker isn't even used

> ✖ It used there https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/loot/LootTweaker.zs#L104 And i dont know how to replace it functionality with LootTweaker, because last one do not have functionality "remove from all tables".

 didn't see that

> > TESLA

> ✖ Tesla used by **Industrial Foregoing**

 not required in latest IF 1.12 version https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/2745321

> ✖ You just tells about bloating of mods, but Flat Colored Blocks is literally same as Little Tiles coloring capabilities. Its just the same and already included.

my bad, not familiar with littletiles

> > unnecessary bloat mods included

> ❓ Could you example this mods? Im trying to add all mods for a reason, not just sink them because i can. Do you mean **Dynamic Surroundings** is unnecessary? Or maybe **Sound Physics**?

spark and LagGoggles are redundant
Animania and Better Animals Plus are redundant
I'm not sure how Animania and Better Animal Models work together because Animania replaces some of the vanilla animal models
Dude Wheres My Horse and Stupid Horse Stand Still are redundant
TellMe isn't going to be used outside of development
Although ToroHealth and Neat aren't the same thing, they're kinda similar
All Mekanism Fluxified does is change the inside of Mekanism energy buffers to red, seems pretty unnecessary
Smaller Nether Portals seems unnecessary to me
I'm pretty sure you can add a startup sound to Dynamic Surroundings, making Ding obsolete
While somewhat useful, Enable Cheats is unnecessary
Ping seems unnecessary with Vanilla chat and discord
Colossal chests seems unnecessary with all the storage things (iron chest, crates, ae2, etc.)
Fakename doesn't really fit into a pack like this IMO
CapabilityProxy and Actually Additions phantomface are pretty redundant
Environmental Materials is just deco materials many of which are already in other mods

> > also add https://www.curseforge.com/minecraft/mc-mods/entity-culling https://www.curseforge.com/minecraft/mc-mods/particle-culling

> ✅ Would try that. Through, not sure if other performance mods like Random Patches not did this already.

Culling is not a part of any other 1.12 performance mods akaik

**Comment by Krutoy242** [comment]
Ok, i would review this mods.

**Comment by Krutoy242** [comment]
> spark and LagGoggles are redundant

Thanks for the list of mods and comments. It helped me find a few bugs and revise the list. You will see changes in next release.

While I won't respond to every item, I will highlight a couple of things I think are important.

- Searching lagging blocks\entities is `spark` and `LagGoggles` for. Optimizing lags - **part of 400+ mods pack gameplay**.
- How to enable cheats without `Enable Cheats`? In vanilla there is only way to open game for lan, but this makes game running on background always.
- > `Ping` seems unnecessary with Vanilla chat and discord
  
    I played many times and usually "take items from THIS CHEST" is not enough 😄.
- `Environmental Materials` is simple mod with nice stairs and slabs. Other mods do not adds such nice-looking slabs and stairs.

**Comment by freopt** [comment]
> * `Environmental Materials` is simple mod with nice stairs and slabs. Other mods do not adds such nice-looking slabs and stairs.

you can do stairs and slabs with ArchitectureCraft

> * Searching lagging blocks\entities is `spark` and `LagGoggles` for. Optimizing lags - **part of 400+ mods pack gameplay**.

I understand that, but they both do the same thing. There is no need for both of them.

**Comment by Krutoy242** [comment]
> you can do stairs and slabs with ArchitectureCraft

This Stairs cant be used correctly by
1. Building Wands. They placed as default "Oak Planks" color
2. Block Placers. They turned wrong.
3. Dank Nulls. Placed wrong.
4. Schematica. Cant be used.

> There is no need for both of them.

Lag Goggles shows exact blocks that lagging the game. As far as i know, Spark cant do this. It shows lags by type of block instead.
Same time, Lag Goggles shows lag of parralel processes and other non-entity stuff wrong. For example, it actually shows that Integrated Dynamics item transfer load 1400% of tick, which is impossible.
