### ISSUE TITLE
Mod suggestions:`Sledgehammer`

### ISSUE THREAD

**Issue by mczph** [Krutoy242/Enigmatica2Expert-Extended#212]
[Sledgehammer](https://www.curseforge.com/minecraft/mc-mods/sledgehammer)

It can fix many bugs and improve performance(you need to open functions in the config due to they are disabled in default)

e.g https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/e18e8b5553a3d62caec9991bc99d47104ab32cc6/dev/TODO.md?plain=1#L157 (notice:gelid_gem tic material will disappear but you can readd it by contenttweaker) 
https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/e18e8b5553a3d62caec9991bc99d47104ab32cc6/dev/TODO.md?plain=1#L248

**Comment by mczph** [comment]
By the way [Thaumic Energistics Extended Life](https://www.curseforge.com/minecraft/mc-mods/thaumic-energistics-extended-life) is available on Curseforge,you can include it to your pack now.

**Comment by Krutoy242** [comment]
Thanks for suggestions! Im readying Sledgehammer description now.

For the `Multi Builder Tool` - how it better? I tested it already, and i found that its same as Schematica, but without several features, like folder structure. Maybe i missed some features that makes it better?

**Comment by mczph** [comment]
oh,i found 
![image](https://user-images.githubusercontent.com/103164772/236668545-aa586203-63a2-4725-bb63-2f08d10bb1a2.png)
so just ignore it.

**Comment by mczph** [comment]
It seems some of the problems have been fixed using bansoukou,but maybe it's better to use this mod,it's on your choice.
