### ISSUE TITLE
Astral Sorcery celestial gateway visual bug

### ISSUE THREAD

**Issue by DavidSarif** [Krutoy242/Enigmatica2Expert-Extended#214]
## Description

Rendering does not work right when the player is in celestial gateway multiblock. Among the darkness with numerous stars there are flickering bold lines of different colours. Additionaly, the previews of other portals are not shown.

**To Reproduce**

1. Build two celestial gateway multiblocks
2. Step in into one of them.
3. Observe the flickering.
4. Look at the yellow star of the other gateway.
5. Teleport to the other gateway. 
6. Look at the yellow star of the first gateway.
7. Observe the absence of gateway preview.
 
**Screenshots**
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/14242594/ef5c0d4b-deab-483b-9432-bde663fe2d86)
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/14242594/9c408fb1-048f-4f24-87ef-d796fc174aed)

**Modpack version** `v1.3.0`

**`debug.log` or Crash report**
No crashes, so adding latest.log, I hope it will help.
[latest.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11520360/latest.log)

**Comment by Krutoy242** [comment]
Thank you for the report, I will investigate the issue!

**Comment by Krutoy242** [comment]
I cannot reproduce the issue, rendering works fine for me.

https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/9b1f8d8f-cd1d-4c8a-a182-109a0ce91039

Seems like this issue depends on some kind of computer hardware or software.

Possible fix is update java. Your java is `1.8.0_51` and its 7 years old one.
Please update and answer if problem still persist. You can check your Java version on F3 screen or 5th line of `latest.log`

**Comment by DavidSarif** [comment]
![2023-05-23_21 39 48](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/14242594/8c1f18c1-61f6-4b72-95f9-ad717d414305)
Changed java to 1.8.0_371 – no effect. What version should I use?

**Comment by Krutoy242** [comment]
Strange.. This version is fine.

Do you use any shaders or additional mods?

**Comment by DavidSarif** [comment]
No shaders. I installed manually Sledgehammer before, but now this mod is already in the pack.

**Comment by Krutoy242** [comment]
You can try to remove this mods and see if problem fixed:

- FoamFix
- Random Tweaks
- BetterFps

Also, you can try to launch original E2E modpack and see if problem exist in it too.

**Comment by DavidSarif** [comment]
Removed FoamFix, Random Tweaks, BetterFps and CensoredASM mods at 1.5.0 : world load takes too long (more than 15 min), can't confirm if it works or not.
Played Sevtech modpack on the same device before: this glitch did not occur.

**Comment by DavidSarif** [comment]
The glitch vanished after I deleted one of the JourneyMap waypoints. Both no flickering occurs and celestial gate preview is rendering as it should.

**Comment by Krutoy242** [comment]
Could you say how I can add this waypoints to reproduce it?

**Comment by DavidSarif** [comment]
Double-click in the full-screen map; the problematic waypoint was approximately between two distant celestial gates. Can't provide more precise coordinates: already deleted it.

**Comment by Krutoy242** [comment]
I think this is very rare circumstances. I don't know how i could fix that, since this is most likely `Journey Map` or `Astral Sorcery` bug.
