### ISSUE TITLE
Incompatability with Dynamic Surroundings

### ISSUE THREAD

**Issue by DavidSarif** [Krutoy242/Enigmatica2Expert-Extended#215]
## Description

After last modpack update I can't run the modpack with Dynamic Surroundings mod installed: Minecraft crashes at launch.

**To Reproduce**

1. Install Dynamic Surroundings mod.
2. Launch the modpack.
3. Get the crash.

**Modpack version** `v1.3.0`

**`debug.log` or Crash report**

[2023-05-16-2.log.gz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11520439/2023-05-16-2.log.gz)

**Comment by Krutoy242** [comment]
Thank you for the report!

I didn't check logs yet, but this most likely `SledgeHammer` mod.

**Comment by mczph** [comment]
Here's a same issue https://github.com/embeddedt/aquaacrobatics/issues/44
You need to follow this to slove the problem
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/103164772/bc760186-58d1-4623-ae75-5138a05d7066)
