### ISSUE TITLE
Industrialcraft 2 electric motor is not craftable

### ISSUE THREAD

**Issue by DavidSarif** [Krutoy242/Enigmatica2Expert-Extended#217]
## Description

When components for the IC2 electric motor are placed in the crafting station no electric motor is formed. There is the same behavior when placing ingredients both via HEI and manually.

**To Reproduce**

1. Place 2 iron ingots, 2 tin item casings and copper wire coil in crafting station as in the recipe of electric motor.
2. No electric motor is formed.

**Screenshots**

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/14242594/56fc81f5-cab8-4f71-998e-eaad9b6e3d7f)

**Modpack version** `v1.3.0`

**Comment by Krutoy242** [comment]
Thank you for the report!
Are you sure this coil have at least 9 block length?

**Comment by DavidSarif** [comment]
> Thank you for the report! Are you sure this coil have at least 9 block length?

Thanks! Tried with 13 length coil: it worked.
Did not notice that Industrial wires have varying length: I suggested they are as simple as default IE wires. Can we have some memo in the corresponding quest?

**Comment by Krutoy242** [comment]
For the motor recipe, where you suggest to place info about 9 length required?

**Comment by DavidSarif** [comment]
There was a quest where Industrial wires were introduced: maybe add to this quest description something like "Industrial wires can be of different length. Some recipes that use industrial wires need wires with certain length" in it.

**Comment by Krutoy242** [comment]
Got it!

**Comment by Krutoy242** [comment]
Will be added note in quest book next version.
