### ISSUE TITLE
Not opening on my pc

### ISSUE THREAD

**Issue by redznn** [Krutoy242/Enigmatica2Expert-Extended#219]
## Description

Not opening on my pc

**Modpack version** `v1.50.0`

**`debug.log` or Crash rep
[crash-2023-05-26_18.53.33-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11580234/crash-2023-05-26_18.53.33-client.txt)
ort**

**Comment by Krutoy242** [comment]
Are you using resource packs or other mods?

**Comment by redznn** [comment]
OptiFine only, but same without OptiFine

**Comment by Krutoy242** [comment]
Ok. There is probably 0_52 Java version. I will check out log later.

**Comment by Krutoy242** [comment]
Ok, Java is fine.

- Try to remove mod `FoamFix` and see if bug persist.
- If previous not help, remove `CensoredASM` too

**Comment by redznn** [comment]
Ok, i will check

**Comment by Krutoy242** [comment]
@redznn so, did you fixed issue?
