### ISSUE TITLE
World restarts when updating server to 1.5

### ISSUE THREAD

**Issue by dimauloagustin** [Krutoy242/Enigmatica2Expert-Extended#221]
## Description

I'm trying to upgrade a 1.3 e2e-e localserver to 1.5, but when I logged into the server it created a new world.
This is also something that happened to me when I upgraded from 1.2.1 to 1.3.0 but after many tries I was able to get it to work, sadly I don't remember how I did it.

**To Reproduce**

My working 1.3 server: https://drive.google.com/file/d/1EkxT343nbsBZTN3jUywH48QR6NtV2fPb/view?usp=share_link
download 1.5 server files from curseforge
delete folders: bansoukou, config, mods, patchouli_books, schematics, scripts and structures. As in SERVER_GUIDE
start the server.

**Modpack version** `v1.5.0`
[latest.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11585902/latest.log)

**Comment by dimauloagustin** [comment]
After several more retries, the server opened the old world (I honestly don't know what I did differently)

**Comment by Krutoy242** [comment]
I'm glad it fixed itself 😁
