### ISSUE TITLE
bug The title interface cannot be accessed

### ISSUE THREAD

**Issue by kierkking** [Krutoy242/Enigmatica2Expert-Extended#222]
## Description
modpack  version 1.6.0

**To Reproduce**

**Modpack version** `v0.00.0`

**`debug.log` or Crash report**
https://paste.org.cn/qUZsEFZ3sU

**Comment by Krutoy242** [comment]
Try to remove FoamFix and see if problem persist

**Comment by kierkking** [comment]
censoredasm5.10.jar became to censoredasm5.9.jar
 problem-solving method

**Comment by Krutoy242** [comment]
Good!
