### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by agrotom** [Krutoy242/Enigmatica2Expert-Extended#224]
## Description

Hi. After updating from 1.5.0 to 1.7.0 i'm not able to play the modpack because it crashes on loading screen because of Redstone Arsenal (according to crash-report). 

**To Reproduce**

1. Startup modpack
2. See error

**Modpack version** `v1.7.0`

**`debug.log` or Crash report**
https://mclo.gs/SL6ZNrr
[crash-2023-06-04_00.15.45-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11643542/crash-2023-06-04_00.15.45-client.txt)

**Comment by Krutoy242** [comment]
Thanks for the report! I was mistakenly added wrong mod version. More info here:

https://github.com/LoliKingdom/MixinBooter/issues/31#issuecomment-1569375803

**Comment by agrotom** [comment]
Thank you for a fast reply. I've downgraded the mod and this made modpack work.
