### ISSUE TITLE
Please mark the server pack file as such in curseforge

### ISSUE THREAD

**Issue by natanfudge** [Krutoy242/Enigmatica2Expert-Extended#227]
The server file should look like this 
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/25990014/9dadc49f-7b70-46a5-947f-16eb09260d28)
But it looks like this
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/25990014/9178b3b3-3101-4424-bdf0-6232a574a55c)

Which makes it not identifiable as a server pack by automated tools. For instance, fixing this would allow hosting this pack on Aternos.

**Comment by Krutoy242** [comment]
Seems like the only option i have is manually mark server pack as "server" on CF website... Duh ☹
