### ISSUE TITLE
Tungsten Dust can't be melted

### ISSUE THREAD

**Issue by MortenJordan** [Krutoy242/Enigmatica2Expert-Extended#228]
Tungsten Dust can't be melted in the NuclearCraft melter in v1.9.0 even though JEI shows it as a recipe

**Comment by Krutoy242** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Krutoy242** [comment]
I cannot reproduce the issue, its working fine for me:

![G62ZPi8PA5](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/fb197ace-632a-4bbb-864b-9b6024b42eff)

Can you reproduce it in new creative world?

**Comment by MortenJordan** [comment]
I think I found the problem, I got my Tungsten Dust from the Immersive Engineering Crusher because I wanted to get the Manganese side product as well. But the Crusher gives out Tungsten Dust from the Quantum Minecraft Dynamics mod which can't be processed like the one you have in the GIF (which you get through SAG Mill and Enrichment from Mekanism)

https://imgur.com/a/wGWK66X

**Comment by Krutoy242** [comment]
Oh, thank you for additional info! Will fix that.
