### ISSUE TITLE
Unable to synthesize ic2:upgrade.

### ISSUE THREAD

**Issue by ls314** [Krutoy242/Enigmatica2Expert-Extended#229]
The coolant cannot enter the carpenter.
There are hot coolant in the carpenter tabulation but no coolant.
modpack version:1.9.0

Sorry,I don't speak English.
So it can only be described through translation software.

**Comment by ls314** [comment]
But it can be made in version 1.7.1

**Comment by Krutoy242** [comment]
Show me screenshot of what you trying to do.

**Comment by ls314** [comment]
![9826f518d485ce02648f89c0108a5d0](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137019119/b64a293e-9d92-445f-b9d9-3c8f474302b6)
![d3382d5f82bc3fbf54bf978b15d9e90](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137019119/b0a9b65d-848a-4357-a9db-649d7f28d52d)
![f0fe6bb67172534c2c97a8e57861240](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137019119/3ae5808f-40ad-4e93-a6b3-1d4182b407c8)

**Comment by Krutoy242** [comment]
1. Can you reproduce it in new creative world?
2. Does it work if you put liquid inside with a bucket?

**Comment by ls314** [comment]
> 

Neither 1 nor 2 can be achieved.

**Comment by ls314** [comment]
I started the game today and found that I can make it now.
I don't know why.
Wishing you happiness every day:)

**Comment by Krutoy242** [comment]
I always love when issues fixed by itself😁
