### ISSUE TITLE
"Any container with ..." dupe (Universal Cells, other stackable Tanks)

### ISSUE THREAD

**Issue by LeeOn777** [Krutoy242/Enigmatica2Expert-Extended#230]
Crafting conduit binder with a universal cell will dupe the cells. 

Playing on v1.9.0

**Comment by Krutoy242** [comment]
Thank for the report. 
Could you attach screenshot of recipe? Or you talking about cell with liquid sand?

**Comment by LeeOn777** [comment]
![2023-06-24_17 57 48](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137647136/30062b34-7537-4e9c-bb6d-3b13e16ad84e)
![2023-06-24_17 57 52](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137647136/5d9a5a66-3e66-4b79-b5c1-d2b19e59d547)

**Comment by LeeOn777** [comment]
If you do it in a regular crafting table it will not consume the cells.

**Comment by Krutoy242** [comment]
Seems like it happen with ANY recipe that accept Universal Cell as ingredient...

**Comment by Krutoy242** [comment]
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/4a21ac10-5f2f-4d90-ab2c-9a42bcef8458)

I found that you can dupe any stackable container with this recipes

**Comment by Krutoy242** [comment]
Found that this is CraftTweaker bug https://github.com/CraftTweaker/CraftTweaker/issues/1692
