### ISSUE TITLE
`Batch Crafter` (IC2) dupe recipes with various ingredient amount

### ISSUE THREAD

**Issue by LeeOn777** [Krutoy242/Enigmatica2Expert-Extended#231]
Using an IC2 batch crafter to craft copper wire it will craft it for free.

Playing on v1.9.0

**Comment by Krutoy242** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Krutoy242** [comment]
To clarify bug, this is how it looks in game:
![javaw_gSAuADWXyD](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/1287912e-e82e-42f2-84e5-5fad04998cc8)

I need further investigation, but I don't know how to actually fix that, since this is a recipe from `Industrial Wires` mod.

**Comment by Krutoy242** [comment]
I found that Batch Crafter dupe every recipe with wildcarder ingredients

https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/2da62289-092c-441e-9f51-691b8e1a9efc

**Comment by Krutoy242** [comment]
Seems like the issue wont be fixed by `IC2-Patcher` devs.

I could remove `Batch Crafter` from the game, but i think this dupe is not so obvious and game breaking, so i could just ignore it and mark as "one of the 100+ known dupes".
