### ISSUE TITLE
Typo in Spectre Coil Info

### ISSUE THREAD

**Issue by TAMATLT** [Krutoy242/Enigmatica2Expert-Extended#234]
## Description

Typo in the information tab for "Spectre Coil NXXX"

**To Reproduce**

Take a look at the information tab "Spectre Coil NXXX", it says it generates 128 RF/t, while in the pop up description and in reality it is 32 RF/t.

**Screenshots**

![SpectreCoil](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/113747883/e67ab1e3-7ced-4413-ac0d-66b53b8c2c33)
![ToolTipSpectreCoil](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/113747883/81ec8c0a-159b-455e-962f-ad3c2d3d541a)

**Modpack version** `[v1.9.0]`

**Comment by Krutoy242** [comment]
Thanks for report! Gonna fix.
