### ISSUE TITLE
Commands in yellow are impossible to read

### ISSUE THREAD

**Issue by IzdebskiMichal** [Krutoy242/Enigmatica2Expert-Extended#242]
It is really difficult or almost impossible to read these commands in yellow ( or any other things that are in yellow )

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/36077834/64c7a571-7a7f-4025-aa89-c32b9ca8b8ff)

Any chance I get to know what are these commands? :)

**Comment by Krutoy242** [comment]
Oh, it's really hard indeed. I will fix it later then.
You can check out tips on GitHub Wiki
