### ISSUE TITLE
Quest Inconsistancy: The `Animals Entry` quest

### ISSUE THREAD

**Issue by DDriggs00** [Krutoy242/Enigmatica2Expert-Extended#243]
The Initial quest in the animals tab claims to reward spawn eggs, but offers bait instead. Either the description or the rewards should be changed. Also, the cow behavior described is for cows from the removed Animania mod.

**Modpack version** `v1.14.1`

**Comment by Krutoy242** [comment]
True! Thank you for the report, I forgot to fix that quest after Animania removal.
