### ISSUE TITLE
Server configuration \ Server World Gen

### ISSUE THREAD

**Issue by PatRakowicz** [Krutoy242/Enigmatica2Expert-Extended#244]
Hello,

I was just wondering where the sever configuration "options" are found. 

For example if I want to create a new world using the new generation how would that be possible. 

Would I have to gen the world and then move it to the sever? Thanks.

**Comment by Krutoy242** [comment]
You may search in web how to start Minecraft server. Questions you asking is not modpack dependent, and even vanilla.

File with options you seek is `server.properties`

**Comment by PatRakowicz** [comment]
Disregard, figured it out.
