### ISSUE TITLE
Structures spawning with no loot in chests

### ISSUE THREAD

**Issue by Ari0** [Krutoy242/Enigmatica2Expert-Extended#246]
I've created 3 default worlds and 2 OTG worlds and I keep running into structures, mainly the village ones, that have no loot in any chest. Most recently the big house that has all of the bookcases and enchantment tables. They spawn together as single chests rather than double chests as well. I am using the latest version of the pack and the only thing I changed was adding Optifine 1.12.2 G5 Ultra and changing the weakskyrenders in the astral sorcery config.

**Comment by Krutoy242** [comment]
Chests without loot is fine - some structures doesn't have any loot in them at all. No loot defined in their structure files.

**Comment by Ari0** [comment]
Oh ok sorry about that thank you for clarifying!
