### ISSUE TITLE
Is there a way to stop pickaxe melting coal

### ISSUE THREAD

**Issue by NNPJS** [Krutoy242/Enigmatica2Expert-Extended#249]
Just made firewood handle for my pickaxe and now every single coal ore turning into Graphite from Nuclear Craft. Tried to search this option in mod setting and configs of Tinker's Construct and Nuclear Craft, but didnt find any way to stop this

**Comment by Krutoy242** [comment]
Replace handle with other material. You cant disable this feature by other means.

For questions like this better to visit my discord https://discord.gg/VcmyHdNNQP 😉
