### ISSUE TITLE
Bug in rotorlist.zs script

### ISSUE THREAD

**Issue by Thalzamar** [Krutoy242/Enigmatica2Expert-Extended#250]
Elektron60 Stator Recipe being bugged/faulty
[rotorlist.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/12442051/rotorlist.zip)
either replace it with the one i posted or change in there
"elektron","Elektron", 0.80"
 to
"elektron","Elektron60", 0.80"

**Comment by Krutoy242** [comment]
Thank you for pointing to bug! I will fix that!

**Comment by Thalzamar** [comment]
well i made that stuff XD
you can thank random guy on the NC discord since he found the stuff wrong with my addon 
there are also problems in the magnetlist and extractor list , i just packaged them in this zip
thank god i used classes , makes bug fixing really easy when recipes arent working cause i used wrong oredict names 
[scripts.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/12442656/scripts.zip)

**Comment by Thalzamar** [comment]
btw. i also made https://legacy.curseforge.com/minecraft/customization/immerisve-nuclear-steam
if you want some nuclearcraft-immersive technology scripts with added moar reactor funtionality compatibility(like heat exchanger recipes) but it also needs a config change for the inventory of the IT heat exchanger to 20000

**Comment by Thalzamar** [comment]
no clue if it's the list or the recipes script that is outdated 
already fixed mercury on a newer version but the fix isnt ingame 
[converters.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/12444882/converters.zip)

**Comment by Krutoy242** [comment]
> i also made immerisve-nuclear-steam

Yes, i saw that before. But i discovered your code only after i already made my own IE integration with NC:O.
https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/mods/nuclearcraft.zs#L736-L740

I didn't look deeper into your code and can't say if its better to move to your INS addon. Maybe i could look deeper later.

> converters.zip

Im not sure what changes this actually about. I have similar already.

Also, there is an error in your code.
```less
itemUtils.getItem("nuclearcraft:turbine_dynamo_coil_antitritiumconverter")*2
```
This syntax makes no sense. Since, if there is no `nuclearcraft:turbine_dynamo_coil_antitritiumconverter` defined, `itemUtils.getItem()` returns `null` and script fall anyway, since it cant multiply `null * 2`.

**Comment by Thalzamar** [comment]
that one does exist just not as a class one 
i added it directly in the convertregistration since all the antimatterstuff dont have classes 
i am doing a lot of copy paste of code parts thats why some look pretty weird like the antimatterstuff
![grafik](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/48890032/8be80cc4-3007-4877-b64b-7575cdb69ebf)

**Comment by Krutoy242** [comment]
> that one does exist just not as a class one i added it directly in the convertregistration since all the antimatterstuff dont have classes i am doing a lot of copy paste of code parts thats why some look pretty weird like the antimatterstuff ![grafik](https://user-images.githubusercontent.com/48890032/263463667-8be80cc4-3007-4877-b64b-7575cdb69ebf.png)

No no, i was talking about exactly this line:
```less
recipes.addShaped("ntp base Converter coil", itemUtils.getItem("nuclearcraft:turbine_dynamo_coil_baseconverter")*2,
```

You dont need to use `itemUtils.getItem` because you better to use brackets like `<nuclearcraft:turbine_dynamo_coil_baseconverter>`.

**Comment by Thalzamar** [comment]
i copied pasted it from others thats why i it looks like that 
i was just too lazy to do the brackets thing
