### ISSUE TITLE
Unable to craft Ender IO basic capacitor with Advanced Rocketry Precision Assembler

### ISSUE THREAD

**Issue by ShermanWu** [Krutoy242/Enigmatica2Expert-Extended#252]
## Description
Unable to craft Ender IO basic capacitor with Advanced Rocketry Precision Assembler

**To Reproduce**

Place Redstone Conductance Coil x64, Titanium Iridium Alloy Rod x64, Grains of Infinity x64 in Precision Assembler input hatch.
Precision Assembler does not process items.

Other Precision Assembler items are processed normally.

**Modpack version** `v0.18.1`

**Comment by Krutoy242** [comment]
Thank you for the report! I will fix that.
