### ISSUE TITLE
Small typo in quest description

### ISSUE THREAD

**Issue by dhasial** [Krutoy242/Enigmatica2Expert-Extended#255]
## Description

There's a very minor typo in the Utilities section for the 'Random Things' quest that describes how to use floo powder.

One word says 'arrrive' instead of 'arrive'.

[I was trying to just edit it and make a pull request myself but couldn't find the right snbt file to edit using ripgrep]

**Comment by Krutoy242** [comment]
Thank you for pointing out!

You can find quest text in folder `resources/ftbquests/lang/en_us.lang`. Try to change it here.
