### ISSUE TITLE
Lag when using tool station/tool forge

### ISSUE THREAD

**Issue by 12-4-25** [Krutoy242/Enigmatica2Expert-Extended#256]
## Description

The game freezes upon using a tool station or tool forge
I am playing with my friends, and the bug also happens to them.

**To Reproduce**

1. Right click a tool station or a tool forge
2. Lag

**Screenshots**

https://youtu.be/E3DrszT7XUM

**Modpack version** `v1.19.0`

**Comment by Krutoy242** [comment]
Please, try to remove VintageFix and test it again.

**Comment by Krutoy242** [comment]
I made an issue on VintageFix github https://github.com/embeddedt/VintageFix/issues/76

**Comment by 12-4-25** [comment]
Fixed after removing VintageFix.
