### ISSUE TITLE
Golden Lasso Dupe Bug

### ISSUE THREAD

**Issue by curlywaffles** [Krutoy242/Enigmatica2Expert-Extended#259]
## Description

When using Extra Utilities Golden Lasso on Thaumic Additions: Reconstructed Chester, the chest is put into the lasso but then also drops on the ground. Basically a Chester duping bug.

**To Reproduce**

Right click Chester with Golden Lasso.

**Screenshots**

N/A

**Modpack version** `v0.00.0`

1.20.0

**Comment by Krutoy242** [comment]
Thank you for the report, I will investigate the issue.
