### ISSUE TITLE
Replace InventoryTweaks with Inventory Bogosorter

### ISSUE THREAD

**Issue by ChromaPIE** [Krutoy242/Enigmatica2Expert-Extended#264]
Inventory Bogosorter: https://www.curseforge.com/minecraft/mc-mods/inventory-bogo-sorter

It's being actively maintained and much less buggy than InventoryTweaks

**Comment by Krutoy242** [comment]
Thanks for suggestion! Yes, I'm gonna migrate to bogosort next patch.

**Comment by Krutoy242** [comment]
Done in `v1.21.0`
