### ISSUE TITLE
Bug: Can't create any empowered crystals using actually additions empowerer

### ISSUE THREAD

**Issue by dhasial** [Krutoy242/Enigmatica2Expert-Extended#265]
## Description
Empowerers do not work for crystals, but they do work for empowered canola seeds. After inserting the outer ingredient items, I cannot insert the crystal to the empowerer at the last step of crafting.

I've also noticed that I can't place the crystal on the stand at all unless it's in block form (which also doesn't work). This is something else, probably related, that doesn't happen on upstream E2E

[below, the word "failed" means I can not insert the crystal to be empowered in the central empowerer block at any point]

So far I've tested this:
* My normal save in E2E-E, a creative world on the same instance; It failed on both
* A brand new install of E2E-E with only my save copied over, and a new creative world; it failed on both
* An install of the upstream of this fork, plain E2E; it worked as expected, got empowered X crystal item

[I've tested diamatine, restonia, and palis crystals so far and they all either fail or succeed together, there hasn't been any crystal that works while the others don't, excluding canola]

**To Reproduce**

**Modpack version** `v1.12.0`

**Comment by Krutoy242** [comment]
You probably found empowered crystals recipe in AA book, right? Sadly, but I can't change recipes straight in book. Only recipes that shown in JEI works.

Instead of using crystal recipes you should use block ones. I removed crystal recipes since they was too expensive - for the same amount of ingredients you get only x9 times less output.

**Comment by dhasial** [comment]
Unfortunately the block forms of the crystals also don't seem to work in the same way the single crystals do. I also agree that a block is more efficient, but it would be better not to disable the recipes outright, and to instead allow the player to learn that on their own and decide for themselves.

**Comment by Krutoy242** [comment]
Thanks for suggestion! But I believe that there is already a lot of fields to learn on. Spending x9 times more resources on items sounds more like a mistake rather than learning.

**Comment by dhasial** [comment]
Also iirc, the script change made it where crystal blocks could be placed on the central empowerer but couldn't be empowered, they just sat there like a display stand. I need to make sure the script is what caused it though.

**Comment by Krutoy242** [comment]
Everything that could be placed on empowerer could be impowered.
