### ISSUE TITLE
Supplementary guide on dealing with UU Metal Ore

### ISSUE THREAD

**Issue by ChromaPIE** [Krutoy242/Enigmatica2Expert-Extended#266]
First of all my game language is not en_us so ignore it if it's already implemented in en_us:
Those who never cares about LittleTiles might have to spend their whole lives figuring out how to extract UU metal from its ore, so maybe there should be an extra tooltip or one line of words or two to let ppl make a Little Bag and put the ores in.

Also UU Metal Sharpening Kit upgrades mining tools to the same level as Terrasteel and Crystal Matrix but got excluded from that quest. Was it intended?

**Comment by Krutoy242** [comment]
Hmmm, probably i should guide players how to use Little Tiles propertly. I surely dont want to just write it in quests because reading is boring.
I dont know how to do that in quests or in game - if you have ideas, tell me 😀

> UU Metal Sharpening Kit upgrades
Yeah, i could probably add UU Metal ingots to mining level quest

**Comment by ChromaPIE** [comment]
just add a side quest somewhere requiring a block of uu metal ore, a little bag and a uu metal block to complete and it should be fine, but i got no idea where could be the best place for it.

**Comment by Krutoy242** [comment]
> and a uu metal block

I don't like this idea, since I don't really want to force players to search and mine those blocks

**Comment by ChromaPIE** [comment]
that ore was literally everywhere lol. and scannable works fine with LT blocks. but reaching ratlantis was kinda grinding so if its me i would put this side quest after a certain existing one that cant be done outside of ratlantis, like those late stage quests in the Rats questline, reasonable and not forcing no one. and UU metal is a pretty decent material for TiC tools, with the mining level at 11 plus some good traits, so there should be enough positive feedback for those who decided to sweat over Rats.

**Comment by Krutoy242** [comment]
Thank you for suggestions.

I'm thinking, maybe I could also remove UU metal ore from quest mention altogether. Because in this case, players would understand that it's their own adventure to understand why it's spawning.

**Comment by ChromaPIE** [comment]
Yea that could be a solution for this. also is it possible to add a crafting guide page in JEI for the ore using Requious Frakto?

**Comment by Krutoy242** [comment]
I think I could say that I partially fulfill your suggestion - on version `v1.22.0` there is JEI tab with conversion from ore to UU metal block.
