### ISSUE TITLE
typing error

### ISSUE THREAD

**Issue by ZZZank** [Krutoy242/Enigmatica2Expert-Extended#273]
## Description

There seem to be some typing error in `resources/contenttweaker/lang/en_us.lang` , listed as below: 

- warp.sword.speak.random.0=§o§5 `I will put in the grave` as many as I can, just one swing is enough!§r
I don't if this is actually an error, it could be some kind of abbreviation. 
- warp.sword.speak.kill.4=§o§5Another tasty `flash` 
 `flesh` I guess
- tooltips.lang.reinforced_cell_frame=The Reinforced Cell Frame (Full) can only be made in a Fluid Transposer with an internal buffer of `250.000` RF or more.
The dot is a bit misleading and can be interpreted as 250, maybe `250,000` will be better. 
- tooltips.lang.drop_at_night=§3Drop §n%s§r§3 on §n%s§r§3 `undert` night sky
`under` ?
- Also, in some entries, I found such a word `strenght` , maybe originally it is `strength` . 

**Modpack version** `v1.21.0`

**Comment by Krutoy242** [comment]
Thanks for the report! I will fix that.

**Comment by Krutoy242** [comment]
> I don't if this is actually an error, it could be some kind of abbreviation.

What means abbreviation? Add `"` symbols?

**Comment by ZZZank** [comment]
That's because `I will put in the grave` seems missing something. Usually I would use `put sth. in` instead of just `put in` , but `put in` could be some kind of special usage, so I say "could be some kind of abbreviation"

**Comment by Krutoy242** [comment]
> That's because `I will put in the grave` seems missing something. Usually I would use `put sth. in` instead of just `put in` , but `put in` could be some kind of special usage, so I say "could be some kind of abbreviation"

Sorry, i didnt get it 😅

**Comment by ZZZank** [comment]
Nevermind, that could be my problem. The usage that I'm familiar with is `put {something} in {someplace}` , say `put an apple in the cabinet` . That's why `put in the grave` feels wrong for me, and I would suggest inserting something, for example `put these souls in the grave` . 
But I just search this expression on an dictionary, and given its result, maybe my feeling is not that correct. 
Feel free to ingnore this lang entry.

**Comment by Krutoy242** [comment]
👍
