### ISSUE TITLE
Impossible to craft supremium armor cores from construct's armory

### ISSUE THREAD

**Issue by CACOKKOTA** [Krutoy242/Enigmatica2Expert-Extended#274]
## Description

Impossible to craft supremium armor cores from construct's armory

**To Reproduce**

1. Get any supremium armor piece core base and master infusion crystal
2. merge them on anvil like JEI says
3. See that it's impossible to craft because of minecraft's "Too expensive!"

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/113460989/5a424ce8-0aa9-47fc-9756-545fb0e961e5)

**Modpack version** `v1.20.0`

**`debug.log` or Crash report**

**Comment by Krutoy242** [comment]
Just take item from output slot ignoring "too expensive" line 😅
