### ISSUE TITLE
wireless terminal deletes items when sorted

### ISSUE THREAD

**Issue by SpaceEngineerJulia** [Krutoy242/Enigmatica2Expert-Extended#275]
## Description

Using the Inventory Bogo Sorter command "Sort Inventory" (bound to mouse middle click by default) deletes all items in your inventory if used while a Wireless Crafting Terminal (appliedenergistics2:wireless_crafting_terminal) is open. This but only manifests with that particular item, no other ae2 terminal, wireless or otherwise, has this bug. This bug does not depend on this particular key binding, it appears with any key bound to "Sort Inventory". Disappeared items do not appear in the ae2 system, adventure backpack, cyclic extended inventory, nor thrown on the ground.

**To Reproduce**
1. Create a minimal AE2 system by placing together and connecting an ME Controller, Security Terminal, and a Wireless Access Point; and then powering the system.
2. Bind a Wireless Crafting Terminal (appliedenergistics2:wireless_crafting_terminal) to the ae2 system using the security terminal
3. Open the Wireless Crafting Terminal (appliedenergistics2:wireless_crafting_terminal) with some items in your inventory.
4. Middle click (assuming default key bindings) on an item in your inventory, and any items in your inventory, but not your hotbar, will disappear.

**Modpack version** `v1.22.0`

**`debug.log` or Crash report**

The point of the log where the items were deleted starts at line 75437, at time [00:32:32] 

[debug.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/12865282/debug.log)

world save where I reproduced the issue

[wireless_terminal_deletes_items.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/12865307/wireless_terminal_deletes_items.zip)

**Comment by Krutoy242** [comment]
Thank you for perfectly described issue report!

**Comment by brachy84** [comment]
This is AE2's fault. I made an issue at their repo

**Comment by Krutoy242** [comment]
I hope this would be fixed..
Can you temporary fix that by disabling sort if AE2 terminal is opened?

**Comment by brachy84** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/4796184

**Comment by Krutoy242** [comment]
@SpaceEngineerJulia could you update AE2 and try to reproduce issue again?

**Comment by SpaceEngineerJulia** [comment]
I'll try and see what happens

**Comment by SpaceEngineerJulia** [comment]
updating AE2 Unofficial Extended Life to v0.55.24 appears to fix the bug. everything sorts correctly with no item deletion.

**Comment by Krutoy242** [comment]
Great! Thank you for helping!

**Comment by Krutoy242** [comment]
Fixed is latest release.
