### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by coder-Zzx** [Krutoy242/Enigmatica2Expert-Extended#28]
Unluckily, it seems that a crash hit again
heres the crash report
https://github.com/coder-Zzx/coder-Zzx/blob/main/crash-2022-03-01_15.40.44-server.txt

**Comment by Krutoy242** [comment]
Thank you for your reports!

Seems like its regular "low memory" error.
1. How much memory you allocated?
2. When this crash happen?
3. How i can reproduce this crash?

P.S. Please include short error description in Issue name when creating new one.

**Comment by Krutoy242** [comment]
Did the crash happen again?
If it doesn't happen again, I'll close the issue.
