### ISSUE TITLE
[Just Enough Characters] can't work

### ISSUE THREAD

**Issue by ChristmasZCY** [Krutoy242/Enigmatica2Expert-Extended#282]
Hello, I'm want to use Chinese in it, but When I added [Just Enough Characters](https://www.curseforge.com/minecraft/mc-mods/just-enough-characters), it can't wok. When I played the E2E, it can work, I wanna to use Chinese, can you help me.

**Comment by ChristmasZCY** [comment]
> Why it's not work? Does it crash?

No, there's no crash. In theory, after loading, I can search through Chinese pinyin, for example, stone means 石头 in Chinese, and I can search through shitou in JEI, but it doesn't work now.

**Comment by Krutoy242** [comment]
There is chinese player that help me with translations. Maybe he knows how to configure it @ZZZank

**Comment by ZZZank** [comment]
The JEI used in E2EE is called HEI, a fork of JEI. So after you installed JECh, you need an extra mod called HECh to make Pinyin search work. 
E2EE 里用的是 HEI，是 JEI 的分支。所以安装了JECh之后还需要安装一个HECh，这样才能拼音搜索

**Comment by Krutoy242** [comment]
So, is your issue fixed?

**Comment by ChristmasZCY** [comment]
> So, is your issue fixed?

Yes. Thank you so much.  @Krutoy242 @ZZZank
