### ISSUE TITLE
Glitches about non-en_us gaming on servers

### ISSUE THREAD

**Issue by ChromaPIE** [Krutoy242/Enigmatica2Expert-Extended#283]
## Description

If im guessing it right the crafttweaker script fetches all items' displayed names for the recipe IDs, so here's the problem: now the client, which was booted up with a different language setting, and the server, which has the language forced at en_us and you can't in any way overwrite it with resourcepacks, resource loader mods, etc. Bansoko might work but bruh, you dont want to edit all those jar files one by one).

This causes the client and the server to have differed recipe IDs, thus in fact breaking Just Enough Drags' function, the actual behavior, according to my test, is that you can't write, but can only overwrite existing items with ghost items in the crafting grid of pattern terminals, there might be more problems with this mod. And, trying to code crafttweaker-modified recipes into a pattern gives you an invalid one, obviously it's also caused by the recipe ID.

Sure there's workaround and im currently playing with one that solves the problem mentioned above: Before quitting the game set the language to en_us, so next time the game will boot up fetching items' english names for the IDs, after that i'll set the language back to mine then we good.

But yea thats still kinda annoying and thats why this issue is here.

**To Reproduce**

What's above should be enough to explain everything.

**Modpack version** `v1.21.0`

**Comment by Krutoy242** [comment]
Does ghost items or recipe patterns actually using recipe names? As far as I know, recipe IDs used only by CraftTweaker and advancements, and rarely with some guide books.
I mean, I could easily make recipes use non-localized IDs.

**Comment by ChromaPIE** [comment]
i know little about how things work internally but starting the game in english simply fixes the problems

**Comment by Krutoy242** [comment]
Ok, i will try to test and fix it.
