### ISSUE TITLE
Death does not fall.

### ISSUE THREAD

**Issue by Dovelet1** [Krutoy242/Enigmatica2Expert-Extended#284]
Hello, after death, I need to restore the items from the last death, what is the instruction

**Comment by Krutoy242** [comment]
Try command `/tmg_restore @p latest`

**Comment by Dovelet1** [comment]
It shows the blue box, when I jump, he also jumps, there is a grid several grids, what is this, how to turn it off

<img width="1113" alt="image" src="https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/129474085/da343cc7-b46b-4fcd-8cdf-c14a6c6ff980">
<img width="1261" alt="image" src="https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/129474085/758c7ea2-fe6e-47aa-985c-d616b189a87a">

**Comment by Krutoy242** [comment]
Use /grid

**Comment by Krutoy242** [comment]
Seems like you fixed issue, so I closing it.

For more questions please join my discord.
