### ISSUE TITLE
ERROR: java.lang.NullPointerException message in the chat

### ISSUE THREAD

**Issue by Bulwarini** [Krutoy242/Enigmatica2Expert-Extended#291]
## Description

When right clicking on another player on multiplayer server, two messages apear in the chat

**To Reproduce**

Join a server.
Right click on another player.
Done.

**Screenshots**
![obraz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/81563389/f6bc3fe4-1d4c-4e7d-b4d2-79b188cb093c)

**Modpack version** `v1.24.2`

<!--
Please provide file `debug.log` from directory `logs/`.
You may need to zip `debug.log` because its usually too big.

[17:45:54] [Client thread/INFO]: [CHAT] §cERROR: java.lang.NullPointerException
[17:45:54] [Client thread/INFO]: [CHAT] §cERROR: java.lang.NullPointerException

**Comment by Krutoy242** [comment]
Thank you for the report! 
This error not harm - I just forgot to remove debug message when releasing.
Fixed next patch.

**Comment by Bulwarini** [comment]
Thank you for quick answer 
;-]
