### ISSUE TITLE
About some machines

### ISSUE THREAD

**Issue by ChristmasZCY** [Krutoy242/Enigmatica2Expert-Extended#294]
Have the manufactory in Nuclearcraft and and dehydrator in Cyclic been deleted?

**Comment by Krutoy242** [comment]
Yes, they are.
Manufactory is just another macerator, and dehydrator lagging hard

**Comment by ChristmasZCY** [comment]
> Yes, they are.
> Manufactory is just another macerator, and dehydrator lagging hard

That's too bad. Manufactory works very well

**Comment by Krutoy242** [comment]
Macerator works very well too!

**Comment by ChristmasZCY** [comment]
> Macerator works very well too!

Thank you！
