### ISSUE TITLE
Consider adding Neeve's AE2 and according questline

### ISSUE THREAD

**Issue by ChromaPIE** [Krutoy242/Enigmatica2Expert-Extended#295]
[Neeve's AE2: Extended Life Additions](https://www.curseforge.com/minecraft/mc-mods/nae2)

I can't actually give 10 Reasons Why You Need NAE2, but as an endgame player basically all features described [here](https://github.com/NotMyWing/NAE2/wiki) in their wiki are just useful.

For `Ctrl Click to Craft Missing Items` some mod in E2E-E which i dont actually know what it is already got it implemented, but seems like the NAE2 one has an extra feature that `Shift+Ctrl+Click would also automatically skip the Crafting Plan menu if all requirements are satisfied.`
I dont know if they cause any conflict nor if both or any one of them are disableable.

Also, the ctrl clicking `+` feature is not functional in wireless terminal, by the way.

**Comment by Krutoy242** [comment]
I will take a look on features and stability.

Through, i don't want to add untested mod, so i could add it only if there would be volunteer players who install it and play for some time.

**Comment by ChromaPIE** [comment]
did a little test on it and did some notes. for the stuff mentioned below check their [wiki](https://github.com/NotMyWing/NAE2/wiki)

Pattern Multi Tool - yet another bauble item. super useful for it wiping out a fricking annoying thing that you have to quit the GUI to reset your coded pattern.

P2P Tunnel - ME Interface - you can easily come up with a thousand circumstances where you can make good use of it simply by looking at its name. and it supports AE2FC reworked.

ME Beam Former - comes in pairs to form a 32-block max, (configurable) straight, (that it, pure x or y-axis extension) ghost, (pure visual thing, players can go into it, but solid blocks break the connection. beam, you know) beam to replace cables, thats it. modifying the wireless connector's recipe to include this can be fun. not too op for me. its native recipe isnt cheap already, and all it can achieve is less cables present in the world.

Ctrl+Click to Craft Missing Items feature - seems like it disables itself when Not Enough Energistics, which provides the same feature, is detected. no conflict nor error in the log, but for the problem that NEE's ctrl crafting refuses to work on wireless terminals, there's an unsolved [issue](https://github.com/vfyjxf/NotEnoughEnergistics/issues/47).

so it is, or seems to be quite stable.

**Comment by Krutoy242** [comment]
Added in `v1.28.0-beta`
