### ISSUE TITLE
💥 Singularity abilities

### ISSUE THREAD

**Issue by Krutoy242** [Krutoy242/Enigmatica2Expert-Extended#3]
Singularities is too useless now (`39` items used only to craft 1 ultimate singularity). I can add different abilities to them.
For example - Make coal singularity burnable.

<img src="https://i.imgur.com/rcpUwH9.gif" width=300>

There is ideas i have for now. Im open for more suggestions!

Is final | ID | Name | Effect
---:| ---:|:---|:---
✅ | 0 | **Coal** | Huge Burn Time
✅ | 1 | **Iron** | Press Plates (used as hammer in hidden recipe turning 1 ingot => 1 plate)
⬜️ | 2 | **Lapis Lazuli** | Turns water into IC2 coolant
⬜️ | 3 | **Redstone** | Produce Power. Maybe by `TE Enervation Dynamo` or other machines, but wont consumed or working enternety
⬜️ | 4 | **Glowstone** | Infinite glowing nano-particles by right-clicking. Similar to `Illumination Wand` from AS
⬜️ | 5 | **Gold** | ❔ (`"❔"` means "not sure" and "need help") Infinity gold when smelted. For example, when smelting output itself + 1 gold ingot.<br>OR somehow related to trades with villagers
⬜️ | 6 | **Diamond** | Give indestructible to Tinkers tools and armor. Similar to 5 `Reinforcement` upgrades
⬜️ | 7 | **Emerald** | Custom villager trades for OP items (idea by @setisblue). What items?
⬜️ | 16 | **Aluminum** | ❔ Infinity ImmersEngin wires (click to create wire coil)
⬜️ | 17 | **Copper** | ❔ Something about Steam
⬜️ | 18 | **Tin** | ❔ Free cans when picking up liquids
⬜️ | 19 | **Bronze** | ❔ Something about breaking blocks
⬜️ | 22 | **Silver** | Holy damage zombies. Probably special TCon Trait
⬜️ | 23 | **Lead** | ❔ Radiation protection
⬜️ | 24 | **Steel** | ❔ Something about Machine cases
⬜️ | 25 | **Nickel** | ❔ Something about fuel
⬜️ | 26 | **Constantan** | Free Shell and bullets for railgun or revolver. Maybe auto-reloading Revolveur
⬜️ | 27 | **Electrum** | ❔ Capacitor upgrades somehow
⬜️ | 28 | **Invar** | ❔ Hardening Cell Frames
⬜️ | 29 | **Mithril** | ❔ Turn manasteel blocks into mithril
✅ | 32 | **Uranium** | Nuclear Fuel
⬜️ | 34 | **Platinum** | ❔ Chemical reaction catalyst. Probably used to turn one chemicals into another
⬜️ | 35 | **Iridium** | ❔
⬜️ | 48 | **Signalum** | Create destabilized redstone ORE from regular redstone ORE
⬜️ | 49 | **Lumium** | ❔
✅ | 50 | **Enderium** | Teleportation 5000 blocks to look vector
⬜️ | 64 | **Ardite** | ❔ Increase durability of tools
✅ | 65 | **Cobalt** | Generates a BoP's **Blue Fire** on click
⬜️ | 66 | **Manyullyn** | ❔
⬜️ | 100 | **Quartz** | ❔ Something about chiseling
✅ | 101 | **Certus Quartz** | Instantly grow AE2 Pure Quartz Crystals
⬜️ | 102 | **Black Quartz** | Makes Black Quartz from Regular Quartz
⬜️ | 103 | **Hard Carbon Alloy** | ❔
⬜️ | 104 | **Magnesium Diboride** | Black Iron crafting catalyst: when used to craft Black Iron, outputs way more
✅ | 105 | **Thorium** | Nuclear fuel
⬜️ | 106 | **Fluxed Electrum** | Produce Power, similar to Redstone Singularity
⬜️ | 107 | **Flux Crystal** | ❔ Charge items in hand
⬜️ | 108 | **Fluix** | ❔ Free wires
⬜️ | 109 | **Titanium** | Increase Mining speed. Probably special tool trait
⬜️ | ultimate | **The Ultimate** | ❔

**Comment by setisblue** [comment]
Emerald singularities could be used in custom villager trades for OP items

**Comment by Krutoy242** [comment]
> Emerald singularities could be used in custom villager trades for OP items

Sounds exactly what i need! I just recently found mod to tweak villager trades. Added to list!

Also, what items its could be? Like, OP tools or machines?

**Comment by Krutoy242** [comment]
Seems like there is no community help from Jan 2021 😅

So i would close issue and do it myself.
