### ISSUE TITLE
Essentia Storage Cell disassemble is not consistent (shift + right click)

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#30]
## Description
The recipe for thaumcraft ME storage is not consistent, and when shift right clicking it returns the housing (and no component, but im not 100% sure about that)

**Screenshots**
![image](https://user-images.githubusercontent.com/78452357/158037996-651914f7-96c1-4a73-abac-012ce8ee6e64.png)

**Modpack version** `v0.49.0`

**Comment by Krutoy242** [comment]
Thank you for the report, i will investigate this.

**Comment by Srdjan-V** [comment]
### I did some testing and it's quite interesting, i decided to shift click every available storage cell
![Screenshot 2022-03-16 190318](https://user-images.githubusercontent.com/78452357/158659013-f675a18b-148e-475c-85cb-db6815db82af.png)

### First time i only got the 16k
![Screenshot 2022-03-16 190400](https://user-images.githubusercontent.com/78452357/158659050-f23211d4-a181-452b-ac14-86cff2e93169.png)

### The second time i got 4k 16k 64k
![Screenshot 2022-03-16 190520](https://user-images.githubusercontent.com/78452357/158659286-6d953e20-df6b-492f-842c-29113debff78.png)

### After that i did it 4 more time, and always got the 4k 16k 64k back
![Screenshot 2022-03-16 192007](https://user-images.githubusercontent.com/78452357/158660357-c9c3fcf0-0a76-4814-a065-dbba43866178.png)
![Screenshot 2022-03-16 192048](https://user-images.githubusercontent.com/78452357/158660362-30b82e22-308e-44c3-91f8-4d74ef14f962.png)

**Comment by Srdjan-V** [comment]
If it is possible to disable the right-click function, my suggestion would be to disable it for every type of cell, and make it recyclable through the arc furnace.

**Comment by Krutoy242** [comment]
I cant fix this issue 😓

- ThaumicEnergetics not have config option to disable right-click functionality.
- I cant cancel event with CraftTweaker, because item use event not fired at all.

I can only suggest to find relative issues on ThaumicEnergetics issue tracker or create new one https://github.com/Nividica/ThaumicEnergistics/issues
