### ISSUE TITLE
Molten Tungsten cannot form ingot from Tinkers' Smeltery

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#301]
All tungsten items can be melted using a Tinkers' Smeltery but molten tungsten can only be turned into ingots using an ingot former from Nuclearcraft.
Looks like this is due to molten tungsten now being from Quantum Minecraft Dynamics instead of End Reborn.

**Comment by Krutoy242** [comment]
Thank you for the report! I will investigate the issue.
