### ISSUE TITLE
Chester dupe

### ISSUE THREAD

**Issue by DecoDragon** [Krutoy242/Enigmatica2Expert-Extended#302]
Pushing Chester (from Thaumic Additions: Reconstructed) into an twilight forest portal drops chester and spawns another on the other side of the portal. Will not dupe items held by chester.

**To Reproduce**

push chester into twilight forest portal

**Screenshots**
![2023-11-06_10 56 00](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/67518462/332ae6e1-8540-4ff7-b528-365c29a1df85)
![2023-11-06_10 56 08](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/67518462/2e39248f-b8c4-44e7-a458-b8f36dde4d3a)
![2023-11-06_10 56 12](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/67518462/90ede34a-addd-4364-a1b7-6351ad1e2274)
![2023-11-06_10 56 20](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/67518462/f66ca30c-a0ef-47d6-b63f-713c39368f53)

**Modpack version** `v1.24.2`

**Comment by Krutoy242** [comment]
Thank you for the report!
I will try to find what I could do with that, but if it's not dupe items inside it's fine I believe.
