### ISSUE TITLE
Morphing Tool uses old IC2 wrench

### ISSUE THREAD

**Issue by LinkIsGrim** [Krutoy242/Enigmatica2Expert-Extended#304]
Title. Particularly problematic when using IC2 liquid pipes as the interface for setting connections won't appear. Adding the wrench to the tool manually doesn't work (old wrench is used).

**Comment by Krutoy242** [comment]
This is impossible to put two wrenches in same morphing tool. And old wrench is more useful than (new) one - it can rotate and pick up machines, that more handy.

Thus, i dont want to change wrench to new one. If i missing something please point me.

**Comment by LinkIsGrim** [comment]
Fair enough. It's a pretty niche use-case for the new wrench, and while it's not annoying it's not like IC2 pipes are commonly used beyond early game.
