### ISSUE TITLE
Using Alfheim instead of Hesperus (suggestion)

### ISSUE THREAD

**Issue by Drunkender** [Krutoy242/Enigmatica2Expert-Extended#310]
Recommend by the creator of [Hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus) to use [Alfheim Lighting Engine](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine) instead of his mod.

**Comment by Krutoy242** [comment]
Thanks for suggestion, i will take a look!

**Comment by Krutoy242** [comment]
moved in `v1.26.0`
