### ISSUE TITLE
Adding/Fixing Hunger In Peaceful

### ISSUE THREAD

**Issue by Mihnea229** [Krutoy242/Enigmatica2Expert-Extended#313]
Hello,  I wanted to play the modpack in peaceful difficulty so I've installed the mod "Hunger in Peace" but the mod does not work, after this I removed hunger in peace and I have edited the config for "Hunger Overhaul" setting all "difficulty scaling" settings to true. It still does not work. Maybe I am missing a setting?

**Comment by Churn3d** [comment]
So the game can be completed in Peaceful, you just want the normal hunger mechanics in peaceful mode?

**Comment by Mihnea229** [comment]
Yes, to add a bit of challenge.

**Comment by Krutoy242** [comment]
Peaceful is playable, but hunger in peaceful is not intended. I don't know how to change that and why your configs not working.
So, I believe you need to figure out it yourself!

Also, I think that no hunger is more challenge than with hunger since it's harder to get additional health.

**Comment by Mihnea229** [comment]
Ok, thanks.

**Comment by Mihnea229** [comment]
Ok, thanks.
