### ISSUE TITLE
There is a problem with the Astral entry for the Tinkers' Evolution

### ISSUE THREAD

**Issue by wangxiaoyang776** [Krutoy242/Enigmatica2Expert-Extended#318]
I was playing version 1.26.0 recently, and when I tried to resonate a tool with a Astral entry in the Attunement Altar of Astral Sorcery, I found that my tools became tools with all stats of 0, which may have something to do with the restart of the Tinkers' Evolution, but when I rolled back the version of the Tinkers' Evolution, my client couldn't even open.Now I'm trying to make my tool in an earlier version and bring it back to 1.26.0.

**Comment by Krutoy242** [comment]
This is TConEvo bug. Its disused here: https://github.com/phantamanta44/tinkers-evolution/issues/127

Seems like solution could be somewhere in tconevo config files.

**Comment by wangxiaoyang776** [comment]
Okay, I'll see if the lower version of the tool works on the higher version, maybe you can fix this by lowering the mod version before the TConEvo fixes?

**Comment by Krutoy242** [comment]
> Okay, I'll see if the lower version of the tool works on the higher version, maybe you can fix this by lowering the mod version before the TConEvo fixes?

Its could not be fixed with TConEvo downgrade. As mentioned in linked thread, other mod `Random Tweaker` breaking TConEvo functionality. I could only remove `Random Tweaker` to achieve this.

**Comment by Krutoy242** [comment]
> could i see a server log, please?

Sure! I will send it later.

**Comment by Krutoy242** [comment]
> could i see a server log, please?

[debug.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/13605325/debug.log)

**Comment by Krutoy242** [comment]
> should be fixed in https://github.com/phantamanta44/tinkers-evolution/commit/cfbeb411ce013e65ac04a90c66580903d662ff7a; I've just pushed the 1.0.49 jar with the patch to curseforge

Thanks! I will update and test later.

**Comment by Krutoy242** [comment]
Fixed in https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.27.0-alpha
