### ISSUE TITLE
Crash: `java.lang.NullPointerException: Ticking player` (after killing Enderman)

### ISSUE THREAD

**Issue by ThuursDay** [Krutoy242/Enigmatica2Expert-Extended#323]
## Description

The game crashes upon picking up or hovering over a drop (untextured item) of an enderman

**To Reproduce**

1. Spawn an enderman
2. Kill it
3. Pick up the item (or hover over the drop in a container if it fell into one)

**Screenshots**

**Modpack version** `v1.28.0-beta`

**`debug.log` or Crash report**

//username edited to thuurs
[debug.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14001333/debug.log)
[crash-2024-01-21_13.10.45-server.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14001334/crash-2024-01-21_13.10.45-server.txt)

**Comment by ThuursDay** [comment]
![2024-01-21_13 43 30](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/37485169/faa41eb1-8b8e-4b37-962b-f0f35942aefe)
![2024-01-21_13 43 21](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/37485169/405e9c15-a659-4dc7-b889-2f554f89eb2e)
forgot to add the screenshots.

**Comment by Krutoy242** [comment]
Thank you for the report!

This is happens since i recently removed bunch of items from mod EndReborn.

To temporary fix this issue:
1. Go to file `config\malekremoveregistries.txt`
2. Remove line `endreborn:food_ender_flesh`

This steps will make Endermans drop Mysical Flesh as before.

**Comment by ThuursDay** [comment]
Got it, thanks
