### ISSUE TITLE
Empty chests in mineshaft

### ISSUE THREAD

**Issue by bsv222** [Krutoy242/Enigmatica2Expert-Extended#326]
Minecarts with chests (in mineshafts) are ALWAYS empty.
I've been playing your build for a year. And I'm waiting for a fix with each update, since only these chests have the loot I need. (Bat's traveler backpack, for example)
![2024-01-23_23 46 34](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/157520708/9353a263-2428-4b26-8926-5cdc1e06a706)
![2024-01-23_23 46 41](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/157520708/9b87665a-9aa9-4063-bc82-ed475598fc77)

**Comment by Krutoy242** [comment]
Thank you for the report!
I dont know why this happens and have no clue how to fix.

Can you help me? Try this please:
1. Remove **Lootr**
2. Load game
3. Generate new **BoP** world
4. Find mineshaft
5. Check at least 3 loot carts in different shafts

**Comment by bsv222** [comment]
The problem is solved. A reward appeared in the chests. Can I keep playing without Lootr?
Will I lose something interesting without this mod?

**Comment by Krutoy242** [comment]
You can play without Lootr for sure! Its just for multiplayer and can be removed from client.

**Comment by bsv222** [comment]
Dear Krutoy242! 
Could you post a list of mods for playing multiplayer? I want to remove these mods for single player and faster loading. 

Thanks for amazing modpack!

**Comment by Krutoy242** [comment]
> Dear Krutoy242! Could you post a list of mods for playing multiplayer? I want to remove these mods for single player and faster loading.
> 
> Thanks for amazing modpack!

This is not related to original Lootr chests issue. For such questions, please write in <a title="Join us on Discord!" href="https://discord.gg/VcmyHdNNQP"><img src="https://img.shields.io/discord/911676461050642432?label=E2E-E%20Discord&amp;logo=Discord&amp;style=?flat" alt="Discord"/></a>

In short: i dont have such list.
