### ISSUE TITLE
Lootr chest can`t be opened

### ISSUE THREAD

**Issue by SikiciBebek** [Krutoy242/Enigmatica2Expert-Extended#327]
## Description
Chest are generated but nobody is able to open them

**To Reproduce**

**Modpack version** `E2E-Extended-v1.26.0`
[latest.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14029196/latest.log)

**`debug.log` or Crash report**

**Comment by Krutoy242** [comment]
How to reproduce? Whenever I opening chests, they always working fine


https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/af800b1e-a06e-4957-b2b9-b45e8c50d34e

**Comment by SikiciBebek** [comment]
I´m spamming right click on them, but they wont open.

Idk why or how to reproduce it :c

**Comment by Krutoy242** [comment]
Try this:

1. Try to restart server
2. Try new chest in recently generated chunk
3. Try to send `logs/debug.log` file

**Comment by SikiciBebek** [comment]
[20:13:45] [Server thread/ERROR] [Lootr]: replacement TE net.minecraft.tileentity.TileEntityChest@460be02f is not an LootrInventoryTileEntity dim 0 at BlockPos{x=-3419, y=40, z=1940}

Thats what it says in the logs 

And here is the debug file after restarting
https://gist.github.com/SikiciBebek/459ad1bcce980130afdadcda3e05bc86

**Comment by SikiciBebek** [comment]
i might know the reason
i think its because of chunk pregenerator. The allready generated chunks (and chests) do not work.
Sry to taking your time have a great one :D

**Comment by Krutoy242** [comment]
What method you used to pregenerate?

**Comment by SikiciBebek** [comment]
I used Chunk Pregenerator.
added it on the server and client (only for me)

**Comment by Krutoy242** [comment]
Oh, yeah, it could cause biome corruption.

**Comment by SikiciBebek** [comment]
:c rip
i texted them the issue. hopefully they fix it ^^
ty for your help :D
