### ISSUE TITLE
Native Clusters processing in SAG Mill recipes not working

### ISSUE THREAD

**Issue by Aliagor** [Krutoy242/Enigmatica2Expert-Extended#328]
Recipes are appearing in JEI with items according to config for JAOPCA but byproducts from processing them in SAG Mill are not obtainable. In 1.26 it was working fine, every later version has it broken. In attached image from 1.26 you can see that if you hover over any byproducts from Native Clusters recipes in SAG Mill you can see % chance of getting this item. This information is gone in versions 1.27 alpha, 1.28 beta and 1.29 (recipe is not working properly for these versions).

![obraz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/34624207/7916c8ed-2e21-480d-99ba-8a293e486038)

It seems that one of changes made for 1.27 alpha update broke it. I tried looking through commits after 1.26 release but have not found anything obvious that could cause it. Update included a lot of performance improvements so maybe one of commits for performance or deleted files also removed byproducts from these recipes? Also some mods have been updated, some have been deleted and some added, so it might also be possible cause of this issue.

**Comment by Krutoy242** [comment]
Most likely one of added / updated mods is the reason.
First concerning mods is
Added:
- [Malek's Infinity Gauntlet](https://www.curseforge.com/minecraft/mc-mods/maleks-infinity-gauntlet)
- [Just Enough Magiculture](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture)
Updated:
- [Roughly Enough IDs](https://www.curseforge.com/minecraft/mc-mods/reid)
- [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks)
- [VintageFix](https://www.curseforge.com/minecraft/mc-mods/vintagefix)

**Comment by Aliagor** [comment]
Tried on 1.29 version:
- Removed [Malek's Infinity Gauntlet](https://www.curseforge.com/minecraft/mc-mods/maleks-infinity-gauntlet)
- Removed [Just Enough Magiculture](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture)
- Downgraded [Roughly Enough IDs](https://www.curseforge.com/minecraft/mc-mods/reid) to 1.26 state
- Downgraded [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks) to 1.26 state
- Downgraded [VintageFix](https://www.curseforge.com/minecraft/mc-mods/vintagefix) to 1.26 state

This did not fix the issue.

Started with 1.29 version and changed all mods to be exactly like in 1.26 and issue was still there.

Started with 1.26 version and updated mods to 1.29 state -> Native Clusters are working properly. Screenshot with working recipe and JEI search for Neeve's AE2 addon (mod from newer modpack versions than 1.26)
![obraz](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/34624207/22366c77-e9b9-40fa-8e40-03d4d6e29832)

Seems that mods might not be causing this issue if I'm understanding this correctly. I'll try reversing some changes made in 1.27 update on my 1.29 test instance to try and find possible cause of this problem.

**Comment by Aliagor** [comment]
I decided to replace scripts folder on my 1.29 instance with scripts folder from 1.26 and clusters are working properly. I have noticed that this [commit](https://github.com/Krutoy242/Enigmatica2Expert-Extended/commit/89370d03bf11494e7c0e195ecef296c79a5844d7) was a formating one. It sorted a lot of imports and removed some of them, also moved around other parts of code usually at start of files. I don't know if it matters for these files but I've seen a lot of code in C or C++ (for example) stop working after auto-format decided to sort includes.

**Comment by Krutoy242** [comment]
Yes, its may be related. I will take closer look to this commit then.

**Comment by Krutoy242** [comment]
Since in [`v1.30.0`](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.30.0) all native clusters recipes was reworked, they could be turned into Dirty Ore and then processed.

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/e07618cd-81e9-45c4-9b62-37712ee59ac7)
![javaw_R8QwlsAlt7](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/c45c04e4-ea41-4fcb-aa43-47698ed706a4)

But I can get 3d  output. Will investigate further.
