### ISSUE TITLE
Nether Gold Ore Not Processable in Actually Additions Crusher

### ISSUE THREAD

**Issue by sonicjames10** [Krutoy242/Enigmatica2Expert-Extended#332]
I'm not sure if this is intended or not, but I noticed that Nether Gold Ore can't be processed in Actually Addition's Crusher.

![2024-02-12_22 31 18](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/49282601/a06e172e-8fce-4db8-9e2a-9454d75b9a58)

It seems like other nether ores can be processed in it, so I wasn't sure why this one couldn't.

**Comment by Krutoy242** [comment]
Thanks for the report! I will investigate it.
