### ISSUE TITLE
The world won't load

### ISSUE THREAD

**Issue by hopethisdoesntlastlonger** [Krutoy242/Enigmatica2Expert-Extended#335]
After updating this happened and world won't load no matter how long i wait
Version: 1.30.2
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/69762672/9890f627-2053-4dbe-91ac-76a46fff4ada)

**Comment by Krutoy242** [comment]
I recommend to read [patch notes](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases).

Your problem seems like from updating `v1.26.0` or earlier versions and was described [here](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.29.1):

> ### ⚠️Important note:
> 
> If you're updating the modpack from version `v1.26.0` to a newer one, you may need to delete the file `saves/[world name]/data/biometweaker_asmtweakdata.dat` to prevent your world from freezing and becoming unresponsive after the update.

**Comment by hopethisdoesntlastlonger** [comment]
Worked for me, thanks
