### ISSUE TITLE
Hirschgeist invulnerable during night when summoned

### ISSUE THREAD

**Issue by InsertSalt** [Krutoy242/Enigmatica2Expert-Extended#336]
As per title Hirschgeist invulnerable during both day (as intended) and night when summoned with the hand of fate

**Comment by Krutoy242** [comment]
This is true and sometimes you cant damage it even at night.
But, you can still kill it with AOE damage weapons, like Harming potions:


https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/0fde4976-2cd1-4324-935c-2d70f765640b
