### ISSUE TITLE
Refining Infusion enchant no longer has 100% chance to create clusters

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#337]
The refining infusion enchantment seems to have gone back to the original thaumcraft numbers with a 75% chance at level 4 to convert ore to a single cluster and has no chance to generate extra.

This change started with the 1.31.0 version.

**Comment by Krutoy242** [comment]
Yeah, seems like its somehow related to mixins and updates of some mods. Thanks for report, I will try to investigate.

**Comment by stiffchub** [comment]
This may have started happening in 1.30.0. I recall not getting clusters sometime before the update to 1.31.0
