### ISSUE TITLE
Animated Textures Not Animating At All With Optifine's Smart Animations Enabled

### ISSUE THREAD

**Issue by philswiftimp** [Krutoy242/Enigmatica2Expert-Extended#338]
## Description

When I install the modpack with nothing else added or changed, and choose to install Optifine from Mod Director, I've noticed for a while that animated textures (such as fire or smeltery liquids) do not animate whatsoever.

Turning off Smart Animations (enabled by default if you install Optifine) restores the animations. I'm not sure if this is something fixable, but I'm assuming it's because Optifine conflicts with other performance mods that edit texture animations similarly.

**To Reproduce**

1. Go to Optifine's Performance Settings
2. Click on Smart Animations
3. Look at Smeltery Textures, they do not animate.

**Modpack version** `v1.32.1`

**`debug.log` or Crash report**

[debug.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14488599/debug.zip)

**Comment by Krutoy242** [comment]
Yes, this is known incompatibility between Optifine and CensoredASM. See more information here: https://github.com/LoliKingdom/LoliASM/issues/130

**Comment by Krutoy242** [comment]
I think i will left this option enabled, because its give huge performance boost. Maybe i will point out somewhere that later.
