### ISSUE TITLE
Better animals plus spawns too many freshwater eels

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#34]
![2022-03-26_00 58 36](https://user-images.githubusercontent.com/78452357/160216438-a0b7417d-c28f-466a-ba73-a732dcd84607.png)

**To Reproduce**
This probably has something to do with my distance to the river, i can provide the world for debugging if needed.

**Modpack version** `v0.52.0`

**Comment by Krutoy242** [comment]
Thank you for the report! Would fix that next release.
