### ISSUE TITLE
Crash: Fighting gaia spirit II

### ISSUE THREAD

**Issue by JustaRandom** [Krutoy242/Enigmatica2Expert-Extended#344]
When Fighting the second gaia spirit at the last phase just after the mob spawning end.
The server just crash and the server restart.
Did try the fight 2 times and same problem.

Ver: 1.32.1

[---- Minecraft Crash Report ----.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/14625327/----.Minecraft.Crash.Report.----.txt)

**Comment by Krutoy242** [comment]
Thank you for the report! I will investigate the issue.

**Comment by Krutoy242** [comment]
I tried to reproduce this issue but cant. Whole Gaia II fight comes normal, succesfully killed it and it had drop.

I found that your crash happens [there](https://github.com/VazkiiMods/Botania/blob/1.20.x/Xplat/src/main/java/vazkii/botania/common/entity/GaiaGuardianEntity.java#L847) in the code of generating invisible Land Mines. For some reason, Botania cant find any players around.

But when I fought Gaia II, there was this mines and everything was ok.

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/de4a069c-4fd2-40cd-b8b8-d19d6885eeb9)

Does this crash happened on server?

**Comment by JustaRandom** [comment]
yes the crash did happened in a server.
I did not try the fight on the 1.35 so maybe it is fixed. Will try and come back with the result.
