### ISSUE TITLE
Fail Install

### ISSUE THREAD

**Issue by Jojo6140** [Krutoy242/Enigmatica2Expert-Extended#346]
Unable to install the modpack.
 Try it on two different computers via the curse platform or via the zip (import) or via Prism
. It says "Mod File Integrity Check Failed". With Prism it indicates the 4 mods in problem
 -TMEL
 -Netherending Ores
 -MCTsmelteryIo
 -HarderBranchMining

 Not practical because we don't see if you release a new version of your modpack

**Comment by Krutoy242** [comment]
This is happens because owners of this 4 mods forbid to download them by 3d party launcher. This could be fixed in prism by pressing `Open Missing` button:

![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/b2fb7bd5-6e9b-4e40-9e1b-bc72396039d4)

**Comment by Jojo6140** [comment]
Thanks for the info.
 I understood and managed to make it work but I think it's a shame that it doesn't do it directly via curse because problematic for many people who won't bother trying to go through prism
. otherwise very good modpack.
 When will there be an expert modpack in 1.20?

**Comment by Krutoy242** [comment]
> it doesn't do it directly via curse

It does actually. If you using CurseForge launcher, it downloading all the mods without additional clicks.

> expert modpack in 1.20

1.12.2 is best version for expert packs already. Why you need 1.20?
