### ISSUE TITLE
Wheat seeds drops

### ISSUE THREAD

**Issue by jennifer-ross** [Krutoy242/Enigmatica2Expert-Extended#348]
## Description
When I plant two or more wheat seeds side by side they just fall out. The farm doesn't work either. But from the harvest craft mod the seeds are planted normally.

I didn't get any errors in the console

**Modpack version** `v1.35`

https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/38167698/b629ad9c-941c-4a65-8fe0-f35e77c69b47

**Comment by Krutoy242** [comment]
Can you place lantern near them? It feels like they just need light.

**Comment by jennifer-ross** [comment]
It's working. Sorry, my mistake. It was my night vision that confused me. Thank you
