### ISSUE TITLE
IC2 machine cannot work after Construct's Armory with Horologium

### ISSUE THREAD

**Issue by Thjingdian** [Krutoy242/Enigmatica2Expert-Extended#349]
When Construct's Armory with Horologium is triggered,IC2 machine  no longer works

**Comment by Krutoy242** [comment]
Isnt this is the point, to disable all ticking entities around?

**Comment by Thjingdian** [comment]
> Isnt this is the point, to disable all ticking entities around?
 Horologium just work 5 seconds. After 5 seconds, ic2 machine remains permanently frozen unless removed and repositioned.

**Comment by Krutoy242** [comment]
Please, create a new issue in Tinker's Evolution mod issue tracker, because attunement is handled by that mod https://github.com/phantamanta44/tinkers-evolution/issues

Also, dont forget to write steps to reproduce in new issue.

**Comment by Krutoy242** [comment]
I don't know how to reproduce the issue since cant remember how to make such armor and attune it correctly.
Thanks for the report anyway, but since this is issue of another mod, i will close current issue.
