### ISSUE TITLE
Integrated dynamics squeezer not processing aluminum

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#35]
## Description

Both the normal squeezer and mechanical squeezer are not accepting aluminum, but they are accepting all other thermal ores, and cobalt and ardite(They are also not accepting any nuclearcraft ores but this is consistent so it seems intended)

![Screenshot 2022-03-26 173015](https://user-images.githubusercontent.com/78452357/160248797-37133b69-71ad-4937-90fe-2143d5803fcd.png)

**Modpack version** `v0.52.0`

**Comment by Krutoy242** [comment]
Thank you for report! I will check this out.
