### ISSUE TITLE
Modded Survival World Crashing ( java.lang.NullPointerException: Exception in server tick loop)

### ISSUE THREAD

**Issue by kayfarik2005** [Krutoy242/Enigmatica2Expert-Extended#353]
Hello guys, I encountered this problem, after restarting Minecraft with any world there was this crash report https://mclo.gs/VAX1NTk

**Comment by Krutoy242** [comment]
What modpack version?

**Comment by Krutoy242** [comment]
Update modpack to [`v1.37.1`](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v1.37.1)

**Comment by Krutoy242** [comment]
Ok, we probably found solution - remove file `config\sledgehammer.conf`
