### ISSUE TITLE
Crash: `RuntimeException: Error processing net.minecraft.potion.PotionEffect - no holder field declared (is the code somehow obfuscated?)`

### ISSUE THREAD

**Issue by Octelly** [Krutoy242/Enigmatica2Expert-Extended#355]
## Description

Modpack doesn't start.

**To Reproduce**

1. Try to launch the pack

**Modpack version** `v1.37.1`

**`debug.log` or Crash report**

[Here's a link](https://mclo.gs/XrVSOv3), but this crash was already mentioned in this repo's issues previously: [Krutoy's comment in #269](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/269#issuecomment-1751933200)

As [ZZZank pointed out](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/269#issuecomment-1751942971), the problem was Universal Tweaks' mixin.

Disabling ``[1] Incurable Potions Toggle`` in ``Universal Tweaks - Tweaks.cfg`` fixed the problem.

**Comment by Krutoy242** [comment]
Thanks for the report and a advice to fix it! I will fix it next patch.
