### ISSUE TITLE
Entering the world will lead to collapse

### ISSUE THREAD

**Issue by ls314** [Krutoy242/Enigmatica2Expert-Extended#357]
Hello, I will prompt a crash when entering or creating a new world, which may be caused by adding other mods. However, when I delete these mods and restart the new world, it will still crash. The current version number is 1.37.2, and this issue will not occur under version 1.36.1.
![捕获](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137019119/dd3bf53c-b412-4304-a0e7-e3c645742fe4)
![屏幕截图 2024-04-17 110633](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/137019119/dd2ce149-d02d-4bdf-9900-564d805ea699)
[crash-2024-04-17_10.45.18-server.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/15005038/crash-2024-04-17_10.45.18-server.txt)

**Comment by Krutoy242** [comment]
Thank you for the report!
This is related to previous issue https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/353
I though I fixed this crash but actually dont. For temporary fix remove file `config/sledgehammer.conf`

**Comment by ls314** [comment]
> 感谢您的报告！这与之前的问题#353有关，我虽然修复了这个崩溃，但实际上没有。对于临时修复，请删除文件`config/sledgehammer.conf`

Thank you, you are an amazing modpack producer. :)
