### ISSUE TITLE
In Enigmatica2Expert-Extended v1.37.3, block placement feels odd.

### ISSUE THREAD

**Issue by mc123mc** [Krutoy242/Enigmatica2Expert-Extended#358]
video=https://pixeldrain.com/u/hEph97LE 
Placing blocks feels odd and unfamiliar. I want to remove this mod, but I'm not sure what it's called
"I want to revert to the original behavior of block placement."

**Comment by Krutoy242** [comment]
To disable this feature go `Mod Options` ➜ `Universal Tweaks` ➜ `Tweaks` ➜ `Blocks` ➜ `Better Placement` ➜ `Better Placement Toggle` set `false`.

**Comment by mc123mc** [comment]
Is Better Placement a mod? This mod hasn't been installed
[Uploading 文本(2024-04-23 192824).txt…]()
