### ISSUE TITLE
Graphite Block is not craftable in alloy smelter 

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#36]
### Not sure if its a bug with HEI or the recipe not working.

![Screenshot 2022-03-28 232551](https://user-images.githubusercontent.com/78452357/160490904-adbf83c9-30b7-488a-a3ab-d9f51aed7e34.png)

### I have tried it in both alloy and furnace mod, and also tried chiseled coal and charcoal.   
![Screenshot 2022-03-28 232653](https://user-images.githubusercontent.com/78452357/160490910-efadabaf-326d-4e68-b711-754a5aa76b5f.png)

**Modpack version** `v0.52.0`

**Comment by Krutoy242** [comment]
Thank you for report, I will investigate the issue.
