### ISSUE TITLE
"The 'Random Things' mod's Spectre server is not loading properly."

### ISSUE THREAD

**Issue by mc123mc** [Krutoy242/Enigmatica2Expert-Extended#360]
"The 'Random Things' mod's Spectre server is not loading properly."
https://pixeldrain.com/u/TaW9H6Qz  [.mp4]

**Comment by Krutoy242** [comment]
What modpack version you pay on? There was same issue I already while ago.

**Comment by mc123mc** [comment]
v1.37.3

**Comment by Krutoy242** [comment]
Ok, I will investigate issue further. Please send full log of server - file `debug.log`.

**Comment by mc123mc** [comment]
[Uploading logs.zip…]()

**Comment by mc123mc** [comment]
https://pixeldrain.com/u/dQxidvfT

**Comment by Krutoy242** [comment]
Thanks, I will investigate the issue. This could take several weeks.

**Comment by Krutoy242** [comment]
I cannot reproduce the issue. Can you provide more information?
Like, maybe you have additional mods? Or your configs are changed?

https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/4497f6cb-8d61-4c84-8c00-12833382e178

**Comment by Krutoy242** [comment]
Made issue on UT github https://github.com/ACGaming/UniversalTweaks/issues/460

**Comment by Krutoy242** [comment]
Note:
The temporary fix would be change player game mode to Creative just on one second.
