### ISSUE TITLE
Is there any problem updating the server from v1.37.3 to v1.37.4?

### ISSUE THREAD

**Issue by mc123mc** [Krutoy242/Enigmatica2Expert-Extended#361]
Will updating the server from v1.37.3 to v1.37.4 cause corruption? Do users need to update to v1.37.4? Will the server crash if the save file is switched to v1.37.4?

**Comment by Krutoy242** [comment]
Updates can bring exciting new features, but they also carry the risk of instability, such as crashes, world corruption or loading issues. Despite thorough testing, unexpected problems can arise. If your current version of the modpack is stable and enjoyable, staying with it might be the best choice for uninterrupted gameplay.
