### ISSUE TITLE
RandomThings Spectre "Universal Tweaks - Modifications in Tweaks.cfg file not taking effect"

### ISSUE THREAD

**Issue by mc123mc** [Krutoy242/Enigmatica2Expert-Extended#366]
"Universal Tweaks - Tweaks.cfg" file modification is ineffective or unable to load.

This error message suggests that you're encounte
[Universal Tweaks - Tweaks.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/15285842/Universal.Tweaks.-.Tweaks.zip)
[logs (1).zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/15285843/logs.1.zip)

**Comment by mc123mc** [comment]
"Still unable to properly load Spectre simulation."

**Comment by Krutoy242** [comment]
I dont understand what you talking about. If you are using translator, please use better one such as https://www.deepl.com/translator

**Comment by mc123mc** [comment]
"I'm using GPT for translation, but there are errors in the translation."
"Spectre Latitude still cannot be loaded and cannot be moved."

**Comment by mc123mc** [comment]
1. "Better Placement Toggle" should be changed to `false`.
2. "Block Dispenser Toggle" should be set to `true`.
3. "Auto Jump Replacement" needs to be updated to `true`.
4. The "Creeper Confetti Spawning Chance" entry should either be removed or commented out.
5. "Flaming Arrows" must be switched to `true`.
6. "Max Speed" should be altered to `100.0`.
7. "Max Elytra Speed" requires changing to `300.0`.
8. "Max Vehicle Speed" has to be revised to `100.0`.
9. "No Night Vision Flash" ought to be turned to `false`.
10. "Remove Recipe Book" should be flipped to `false`.

Even after manually applying these changes, it still fails to load Spectre Latitude.

**Comment by Krutoy242** [comment]
When entering Spectre dimension just turn creative game mode for a second `/gamemode 1` and it will be fixed.

**Comment by mc123mc** [comment]
create one-timeloading 
https://pixeldrain.com/u/eX3nwCrR

**Comment by Krutoy242** [comment]
Yes, this is how it works right now. I dont know how to fix it yet. You can also remove Universal Tweaks from the server to fix this issue.
