### ISSUE TITLE
add Scalar for Scala support when using Cleanroom

### ISSUE THREAD

**Issue by ZZZank** [Krutoy242/Enigmatica2Expert-Extended#367]
Cleanroom, unlike Forge, does not includes Scala support by default. This breaks OpenComputer(and possibly other mods) when using Cleanroom. 

So I suggest including Scalar by default, just like Fugue.
Link: https://www.curseforge.com/minecraft/mc-mods/scalar

This should not break anything since Scalar should not load under Forge. 

Note that the version of Scalar should be 2.x.x(e.g. 2.11.1), NOT 3.x.x. This is because Scalar 3.x is providing Scala3, which is not compatable with Scala2 that Forge mods are using.

**Comment by Krutoy242** [comment]
Im unable to add Scalar into Java 8 instance since unlike Fugue, Scalar causing crash https://mclo.gs/syl99cJ
```ruby
[main/FATAL] [Scalar]: Not running on Cleanroom! Cause by {}
java.lang.ClassNotFoundException: com.cleanroommc.loader.LanguageAdapterRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_402]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_402]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_402]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_402]
	at com.cleanroommc.scalar.ScalarLoadingPlugin.<init>(ScalarLoadingPlugin.java:17) [scalar-1.12.2-2.11.1.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_402]
```

**Comment by ZZZank** [comment]
My bad. It's not crashing on my side because I was using my own fork when testing. 

I've uploaded my changes to Github, and there's a prebuilt jar avaliable in the [Actions page](https://github.com/ZZZank/Scalar/actions/runs/9063312771), the `scalar-1.12.2-2.11.1.jar` in `artifact`.zip is the mod jar. 

Give it a try if possible?

**Comment by ZZZank** [comment]
my [PR to Scalar](https://github.com/CleanroomMC/Scalar/pull/2) has been merged, better wait for a new version of Scalar instead of using my fork :)

**Comment by kappa-maintainer** [comment]
> Im unable to add Scalar into Java 8 instance since unlike Fugue, Scalar causing crash https://mclo.gs/syl99cJ
> 
> ```ruby
> [main/FATAL] [Scalar]: Not running on Cleanroom! Cause by {}
> java.lang.ClassNotFoundException: com.cleanroommc.loader.LanguageAdapterRegistry
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_402]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_402]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_402]
> 	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_402]
> 	at com.cleanroommc.scalar.ScalarLoadingPlugin.<init>(ScalarLoadingPlugin.java:17) [scalar-1.12.2-2.11.1.jar:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_402]
> ```

I forgot to reupload the Forge-safe version

**Comment by kappa-maintainer** [comment]
Are you using the build from CurseForge? Forge should safely ignore that jar
If you are not aware of or have forgotten: Scalar doesn't change version, new jars will be uploaded to same release to match library version

**Comment by Krutoy242** [comment]
I will test new CurseForge jar later.

**Comment by Krutoy242** [comment]
Ok, just tested 2.x file on CurseForge and Java 8.  Working fine I believe.
Now we need to wait until Bansoukou will finally fixed so E2E-E could officially be distributed as Java22 modpack 😅
