### ISSUE TITLE
Little Tiles Harvest Level Bug

### ISSUE THREAD

**Issue by mayoamn203** [Krutoy242/Enigmatica2Expert-Extended#368]
## Description

The tools of Little Tiles don't have sufficient harvest level to chip away at Greatwood Log (3) or Charred Stone. (5)
This issue didn't manifest in creative mode as i assume there is some execption built in.
*edit Tools worked in creative mode for the Greatwood log but not charred cobblestone (5)

1. Left click on Greatwood Log with Little Hammer
2. Not able to carve

![2024-05-20_01 09 23](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/170280069/a417312a-d585-4278-b9ea-adec4d9541c1)

**Modpack version** `v1.37.6`

**Comment by Krutoy242** [comment]
This is default "Protection" from Little Tiles mod to forbid players using Little Chisel and Hammer as mining tools.
Without this protection, survival players could skip all mining levels and mine every single Ore - instantly, silk touching.

If you have ideas how i could control ore mining and same time allow changing blocks with high mining level - i'm all ears!
