### ISSUE TITLE
Crash: `java.lang.NullPointerException`  When using infinity furnace connected to rf power source

### ISSUE THREAD

**Issue by Fatcow007** [Krutoy242/Enigmatica2Expert-Extended#369]
## Description

Infinity furnace connected to RF power will crash.
Crashed world will keep crashing on startup

**To Reproduce**

Place infinity furnace
Place RTG fuel source (from nuclearcraft) next to furnace
Try smelting any recipe in infinity furnace

Modpack version 1.37.5

Crash log: https://pastebin.com/2DWa6him

**`debug.log` or Crash report**
[debug.zip](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/15383632/debug.zip)

**Comment by Krutoy242** [comment]
Thank you for the report! I will investigate the issue.

For now, go to file `config/forge.cfg` and set `B:removeErroringTileEntities=true`. This would make your world able to load.

**Comment by Krutoy242** [comment]
Should be fixed since `v1.38.0`

**Comment by Krutoy242** [comment]
Ok, seems like the fix actually crashing server https://github.com/XHL315/IC2-No/issues/1

**Comment by Krutoy242** [comment]
@srki_2K suggested this. Im gonna try it.

> Change this file `mixin.ic2no.mod.json` to:
```json
{
  "package": "superhelo.ic2no.mixins",
  "minVersion": "0.8",
  "refmap": "mixins.ic2no.refmap.json",
  "mixins": [
    "MixinEnergyRender",
    "MixinTileEntityAssembly"
  ],
  "client": [
     "MixinEnergySlot"
  ]
}
```
