### ISSUE TITLE
Molted diamond HEI recipe

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#37]
## Description
HEI shows that molten diamond is craftable with normal diamonds, but its only accepting rat diamonds(is this intended?). 
![Screenshot 2022-03-29 000124](https://user-images.githubusercontent.com/78452357/160495318-7e101e94-6df6-4760-b3bf-41ca18c8f212.png)

**Modpack version** `v0.52.0`

**Comment by Krutoy242** [comment]
No, only rat diamonds should me valid. 
I could fix this on next release I think.

**Comment by Krutoy242** [comment]
> is the Melting Crucible meant as an alternative?
Yes, this is earlier machine before TE crucible.

> remove the oredict value gemDiamondRat form the normal diamond
No no, if i would remove it, lot of other recipes stop taking normal diamond as ingredient.
