### ISSUE TITLE
Long pressing the right mouse button can only trigger Right Click once

### ISSUE THREAD

**Issue by ZZZank** [Krutoy242/Enigmatica2Expert-Extended#370]
## Description

The title should be clear enough I guess.

**To Reproduce**

Just long press the Right button of your mouse (or any device rhat can produce a Right Click, it doesn't matter), and you will find that Right Click is only triggered once. This becomes very apparent when using Sieves from Ex Nihilo. 

**Modpack version** `v1.37.6`

This might be a recent version exclusive bug, because I wasn't experiencing this when playing on v1.32.0

**Comment by TabakaSIM** [comment]
Universal tweaks config ->  tweaks -> blocks -> better placement -> force new location -> Set to `False`

@Krutoy242 pls change it to be `false` by default

**Comment by Krutoy242** [comment]
I was [already suggest feature request](https://github.com/ACGaming/UniversalTweaks/issues/416#issuecomment-2047325481), but seems like it was missed since last UT version wasn't have this fix.

So, I guess i will create new issue on UT issue tracker.

**Comment by Krutoy242** [comment]
Need to wait till this change will be released https://github.com/ACGaming/UniversalTweaks/issues/473

**Comment by Krutoy242** [comment]
Fixed in next modpack version by updating Universal Tweaks mod.
