### ISSUE TITLE
IC2 Nuclear Reactor Chamber incompatibility with other cables

### ISSUE THREAD

**Issue by trubetscoin** [Krutoy242/Enigmatica2Expert-Extended#377]
## Description

Industrial craft 2 nuclear reactor chamber doesn't connect to Mekanism universal cable at all. It does connect to nuclear reactor itself, but not to the chamber, making you either loose one column of reactor space or use IC2 fibre glass cable that would be connected to IC2 eu storage as an intermediary step. The same applies to the Ender IO Energy Conduit, but it doesn't connect to even nuclear reactor and the chamber as well. Would be nice to have such compatibility.

**To Reproduce**

1. Create nuclear reactor (with all 6 sides optional) covered with nuclear reactor chamber
2. Place Mekanism cable to reactor chamber

**Modpack version** `v1.38.1`

**Comment by Krutoy242** [comment]
Yes, i cant replicate this bug too.
I dont know how to fix that, so I will just add questbook note that reactors can not be used with cables.

Main solution would be to use Mek Cubes. this setup works fine:
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/936618/9b61e0df-3db3-413d-a6de-05e984be6e5b)

**Comment by trubetscoin** [comment]
Thank you for the fast reply and good luck!
