### ISSUE TITLE
Mob can spawn with a glitched block during gaia guardian 2 fight.

### ISSUE THREAD

**Issue by Fatcow007** [Krutoy242/Enigmatica2Expert-Extended#378]
## Description

Mob spawns with a glitched block (purple texture) in hand, which can be dropped as an item.
Hovering over the picked up item in inventory will crash the game, causing "java.lang.NullPointerException: Rendering screen"

Item shows itself as "air" block when viewed through external tool (NBTExplorer).
Also, item disappears on game reload.

**To Reproduce**

1. Start the fight with gaia guardian 2, progress until mob spawning phase.
    - Unsure if only mobs spawned from gaia guardian 2 can produce this bug, but it is how I encountered & reproduced
2. Mob spawns with broken texture (purple checker) block in hand. Kill and obtain the block.
3. Hover over the block and crash.
3-a. Restarting world will remove the glitched block from inventory.

Wither skeleton spawned with glitched block.
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/42465783/e3f90682-991e-4ed6-a30e-62839cda11ea)
Item viewed from NBTExplorer
![image](https://github.com/Krutoy242/Enigmatica2Expert-Extended/assets/42465783/0446928a-bc27-4287-80c6-0169529f22a8)

**Modpack version** `found: v1.37.6 `also exists in: v1.38.1`

**`debug.log` or Crash report**
https://mclo.gs/D9GkN2j

**Comment by Krutoy242** [comment]
This is probably same issue is [here](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/363), but thank you for the investigation! I think i could fix the issue next patch version.

For now, you can try to remove file [config/malekremoveregistries.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/tree/master/config/malekremoveregistries.txt) and this may fix the issue.

**Comment by Krutoy242** [comment]
UPD: Try to remove only line `botania:elementiumsword` from that file and report if this fix the issue. You will need to restart the server.
