### ISSUE TITLE
Alloy Smelter broken omnivoir recipe

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#38]
![Screenshot 2022-04-06 003006](https://user-images.githubusercontent.com/78452357/161861883-eb4ba464-8530-4039-9961-241f879254e7.png)
![Screenshot 2022-04-06 003042](https://user-images.githubusercontent.com/78452357/161861990-19a55a8e-5795-4c59-ad73-6f5978f2e1e8.png)

**Comment by Krutoy242** [comment]
Thank you for report.

Seems like [Ender Tweaker](https://www.curseforge.com/minecraft/mc-mods/endertweaker) mod not working anymore.

Would be fixed next release.
