### ISSUE TITLE
Mod Suggestion: Ambient Sounds 3

### ISSUE THREAD

**Issue by evanbones** [Krutoy242/Enigmatica2Expert-Extended#384]
Now that DynamicSurroundings is gone (love it, but way too many issues), Ambient Sounds is a really nice and simple alternative for adding world ambience. Should have little to no performance overhead from my testing.

https://www.curseforge.com/minecraft/mc-mods/ambientsounds/files/3516274

**Comment by Hlwyefeng** [comment]
I have tested this mod and it actually has a significant impact on performance, especially in the presence of Sound Physics

**Comment by Krutoy242** [comment]
Thanks for the suggestion, I will take a look on this mod later!
Want to warn, that DynamicSurroundings is not part of E2EE and only listed in "recommended" mods list.

**Comment by evanbones** [comment]
Having played with AmbientSounds more, I have been noticing significantly more stutters. Removed for now, wouldn't totally recommend unless for those who absolutely need the effect

**Comment by Krutoy242** [comment]
Thank you for the test! Now I will know that we don't want to add it =)
