### ISSUE TITLE
[Sugestion] If possible integrate FTB chunk loading and extra utilities grid power

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#39]
I for one don't like the fact that ftb chunk loading is disabled, for me its tedious to place xu chunk loaders all over my base and keep track of them.

So i think a great trade off would be if the amount of grid power the player has would determine the amount of chunks he can keep loaded. For example: 
10Gp = 15FTB chunks
20Gp = 25FTB chunks
30Gp = 35FTB chunks
40Gp = 45FTB chunks
50Gp = 50FTB chunks
60Gp = 55FTB chunks

Its possible to make ftb ranks with varying amounts of chunk loading [tikets](https://forum.feed-the-beast.com/threads/ftb-utilities-how-to-increase-allowed-claimed-chunks.220348/)

But i don't know if zen script can interact with thous ranks, and if it can track the grid power of the player

**Comment by Krutoy242** [comment]
It's actually interesting and original idea!
I would take a look on this ranking system. I have access to FTB but not sure about GP.

Anyway, you can use IC2 chunk loader - it's even have similar GUI as FTB.

**Comment by Srdjan-V** [comment]
I will not make any promises but i will try to make such a mod.
The only problem is that i don't have any knowledge about forge, but do have decent knowledge about java.

**Comment by Krutoy242** [comment]
Such mod would be nice for sure.

**Comment by Srdjan-V** [comment]
I give up, i have tried to set up the dependency's for the project but every time it crashes the dev env. Apparently it has something to do with the version of gradleForge, i have tried a older version but thous didn't detect the dependency's. I have spent about 12h trying to figure this out but i have no idea what im doing wrong.

**Comment by Krutoy242** [comment]
I also spent some time studying FBT Utilities.

I found no direct way to access FTB Utilities through CraftTweaker.
I usually use [these](https://github.com/BrisingrAerowing/CraftTweakerUtils/wiki) [three](https://github.com/TCreopargh/CraftTweakerIntegration/wiki/Vanilla-Expansion) [utilities](https://github.com/friendlyhj/ZenUtils/wiki), but there doesn't seem to be any support there.

The only option left is to manage ranks via commands. But **I couldn't find any such commands**!

Googling I found only [this list](https://help.ftb.team/help/en-gb/8-frequently-asked-questions/20-is-there-a-full-list-of-commands), and it doesn't say how to give ranks to players.

------------

**I need help** - what commands give ranks?

I think it's best to tie the number of chunks not to GP, since we already have a chunk loader running from GP.   
My idea is to tie it to the quest book - when a player completely finishes some chapter, he gets a Trophy, and also a command that raises his rank by 1, giving more chunks to loadout.

--------------

And anyway, I will say that I don't like the idea of permanent chunk loading. If I could do that, I'd rather only load chunks for a player when he's online.

**Comment by Srdjan-V** [comment]
> I give up, i have tried to set up the dependency's for the project but every time it crashes the dev env. Apparently it has something to do with the version of gradleForge, i have tried a older version but thous didn't detect the dependency's. I have spent about 12h trying to figure this out but i have no idea what im doing wrong.

So i did manege to setup a dev env, but im totally lost with EU2.

---
> I found no direct way to access FTB Utilities through CraftTweaker. I usually use [these](https://github.com/BrisingrAerowing/CraftTweakerUtils/wiki) [three](https://github.com/TCreopargh/CraftTweakerIntegration/wiki/Vanilla-Expansion) [utilities](https://github.com/friendlyhj/ZenUtils/wiki), but there doesn't seem to be any support there.

As for ftb i did saw that they have some [integration](https://github.com/FTBTeam/FTB-Utilities/tree/master/src/main/java/com/feed_the_beast/ftbutilities/integration), suggesting that there are apis for that. I will see if i can ad suport for crafttweaker, since it already has for KubeJS.

---
> **I need help** - what commands give ranks?
>Googling I found only [this list](https://help.ftb.team/help/en-gb/8-frequently-asked-questions/20-is-there-a-full-list-of-commands), and it doesn't say how to give ranks to players.

I can see these commands exit in the [source code](https://github.com/FTBTeam/FTB-Utilities/tree/master/src/main/java/com/feed_the_beast/ftbutilities/command/ranks), and they are not listed on the ftb site, but i have not tried them ingame.
(i thinks its /ranks judging by the last commit)
![image](https://user-images.githubusercontent.com/78452357/162755645-8efba66b-4667-4d5a-ba10-c00852def3dc.png)

---
> I think it's best to tie the number of chunks not to GP, since we already have a chunk loader running from GP. My idea is to tie it to the quest book - when a player completely finishes some chapter, he gets a Trophy, and also a command that raises his rank by 1, giving more chunks to loadout.

This is sounds good.

---
>And anyway, I will say that I don't like the idea of permanent chunk loading. If I could do that, I'd rather only load chunks for a player when he's online.

Yes i will see if i can add that as a config option, but as i have said before i have no experience making mods.

**Comment by Krutoy242** [comment]
Just tried to pla with `/ranks add` and got game crash. I will still look at this through.

Since adding new mechanics to quest book taking long time, i will not introduce this feature in nearest release.

**Comment by Srdjan-V** [comment]
I have found the Documentation for the [comands](https://web.archive.org/web/20201030075459/https://faq.ftb.world/books/ftb-utilities/page/ranks) (its on the wayback machine for some reason)

And it seems that its possible to disable chunk loading if the player in offline but im not sure if it works with 1.12.2
![image](https://user-images.githubusercontent.com/78452357/162772281-d21ae042-43cb-4b48-aa9e-d0ad890dd7d7.png)

**Comment by Krutoy242** [comment]
It exists, but is it actually work? Maybe its not implemented feature.

Also, how to see all permissions list?

**Comment by Srdjan-V** [comment]
>It exists, but is it actually work? Maybe its not implemented feature.

Not sure it seems implemented, I will try to test it

> Also, how to see all permissions list?

Pressing TAB after the rank should autocomplete it, but i will try to find it in the source

**Comment by Srdjan-V** [comment]
>I will try to find it in the source

[I think that's all of them](https://github.com/FTBTeam/FTB-Utilities/blob/98aa2541886d833c0a024d96164866e7cf6a1289/src/main/java/com/feed_the_beast/ftbutilities/FTBUtilitiesPermissions.java#L40-L119)

**Comment by Srdjan-V** [comment]
> This would help me a lot!

I can confirm that it is working
![image](https://user-images.githubusercontent.com/78452357/162790497-2291d0a9-073c-4cc1-b6b7-6e903cdc833c.png)
 
Using a repeating command bock with `/say loaded` it unloaded while 

But it did not the first time i tried it, since the first time i only gave the `ftbutilities.chunkloader.load_offline: false` to the Player rank, and i was technically a admin
![image](https://user-images.githubusercontent.com/78452357/162790796-03d8b773-0396-4200-8d72-e97a4e0bb794.png)

**Comment by Krutoy242** [comment]
> you want me to make a schematic for ti?

Yes, but im still in process of fixing this issue. Cant find a block that intenfere structure to recognize.

**Comment by Krutoy242** [comment]
Ok, seems like it would takes more time to introduce this "level" feature in modpack. Maybe month or more.

I want to make "Confluxes" - special quests that merging all "branches" of questbook together, depending on tier.
Like, if you finish all `Tier I` quests, you got `Conflux I` reward, that contains more FTB chunks.
