### ISSUE TITLE
Add LostUser's Readme to OpenComputers' manual

### ISSUE THREAD

**Issue by ZZZank** [Krutoy242/Enigmatica2Expert-Extended#391]
I noticed that OpenComputers' manual are written in Markdown format, and docs can be added by external sources like ExtraCells2(see https://github.com/ExtraCells/ExtraCells2/tree/rv6-1.12/src/main/resources/assets/extracells/doc), so it should be possible and easy to add LostUser's README.md to OpenComputers' manual.

By doing so, I can view the docs without the needs of opening a browser page and switching back and forth, definitely will be a smoother gameplay

**Comment by Krutoy242** [comment]
Very nice idea! Thank you for noticing me this. I will think to implement it.

**Comment by Krutoy242** [comment]
I tried to research where i could find syntax rules for those doc files. If you know, tell me.
Also, this would be hard to implement if OC not support things like tables.

**Comment by ZZZank** [comment]
OC doc parsing is defined in this package: [li.cil.oc.client.renderer.markdown.segment](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.12/src/main/scala/li/cil/oc/client/renderer/markdown/segment), and you can find all supported markdown syntaxs in [its sub-package](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.12/src/main/scala/li/cil/oc/client/renderer/markdown/segment).

There are two markup formats for OC doc, defined [here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/client/renderer/markdown/MarkupFormat.scala), but both of them are for Markdown.

A bad news is that, yes, it does not support table, only basic syntaxes can be parsed, some of them are defined [here](https://github.com/MightyPirates/OpenComputers/blob/5617463edea215fef12626d10cd52740d5cbfa47/src/main/scala/li/cil/oc/client/renderer/markdown/Document.scala#L155-L163).

---

Another bad news is that it will be hard support table by ourselves, because there's no commits related to table support for OC, not even after Markdown doc is split into [MarkdownManual](https://github.com/MightyPirates/MarkdownManual) by some other authors. We have no reference implementation or workaround for it whatsoever

**Comment by Krutoy242** [comment]
Theoretically, i could "disassemble" table to bullet points, but this would require me to write my own "unparser". And i will need to do the same for many other unsupported formattings.
