### ISSUE TITLE
The Kikoku cannot double the enchantment

### ISSUE THREAD

**Issue by wangxiaoyang776** [Krutoy242/Enigmatica2Expert-Extended#396]
As the title says, I can't enchant anything other than the Kikoku enchantment sword in survival mode, and when I change to creative mode, I can enchant other types of enchantments, but it still can't be doubled properly

**Comment by wangxiaoyang776** [comment]
Oh, and there's another problem, the Gelid Flux Capacitor Amulet from the Redstone Repository Revolved, it shows 10 million IO in the game, but it doesn't reach this data at all in actual use, although I don't think most people will choose to use it, but it's really a mistake.

**Comment by Krutoy242** [comment]
Yeah, it feels like `Gelid Flux Capacitor Amulet` not working at all, but this is an another issue.

**Comment by Krutoy242** [comment]
Kikoku issue confirmed, not working as intended.

**Comment by jchung01** [comment]
XU2-Patcher's default config disables the enchant doubling functionality (for whatever reason). The effect can be re-enabled by setting `opEffectsFix=false` in `XU2-Patcher.cfg`.

**Comment by Krutoy242** [comment]
> XU2-Patcher's default config disables the enchant doubling functionality (for whatever reason). The effect can be re-enabled by setting `opEffectsFix=false` in `XU2-Patcher.cfg`.

Thank you! I didnt knew that!
