### ISSUE TITLE
Bug: cant create pahoehoe lava

### ISSUE THREAD

**Issue by Xplodin** [Krutoy242/Enigmatica2Expert-Extended#398]
## Description

title
**To Reproduce**
1. put liquid heat exchanger down and fill with heat conductor and lava
3. put a stirling gen on the heat port
4. only get 1mb of pahoehoe lava and it stops

https://github.com/user-attachments/assets/d81c9217-1090-42fd-ba5b-f6f5978b816f

**Modpack version** `v1.41.0`

**`debug.log` or Crash report**

**Comment by Krutoy242** [comment]
You forgot point 4
![image](https://github.com/user-attachments/assets/650ee946-4b6f-4c06-8b0e-aa8a0d27f8b1)

**Comment by Xplodin** [comment]
That was it, sorry for that! I honestly thought IC2 machines had some internal buffer
