### ISSUE TITLE
Crash: `ExecutionException:ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by leanlopes** [Krutoy242/Enigmatica2Expert-Extended#399]
When I try to open the modpack, before even load, it already crash and say there's no mods know causing the issue

**Modpack version** `v1.41.0`

Crash report: https://mclo.gs/PAvzYBe

![Captura de tela 2024-08-01 065437](https://github.com/user-attachments/assets/cc559f95-6cf4-44f6-b24d-aa8baa79036a)

**Comment by Krutoy242** [comment]
Try to launch again.

**Comment by Krutoy242** [comment]
So, I assume issue is fixed by launching modpack again?
