### ISSUE TITLE
Blood Magic meteor ritual unable to form

### ISSUE THREAD

**Issue by ZZZank** [Krutoy242/Enigmatica2Expert-Extended#400]
I try to use `Ritual Diviner(Dusk)` to construct a meteor ritual, but it always fails because it's unable to place all Ritual Stones.

More precisely, every attempt of constructing a meteor ritual will stop at the last 8 `Ritual Stones`, and they are all `Ritual Stone of Earth`. I also counted all placed ritual stones, and only the number of `Ritual Stone of Earth` does not match descriptions on `Ritual Diviner`.

**To Reproduce**

- get 1 `Ritual Diviner(Dusk)` for meteor ritual, 1 `Master Ritual Stone`, 108 `Ritual Stone`
<img width="468" alt="1" src="https://github.com/user-attachments/assets/212ec7db-89b6-4c5e-a59a-d46fd08ddcbe">

- click `Master Ritual Stone` with `Ritual Diviner(Dusk)` until there's no more particles
- there'll be 8 `Ritual Stone` left
<img width="385" alt="2" src="https://github.com/user-attachments/assets/81247661-d9fc-4218-a497-768d4c1b822a">

The unfinished ritual is still rotationally symmmetric(I counted them), so the screenshot below should be enough for showing the whole unfinished ritual. 
<img width="960" alt="3" src="https://github.com/user-attachments/assets/9514cb61-b3a9-407f-88a6-e93c69ae8def">

**Modpack version** `v1.39.2`

I haven't try the latest version yet, because Blood Magic related things seem to be unchanged according to the changelog. 

**`debug.log` or Crash report**

[debug.log.zip](https://github.com/user-attachments/files/16481058/debug.log.zip)
[latest.log.zip](https://github.com/user-attachments/files/16481059/latest.log.zip)

**Comment by Krutoy242** [comment]
Thanks for the report! I will investigate the issue.

**Comment by Krutoy242** [comment]
Cannot reproduce the issue. Even with runes left, ritual still formed and summoning meteors still possible 
![image](https://github.com/user-attachments/assets/4925c0c3-5452-4ccc-97da-8fb1dc387d4d)

**Comment by ZZZank** [comment]
Then this is very likely to be a typo, because descriptions on `Ritual Diviner` says 108 `Ritual Stone`, but I can activate this ritual when there's only 100 `Ritual Stone` placed by my test results.

(I didn't realize this days ago because the wiki asked me to activate it using `Weak Activation Crystal`, which is wrong. It should be `Awakened Activation Crystal`)
