### ISSUE TITLE
Game not loading on new install

### ISSUE THREAD

**Issue by AndreiTS** [Krutoy242/Enigmatica2Expert-Extended#401]
## Description
Same issue from here:
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/1037

This works:
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/1037#issuecomment-1511710070

**To Reproduce**

Create a new install and try to enter the game.

**Modpack version** `v1.42.0`

[debug-3.log.gz](https://github.com/user-attachments/files/16500740/debug-3.log.gz)

**Comment by Krutoy242** [comment]
This solution may not be related to the issue.
How you define "Game not loading"? Launcher cant load mods? Modpack icon wont be clicked? Window crashed?
There is a lot of stages of game to be unable to start and to help i need to know when.

**Comment by Krutoy242** [comment]
This solution may not be related to the issue.

The actual issue is that there is popup window that asking you if you want to install Optifine. The problem is that window appear behind the launcher window. So you probably just didnt noticed it. Just fold top window and you will see it.

**Comment by AndreiTS** [comment]
> This solution may not be related to the issue.
> 
> The actual issue is that there is popup window that asking you if you want to install Optifine. The problem is that window appear behind the launcher window. So you probably just didnt noticed it. Just fold top window and you will see it.

Yes I remember that window, maybe it was hidden
