### ISSUE TITLE
LittleTiles Warning

### ISSUE THREAD

**Issue by ChristmasZCY** [Krutoy242/Enigmatica2Expert-Extended#403]
## Description
![image](https://github.com/user-attachments/assets/6a88fc48-00fd-49f1-9f6c-52fbf6627cdb)

When I enter E2EE-server, it will warn top-left side.

**Comment by ZZZank** [comment]
The message already told you the reason of this warning(`Optifine`) and how to solve it(`Disable Render Regions`)

**Comment by ChristmasZCY** [comment]
oh，thank you！
