### ISSUE TITLE
Tamed Cockatrice from Ice and Fire sometimes refusing to move

### ISSUE THREAD

**Issue by BuildTheirMan** [Krutoy242/Enigmatica2Expert-Extended#404]
Not sure if this is a already know issue with Ice and Fire, but the Cockatrice sometimes just becomes completly unable to move, I can still interact with him, but it feels like his AI turns off for whatever reason, he cannot be damaged by me directly but cactus by example, still applies.
Unloading the chunk that he is at by moving far away sometimes fixed the issue, but then I had a even weirder problem where he is following me by teleporting but refusing to walk.
Since I never played a modpack with Ice and Fire before, I would like to know if this issue can be reproduced, or is it something wrong with my save file.

I am using the most recent available version of the modpack: v1.42.0

**Comment by Krutoy242** [comment]
Sorry, i have no additional information about this issue.

Possible suggestions:
1. Try to find more info on `Ice And Fire` issue tracker, dont forget to filter 1.12.2: https://github.com/AlexModGuy/Ice_and_Fire/issues
2. Try to replace I&F with ROTN fork, maybe issue is fixed there: https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition

**Comment by BuildTheirMan** [comment]
> Sorry, i have no additional information about this issue.
> 
> Possible suggestions:
> 
> 1. Try to find more info on `Ice And Fire` issue tracker, dont forget to filter 1.12.2: https://github.com/AlexModGuy/Ice_and_Fire/issues
> 2. Try to replace I&F with ROTN fork, maybe issue is fixed there: https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition

Thanks, I will try that
