### ISSUE TITLE
Opening Draconium Chest that has power causes a Ticking player error.

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#406]
Opening a Draconium Chest while it has any amount of power causes a Ticking player error.
Draconium Chests that do not have power will not cause a crash.
Items can be moved in and out of Draconium Chests and will not crash while it has power.
The crash is only caused by the player opening the chest.

Crash occurs on 1.43.
I did not play 1.42 so I do not know if this bug started happening on 1.42 or 1.43.

[crash-2024-08-23_21.51.00-server.txt](https://github.com/user-attachments/files/16734854/crash-2024-08-23_21.51.00-server.txt)

**Comment by Krutoy242** [comment]
Thank you for the report, I will take a look.

**Comment by Krutoy242** [comment]
Issue source was in `Universal Tweaks` mod.
Go to file `config/Universal Tweaks - Mod Integration.cfg` and change option `codechicken lib` => `Packet Leak Fix` to `false`.

I created related issue on UT issue tracker: https://github.com/ACGaming/UniversalTweaks/issues/541
