### ISSUE TITLE
Immersive technology cooling tower recipe possibly broken

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#41]
## Description

I'm not sure if I'm doing it wrong or if its simply bugged

![Screenshot 2022-04-08 010943](https://user-images.githubusercontent.com/78452357/162334050-b882843b-2ef2-4637-9298-60f2d5863b63.png)
![Screenshot 2022-04-08 011058](https://user-images.githubusercontent.com/78452357/162334047-b975f09b-c0af-4bc9-b405-d1230cb7d3da.png)
![Screenshot 2022-04-08 011025](https://user-images.githubusercontent.com/78452357/162334052-9fa5a00e-4fd5-4b77-8843-a91c76e62767.png)
![Screenshot 2022-04-08 011243](https://user-images.githubusercontent.com/78452357/162334207-b7871d4e-93f0-4036-8481-c58398212cb7.png)

**Modpack version** `v0.53.0`

**Comment by Krutoy242** [comment]
Thank you for report! I will investigate this.

**Comment by Srdjan-V** [comment]
its not bugged, hot spring water needs to go to the left and water to the right
![image](https://user-images.githubusercontent.com/78452357/162545103-9453c470-502d-4be8-a00d-b59c7db86131.png)
