### ISSUE TITLE
Tooltip search is disabled by default, making #Tank, #User etc unusable until the player enable it

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Krutoy242/Enigmatica2Expert-Extended#416]
## Description

It is a tip in a quest so i think it is bug, sorry if it isn't.

**To Reproduce**

**Modpack version** `v0.00.0`

**`debug.log` or Crash report**

**Comment by Krutoy242** [comment]
This is actually a HEI bug that wasnt fixed a long time https://github.com/CleanroomMC/HadEnoughItems/issues/42
