### ISSUE TITLE
Thermal expansion dynamo upgrades are not scaling

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#42]
## Description
![Screenshot 2022-04-09 040414](https://user-images.githubusercontent.com/78452357/162552689-be63b722-c5c6-4805-ac1b-1a290befab45.png)
![Screenshot 2022-04-09 040456](https://user-images.githubusercontent.com/78452357/162552692-0212d03c-bdee-417e-9684-cf5f4e848d18.png)

The config is located here
https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/ebf241c1b515a10f700319394e8fce5490572183/config/cofh/thermalexpansion/common.cfg#L107-L108

I saw that you specifically edited the values for the dynamos, so i'm guessing that that was an oversight.
https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/ebf241c1b515a10f700319394e8fce5490572183/config/cofh/thermalexpansion/common.cfg#L190-L205

**Comment by Krutoy242** [comment]
This is intended.

The fact that dynamos can be easily buffed with upgrades makes Kits too powerful. 

Also, steam dynamo, as I recall, unable to work at all with too much upgrades.

**Comment by Srdjan-V** [comment]
Perhaps rephrasing the tool tip to exclude dynamos would be good
![image](https://user-images.githubusercontent.com/78452357/162569412-1e5f3571-99a1-4971-9768-2537ee856f52.png)

**Comment by Krutoy242** [comment]
Agree, would change this tip.
