### ISSUE TITLE
IC2 Replicator voids UU-Matter

### ISSUE THREAD

**Issue by Legofactor22** [Krutoy242/Enigmatica2Expert-Extended#422]
## Description

Transferring a few millibuckets of UU-Matter into the Replicator voids it. Replicator also seems finicky with getting powered (e.g. XNet's Connectors do not connect)
Worth noting that this was on multiplayer, unsure if the issue persists in singleplayer

**To Reproduce**

1. Use Matter Fabricator to create a few millibuckets of UU-Matter
2. Transfer it using any fluid pipe (we used Thermal Expansion's Hardened Fluiducts)

**Screenshots**
https://github.com/user-attachments/assets/7141e97b-b891-4d70-868d-6fedb668da42

**Modpack version** `v1.43.0`

debug.log: [debug.zip](https://github.com/user-attachments/files/17180786/debug.zip)

**Comment by Krutoy242** [comment]
I cannot reproduce this issue. Am i doing something wrong?

![image](https://github.com/user-attachments/assets/8954c6bf-c59c-4569-9d00-1e07099705f1)

![javaw_ace7fHM5zd](https://github.com/user-attachments/assets/8172ab85-8359-4ad2-82a1-bcd26aea9e2d)

**Comment by Legofactor22** [comment]
False alarm, not an actual issue...
The UU-Matter bar on the left doesn't go up if there's an inserted catalyst, since it immediately gets consumed and goes into replicating. Feels a bit redundant to have 2 bars if they convey the exact same input
![image](https://github.com/user-attachments/assets/e746fc41-5e65-4ff0-9e52-a2d1e20a21f5)
The quest book does explain the meaning of the numbers, but I feel like it could probably be made a bit more obvious, considering both of us (and the other server members) all missed it
Regardless, thank you for your response!

**Comment by Krutoy242** [comment]
> it could probably be made a bit more obvious,

How? Im open for suggestions!
