### ISSUE TITLE
Precision Laser Etcher is unable to make Basic Energy Relay Crystals

### ISSUE THREAD

**Issue by FrenziedDeath** [Krutoy242/Enigmatica2Expert-Extended#423]
## Description
The Precision Laser Etcher is supposed to be able to make the Basic Energy Relay Crystals so they can be used for crafting other recipes (as I would like to avoid making these using blood magic). 

## To Reproduce

Steps to reproduce the behaviour:
1. Form the precision laser etcher multiblock from advanced rocketry
2. Input all of the needed items to the input of the multiblock
3. The machine is not making it (the machine also seems to bug a bit with its animation when trying to make it)

## Screenshots
![2024-10-02_22 27 31](https://github.com/user-attachments/assets/a6e14019-8c37-4c4d-a657-1d2a6f8ede12)
![2024-10-02_22 27 40](https://github.com/user-attachments/assets/8ac791ea-8161-40bd-9d48-13dd432b1aed)
![2024-10-02_22 27 41](https://github.com/user-attachments/assets/e50cd302-c1c2-4615-9f9e-c0cbd3e25879)
![2024-10-02_22 39 25](https://github.com/user-attachments/assets/92404c17-30a8-44be-b8cd-56742daed929)
![2024-10-02_22 28 01](https://github.com/user-attachments/assets/0c6a72ad-8d6e-4fa3-a8ed-7f7b7d16593a)

**Modpack version** `v1.44.0`
Server log:
[debug.log](https://github.com/user-attachments/files/17235674/debug.log)
Client log:
[latest.zip](https://github.com/user-attachments/files/17235681/latest.zip)

**Comment by Krutoy242** [comment]
Thank you for the report! I will investigate it.

For now, please make this tests:
1. If you play on the server, test it in single player creative mode
2. Try to insert items with vanilla hopper instead of by hand
3. Break Input / output hatches and try again

**Comment by Krutoy242** [comment]
Thank you for the tests! I will make an issue on Advanced Rocketry fork github then.

**Comment by FireMagePenguin** [comment]
I just wanted to comment that I'm experiencing a similar issue with high RF/t recipes in the Precision Assembler also from Advanced Rocketry.
![2024-10-07_13 27 12](https://github.com/user-attachments/assets/ede1d741-4c6b-42ae-a505-b05b053b54b0)
I did some testing in a singleplayer world after having issues in multiplayer. I discovered that all recipes requiring 320,000 RF/t or more are broken and leave the Precision Assembler inoperable. Attached is a video showcasing the issue in-game.
https://github.com/user-attachments/assets/661e41db-d3a3-47a1-ab38-b3dd1f3bb8b3

**Comment by Krutoy242** [comment]
I found the problem and it will be fixed next release.

If you want to fix it yourself, do this on server and client:
1. Remove file `scripts/mixin/arlib.zs`
2. Set `D:blockEnergyHatchCapacityMultiplier=100.0` and `D:blockLiquidHatchCapacityMultiplier=10.0` in file `config/advRocketry/advancedRocketry.cfg`

**Comment by Krutoy242** [comment]
I will keep this issue open until new version released.
