### ISSUE TITLE
Packagedthaumic

### ISSUE THREAD

**Issue by bengenie** [Krutoy242/Enigmatica2Expert-Extended#424]
https://www.curseforge.com/minecraft/mc-mods/packagedthaumic

I like to add this mod to fully automate thaumcraft easy.

**Comment by Krutoy242** [comment]
We already have automation options for every Thaumcraft crafting methods. For example, Matrix Infusion can be automated with golems.

If you dont know how to automate one or another TC craft - ask in discord:  <a title="Join us on Discord!" href="https://discord.gg/VcmyHdNNQP"><img src="https://img.shields.io/discord/911676461050642432?label=E2E-E%20Discord&amp;logo=Discord&amp;style=?flat" alt="Discord"/></a>
