### ISSUE TITLE
[Feature Request] Add `Schematica` quest suggestions

### ISSUE THREAD

**Issue by wangxiaoyang776** [Krutoy242/Enigmatica2Expert-Extended#428]
It is advisable to add a description of the projection blueprint mod to the mission description, as many players I know of have not noticed this feature

**Comment by Krutoy242** [comment]
Are you talking about `Schematica` mod?

**Comment by wangxiaoyang776** [comment]
Yes, it's a useful mod that many people don't see

**Comment by Krutoy242** [comment]
Where do you think best place to put a note about this mod?

**Comment by wangxiaoyang776** [comment]
Maybe in the first welcome mission? The threshold of the NuclearCraft: Overhauled and Astral Sorcery or the first quest of the chapters of these two mods are also good choices

**Comment by Krutoy242** [comment]
I dont get your second question. Information about Mithminite is in Thaumcraft book.

**Comment by wangxiaoyang776** [comment]
I mean this
![Image_1729614559460](https://github.com/user-attachments/assets/253ac3fd-d91e-45d7-acfa-4e2b48afd396)

**Comment by Krutoy242** [comment]
What "this"?

**Comment by wangxiaoyang776** [comment]
This entry says that it will give the corresponding status according to the progress of the research in the Thaumcraft 6, and I want to know the detailed bonus

**Comment by Krutoy242** [comment]
See Thaunomicon for that.
