### ISSUE TITLE
On the issue of translation conflicts in Chinese localization

### ISSUE THREAD

**Issue by icepony** [Krutoy242/Enigmatica2Expert-Extended#429]
Chinese users mostly use a [resourcepack](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package) to supplement the mod localization, but it causes our changes to the name to be invalid.

I don't think most users will solve this problem themselves, maybe provide a resourcepack to override it.

Another solution is to use the oresources folder, but I don't know why it doesn't work for Requious Frakto's machine.

Of course, the easiest way is to tell them inside quest.

**Comment by Krutoy242** [comment]
Sorry, I don't understand subject of this issue. What should I do? Is renaming bad? What kind of renaming, like, fruits? Or you talking about `zh_cn.lang` files?

**Comment by icepony** [comment]
Sorry, my game had some issues yesterday, so I couldn't provide images.

![languagepack](https://github.com/user-attachments/assets/be44c153-9238-4dae-9e80-6ef0baa78e0d)

Before using the resource pack:
![work](https://github.com/user-attachments/assets/4339b7de-046c-4fd6-914e-7a33fd2398d0)

After using the resource pack:
![nowork](https://github.com/user-attachments/assets/e6d7e2a1-ee23-45c6-853f-e95edd623589)

As you can see there are problems and the English is actually correct.

The solution I came up with:
1. provide a fix resourcepack and the user can just use it.
![fix](https://github.com/user-attachments/assets/4c3c0164-a149-4b4a-927c-999adab604a1)

2. use the oresources folder
![oresources](https://github.com/user-attachments/assets/4602f31d-5218-47c6-8614-69cd60ecc8cd)
  but I don't know why the replicator won't work.
![replicator](https://github.com/user-attachments/assets/3784e4e9-e90b-44db-be60-39c399af15fa)
  although using [No Localization Conflict](https://www.curseforge.com/minecraft/mc-mods/nolocalizationconflict) can fix this.

4. tell them directly in the quest
![quest](https://github.com/user-attachments/assets/b75973cf-d37c-4b3d-a0be-9abb68a869a2)
  (Note: For users using the Chinese localized resourcepack, it will be displayed as a material reorganization machine.)

**Comment by Krutoy242** [comment]
Ok, now i understand better.

I visited China once via hitchhiking. but I don't know Chinese. This makes me see little different hieroglyphs without meaning. So i cant even point which renames not working and how to fix them.

1. I believe that `Minecraft-Mod-Language-Package` is not installed automatically and wasn't recommended by the E2E or E2EE Github / CurseForge pages. That means that Chinese-speaking players have their own resources with useful links and information. So I believe, that  such things as additional folders or additional resource packs should be distributed same way as Language-Package.

2. I dont know how I can manage to maintain another special folder just for zh_cn. Also, as you said, its not working for Replicator.

3. You can make PR, just, tell me what quest will say.

**Comment by icepony** [comment]
Okay, I'm just trying to get your opinion on the different solutions.

I will add hints to the quest and provide more intrusive solutions in the Chinese community.
