### ISSUE TITLE
How to add `Hand Over Your Items` script into other modpack?

### ISSUE THREAD

**Issue by ls314** [Krutoy242/Enigmatica2Expert-Extended#430]
Can you tell me which mod has the function of sharing items to the chat bar?

**Comment by Krutoy242** [comment]
Its not a mod its a [script](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/do/hand_over_your_items.zs).

**Comment by ls314** [comment]
> 它不是一个 Mod，而是一个[脚本](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/do/hand_over_your_items.zs)。

How do I use it?

**Comment by ls314** [comment]
> > 它不是一个 Mod，而是一个[脚本](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/do/hand_over_your_items.zs)。
> 
> 我该如何使用它？
Sorry for not describing it clearly. I mean how to use it in vanilla? Just add CraftTweaker and put the script in the scripts folder?

**Comment by ls314** [comment]
> > 它不是一个 Mod，而是一个[脚本](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/do/hand_over_your_items.zs)。
> 
> How do I use it?

Sorry for not describing it clearly. I mean how to use it in vanilla? Just add CraftTweaker and put the script in the scripts folder?

**Comment by Krutoy242** [comment]
I don't have a guide to use it in vanilla. You need basic CraftTweaker knowledge to use it.

You can start from copying script and installing mods:
- CraftTweaker
- ZenUtils
- CraftTweaker Integration

**Comment by ls314** [comment]
> I don't have a guide to use it in vanilla. You need basic CraftTweaker knowledge to use it.
> 
> You can start from copying script and installing mods:
> 
> * CraftTweaker
> * ZenUtils
> * CraftTweaker Integration

This looks difficult, but I will try. Thanks for your reply.

**Comment by ls314** [comment]
This seems to be giving items to other players, sharing items to the hotbar is not implemented, is it in the script?

**Comment by ls314** [comment]
This seems to be giving the item to other players, sharing the item to the chat bar is not implemented, is it in the script?

**Comment by Krutoy242** [comment]
You need to copy also lang files from folder `resources\hand_over_your_items\lang` and install mod `Resource Loader`.

**Comment by ls314** [comment]
> You need to copy also lang files from folder and install mod .`resources\hand_over_your_items\lang``Resource Loader`

Sorry, I don't speak English, so I can only describe it through translation software. I still can't achieve it after I do what you said, so I want to confirm the problem with you. The question I raise is this item in the tips:
[MP] Hover over an item in a GUI and press to show it in chat.Shift+T

**Comment by Krutoy242** [comment]
Oh, you want an item icon? You need also add mod `Quark` then, it made possible to see icons in chat.

**Comment by ls314** [comment]
nononono,

> Oh, you want an item icon? You need also add mod then, it made possible to see icons in chat.`Quark`

No, you are talking about the prompt message when giving items to other players. What I want is that when I put the mouse on an item and press a button, the item will appear in the chat bar.

**Comment by ls314** [comment]
> Oh, you want an item icon? You need also add mod then, it made possible to see icons in chat.`Quark`

No, you are talking about the prompt message when giving items to other players. What I want is that when I put the mouse on an item and press a button, the item will appear in the chat bar.

**Comment by ls314** [comment]
Hover over an item in a GUI and press Shift+T to show it in chat
This is a tip in your modpaks. I want to know how this function is implemented.

**Comment by ls314** [comment]
Hover over an item in a GUI and press Shift+T to show it in chat
This is a tip in your modpack. I want to know how this function is implemented.

**Comment by ls314** [comment]
> This is feature of the Quark mod.

How to enable this feature

**Comment by Krutoy242** [comment]
> How to enable this feature

Just install Quark

**Comment by Krutoy242** [comment]
Then you need to search Internet for that. I see that some people say its `SHIFT` + A key you use to open chat. Maybe its the reason https://www.reddit.com/r/QuarkMod/comments/mtq6yw/shift_t_to_share_itens_not_working/

**Comment by ls314** [comment]
> Then you need to search Internet for that. I see that some people say its + A key you use to open chat. Maybe its the reason https://www.reddit.com/r/QuarkMod/comments/mtq6yw/shift_t_to_share_itens_not_working/`SHIFT`

Thank you very much! It is indeed a key binding problem. I used shift + open chat bar button as you said, and it worked!
