### ISSUE TITLE
Basic fluid tank will be mistakenly turned into  rotary condensentrator in brewing barrel

### ISSUE THREAD

**Issue by meteoritel** [Krutoy242/Enigmatica2Expert-Extended#435]
## Description

Basic fluid tank was mistakenly turned into  rotary condensentrator  when I put it in brewing barrel. As shown in the following pictures.
**To Reproduce**

1. Put basic fluid tank with one bucket of water in brewing barrel to fill it. 
2. See error

**Modpack version** `v1.47.0`

**Comment by meteoritel** [comment]
![2024-11-19_10 46 24](https://github.com/user-attachments/assets/3f7f1562-4ce8-4970-8abd-5c1c73f78219)
![2024-11-19_10 46 37](https://github.com/user-attachments/assets/88929a5a-86eb-46f6-8622-47b0c6e4791c)
![2024-11-19_10 46 48](https://github.com/user-attachments/assets/94f6c9e6-0d45-44cb-b98b-03393f41a691)

**Comment by Krutoy242** [comment]
Thank you for the report!

Yes, I can reproduce this issue and its being reported before.
Its a `Rustic` mod bug, and I cant fix it without making changes in Rustic source code. Its being already reported [here](https://github.com/cadaverous-eris/Rustic/issues/316) and [here](https://github.com/cadaverous-eris/Rustic/issues/259).

I will take a look if I could fix it with a Mixin through.
