### ISSUE TITLE
Small Plate Presser not working for wood planks and treated wood planks

### ISSUE THREAD

**Issue by NoSyne** [Krutoy242/Enigmatica2Expert-Extended#44]
## Description

It worked with Iron Sheetmetal but not with any wooden planks nor treated wood

**Modpack version** `v0.53.0`

[debug.log](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/8456733/debug.log)
![2022-04-09_12 25 53](https://user-images.githubusercontent.com/57033696/162568352-bb7d0001-167a-4efa-b212-5f40133c6495.png)
![2022-04-09_12 25 54](https://user-images.githubusercontent.com/57033696/162568353-a8374bae-98a4-4399-9e2f-9afc379e1f1f.png)
![2022-04-09_12 25 43](https://user-images.githubusercontent.com/57033696/162568354-d5f566c6-16c4-472c-aa67-688cfe6eac74.png)
![2022-04-09_12 25 45](https://user-images.githubusercontent.com/57033696/162568356-827d0f72-5993-4d08-82f1-16e1074e68c8.png)

**Comment by Krutoy242** [comment]
Thank you for report, I see same in my server world.
Seems like I need to remove this recipe or make it from other ingredients.
