### ISSUE TITLE
Additional Fluid Dictionary Listings

### ISSUE THREAD

**Issue by Zyian** [Krutoy242/Enigmatica2Expert-Extended#443]
Setting up a system to create hydrogen chloride from salt water using a AR Electrolyser. This machine creates the NuclearCraft Hydrogen, I need the Mekanism version to use in the chemical infuser.

Currently this is the only one that I noticed but there could be others.

* NuclearCraft Hydrogen -> Mekanism Liquid Hydrogen

**Comment by Krutoy242** [comment]
Isnt NC and Mekanism can transfer liquids with each other seamlessly? Can you try just stick one machine to another with some kind of push / pull?
