### ISSUE TITLE
Hydroponics Factory structure not detected

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#45]
![Screenshot 2022-04-09 154212](https://user-images.githubusercontent.com/78452357/162578169-e8ea57bb-6c58-419a-a1d8-bd7546ab5d7e.png)
![Screenshot 2022-04-09 154229](https://user-images.githubusercontent.com/78452357/162578170-756d146c-a6bd-4f29-84b9-55404c460ca8.png)

**Comment by Krutoy242** [comment]
Seems like i messed up with flower pots. I will remake this later.

**Comment by Srdjan-V** [comment]
its still not detecting the structure
![image](https://user-images.githubusercontent.com/78452357/162820569-fafd794e-e3ab-4611-b8b9-fdeecbf2d165.png)
Im guessing that its not being detecting because it "requires a blueprint"

**Comment by Krutoy242** [comment]
> "requires a blueprint"

I don't know why it's even an option...
I would try to find where I can disable it.
