### ISSUE TITLE
Mob Crusher causing creepers to explode

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#49]
## Description
Due to mobs having more hp the crusher is not able to one shot then, in turn creepers are exploding.
I have manually enabled ftb chunk protection that is one way to fix that.

![image](https://user-images.githubusercontent.com/78452357/164067349-3d80f149-f294-4f2e-bf5c-068803b05412.png)

**Comment by Krutoy242** [comment]
- Creepers sometimes **explode anyway**, so this would not change your spawner space safety
- Use blast-resistant materials, like Reinforced Stone, or machines like **Shock Absorber** or **Block Protector**
- If you want machine that one-shot any mob - use **Mob Grinder** from Draconic Evolution
- Just cover Mob Crusher with any blocks
<img src="https://user-images.githubusercontent.com/936618/164074893-7e131c40-742a-4d9c-ab97-3b4248fa09dc.gif"/>

Anyway, this "Mobs aggro on blocks" - is unintended mechanics at the beginning, but now i'm starting to like that 😀

**Comment by Srdjan-V** [comment]
Imo, this should be added to the quest book, and a tool tip warning on the crusher to reed the quest book.

**Comment by Krutoy242** [comment]
Good idea! I would add this
