### ISSUE TITLE
Fluid Dictionary converter inconsistency

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#50]
## Description
It is not possible to convert mekanism liquid oxygen to nuclearcraft oxigen, but mekanism liquid hydrogen to nuclearcraft hydrogen is.
![image](https://user-images.githubusercontent.com/78452357/164518032-68db08bf-c16f-4425-9785-34a9d2812c33.png)

**Modpack version** `v0.55.0`

**Comment by Krutoy242** [comment]
Oh, this means my convert function is malfunction.
Thanks, would fix that!
