### ISSUE TITLE
Precision Laser Etcher wrong RF/t for nuclearcraft plates

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#51]
## Description
160.000 RF/t for basic plates
  70.000 RF/t for elite plates

![Screenshot 2022-04-23 015904](https://user-images.githubusercontent.com/78452357/164836253-e1b3134c-bfec-49b9-88ff-9ad67a16eff7.png)
![Screenshot 2022-04-23 015948](https://user-images.githubusercontent.com/78452357/164836252-a7a87182-a5c1-4e41-8989-f8df823c77be.png)

**Comment by Krutoy242** [comment]
Thank you! Would fix that

**Comment by Srdjan-V** [comment]
Just to add to this since i was not wary clear, the values just seem to be inverted for the plates
70k for tier 4 plates
100k for tier 3 plates
130k for tier 2 plates
160k for tier 1 plates
