### ISSUE TITLE
Crash: AE2 not working 

### ISSUE THREAD

**Issue by Leilei2579** [Krutoy242/Enigmatica2Expert-Extended#53]
Modpack version: v0.53.0
Description: Kicked out of the server every time opening the AE2 terminals(wired and wirelessed) but I cannot figure out the problem.

[crash-2022-04-27_22.57.36-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/8573430/crash-2022-04-27_22.57.36-client.txt)
[crash-2022-04-27_19.08.57-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/8573432/crash-2022-04-27_19.08.57-client.txt)

**Comment by Krutoy242** [comment]
You played on old modpack version.

This crash was fixed in recent AE2 mod versions, so you should update your modpack.

**Comment by Krutoy242** [comment]
Please comment if this issue still persist on new versions.

**Comment by Leilei2579** [comment]
solved&nbsp;actually，good&nbsp;job！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月1日(星期天) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Krutoy242/Enigmatica2Expert-Extended] Crash: AE2 not working  (Issue #53)





 
Please comment if this issue still persist on new versions.
