### ISSUE TITLE
[Suggestion] Recipes for ic2 crops

### ISSUE THREAD

**Issue by Srdjan-V** [Krutoy242/Enigmatica2Expert-Extended#54]
## Description
Ic2 crops are the most annoying part of the modpack to me, the fact that they are so tedious to crossbreed and so slow(i know that you can increase the stat of the crop) is the main reason I'm hating them, i have wasted about 5 hours crossbreeding them only for weed to destroy them, and yes i know that Weed-Ex exists but still that is not changing the fact that they are tedious at least to me.

So my suggestion is to add recipes for them, making them available before mystical agriculture crops.

**Comment by Krutoy242** [comment]
Thank you for sharing tedious parts of modpack - this helps me to improve.

But, why you even go through IC2 crops? They are not mandatory in the pack, you can just skip them.

**Comment by Srdjan-V** [comment]
![image](https://user-images.githubusercontent.com/78452357/166145268-10a5866a-97a0-40f5-a7e1-0933dc1fd701.png)
The way i see it is that this is the only "easily" renewable way of producing pulsating crystal.

On the other hand you will need to make the pulsating crystals using biome essence. The ore is renewable using void miners but im not sure if its possible to automate the conversion to essence without clogging up ae with all the different nbt values. So a alternative to adding recipes for ic2 crops would be to add a way of converting biome essence ore to essence without nbt.

**Comment by Krutoy242** [comment]
So, the pulsating crystal is only reason you want IC2 crops?
In this case i could just make alternative recipe for Pulsating Crystal instead.

**Comment by Srdjan-V** [comment]
> So, the pulsating crystal is only reason you want IC2 crops?

Yes for me that was the only reason, and since i like the fluid crafting mechanic in the pack i though it would be fun.

But i do still think that giving the players the option is the best thing. I have not played the sky block version of the pack so i dont know now many options for ore gathering exist, but making them a alternatively to sieving would be good?
