### ISSUE TITLE
Crash: `ExecutionException:ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by ilanpo** [Krutoy242/Enigmatica2Expert-Extended#56]
## Description

a wierd issue when game is launched happens at the end of loading modpack launches anyway

**Modpack version** `v0.56.0`

**`debug.log` or Crash report**
[crash-2022-05-06_14.04.28-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/8639552/crash-2022-05-06_14.04.28-client.txt)

**Comment by Krutoy242** [comment]
Since i updated `HadEnoughItems` this issue should never happen again.

Feel free to open issue again if it would occur again.
