### ISSUE TITLE
About the Ritual Meteor of Blood Magic: Alchemical Wizardry

### ISSUE THREAD

**Issue by guanzijian099** [Krutoy242/Enigmatica2Expert-Extended#59]
I use this ritual to get some rare material. But some of them doesn't work like it said in list.Just like in this config file:(*/config/bloodmagic/meteor/5_gems.json)

_{
  "catalystStack": {
    "registryName": {
      "domain": "minecraft",
      "path": "emerald_block"
    },
    "meta": 0
  },
  "components": [
    {"weight": 120,"oreName": "oreLapis"}
    ,{"weight":130,"oreName" : "oreDiamond"}
    ,{"weight":180,"oreName" : "oreEmerald"}
    ,{"weight": 20,"oreName" : "oreCoal"}
    ,{"weight": 20,"oreName" : "oreRuby"}
    ,{"weight": 20,"oreName" : "orePeridot"}
    ,{"weight": 20,"oreName" : "oreTopaz"}
    ,{"weight": 20,"oreName" : "oreTanzanite"}
    ,{"weight": 20,"oreName" : "oreMalachite"}
    ,{"weight": 20,"oreName" : "oreSapphire"}
    ,{"weight":160,"oreName" : "oreAmber"}
    ,{"weight": 20,"oreName" : "oreApatite"}
    ,{"weight":120,"oreName" : "oreCertusQuartz"}
    ,{"weight": 90,"oreName" : "oreCinnabar"}
    ,{"weight": 70,"oreName" : "oreProsperity"}
    ,{"weight": 20,"oreName" : "oreQuartzBlack"}
  ],
  "explosionStrength": 18.0,
  "radius": 3,
  "maxWeight": 650,
  "version": 4,
  "cost": 1400000
}_

Actually, "oreApatite", "oreCertusQuartz", "oreCinnabar", "oreProsperity" and "oreQuartzBlack" can't be got in this ritual.
I guess this is beacause the  **"maxWeight"** has a wrong value: 120+130+180+20+20+20+20+20+20+20+160>650 >120+130+180+20+20+20+20+20+20+20.This caused a truth that after the "oreAmber", which has the "weight" of 160, the ritual stopped spawning ores, and this is consistent with the actual result in game. Finally it result in the fact that, i can't get, for example, "oreProsperity" through the Ritual Meteor.
**Set the value of "maxweight" > 1030(the sum of all the "weight" - the last "weight" in the list) can solve this problem.**
Similar to this:
1.In config file  2_platinum.json, the last four ores("oreOsmium" "orePlatinum" "oreRutile" "oreUranium") can't be spwaned by the ritual meteor.
2.In config file 1_iron.json,the last one ores("oreAluminum") can't be spwaned by the ritual meteor.
3.In config file 6_nether.json,the last twelve ores("oreNetherGold" "oreNetherEmerald" "oreNetherDiamond" "oreNetherCoal" "oreNetherPlatinum" "oreNetherSilver" "oreNetherTin" "oreNetherCertusQuartz" "oreNetherChargedCertusQuartz" "oreNetherOsmium"  "oreNetherUranium"  "oreCobalt" "oreArdite") can't be spwaned by the ritual meteor.
The reason of all of these problems is the same. But i don't know if you are meant to design the ritual meteor like this :( 
Maybe just adjust some of the "maxWeight" or delete the ores in the list that can't be got from this ritual.

**Comment by Krutoy242** [comment]
Thank you for the issue and advice!
I will implement your suggestion.

 When I tested changes I didn't really understand what this number meant. When I set it too much there is mostly stone instead ores. But I didn't try to use this sum math. Gonna try.
