### ISSUE TITLE
[Suggestion] Call out Tinkers components that have unusual recipes in E2E-E book or quest book

### ISSUE THREAD

**Issue by blisslen** [Krutoy242/Enigmatica2Expert-Extended#62]
For tinkers parts that have recipes that aren't just that material casted / crafted into a part, it's hard to think of grabbing the recipe for that part in JEI, since normally tinkers parts don't have recipes at all. 

I'd been theory crafting creative flight in liu of angel rings and decided Aetherium armor trim could be a small sequence break -- I could do the reworked bees and get up to Artisan bees for flight early. It didn't really occur to me that the recipe could've changed, and when I saw that I couldn't convert aetherium shards into the trim I thought something was broken for a while. A call out in the quest book / E2E-E book could've been nice to catch that earlier. (Or maybe there's already a call out I missed and I'm just 5head-ing it)

**Comment by Krutoy242** [comment]
Oh!
Sorry for inconvenience!
Seems like it's actually a problem.
I will add notes in quest book or somewhere else.
Probably I would even make something similar in mid game, so players would familiar with mechanic.

Thank you for sharing your experience, this would help me to get modpack even better!
