### ISSUE TITLE
Thaumcraft alchemy recipes not working

### ISSUE THREAD

**Issue by ArdvarkDev** [Krutoy242/Enigmatica2Expert-Extended#63]
Can't make brass on newest version, the catalyst (aluminum brass ingot) just sits in the crucible.
The ink sac and gunpowder hedge alchemy recipes are required to progress in the thaumonocon and are also broken.

**Comment by ArdvarkDev** [comment]
this is on a dedicated server

**Comment by Krutoy242** [comment]
Seems like i just messed up with research names.
I wrote `HEDGEALCHEMY` but should be `HEDGEALCHEMY@1`.
Would fix next patch.

**Comment by Krutoy242** [comment]
Fixed in https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/tag/v0.59.0
