### ISSUE TITLE
Noob want to ask where can I set the absolutely path for jar

### ISSUE THREAD

**Issue by QingShuiMuYang** [Krutoy242/Enigmatica2Expert-Extended#72]
I didn't find where to set the absolutely path for jar, so I cant start my server.
Can you help me? Thanks bro.

**Comment by Krutoy242** [comment]
Did you followed this guide? https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/server/SERVER_GUIDE.md

**Comment by QingShuiMuYang** [comment]
yeah, I followed that guide step by step, but it told me that "Not found valid java". And I did install the java as follow:
![image](https://user-images.githubusercontent.com/50355060/176837639-9fc3a1da-c1c2-450b-8867-15083e3f0452.png)

**Comment by QingShuiMuYang** [comment]
Here's my serverstart.log, hope these infomation helpful:
----------------------------------------------------------------- 
INFO: Starting batch at  周五/0/0:112131 
----------------------------------------------------------------- 
 
DEBUG: Current Dir is G:\Minecraft\服务端\E2E-Extended_v0.61.1_server -- trying to change to G:\Minecraft\服务端\E2E-Extended_v0.61.1_server\ 
INFO: Checking that settings.cfg exists 
DEBUG: settings.cfg Found. Logging full contents below: 
;SETTINGS FOR SERVERSTART SCRIPTS
;See "serverstart.log" in the LOGS subfolder 
;For more details/help see: https://github.com/AllTheMods/Server-Scripts

MAX_RAM=10G; 
JAVA_ARGS=-javaagent:authlib-injector-1.1.42.jar=https://littleskin.cn/api/yggdrasil -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.readTimeout=180 -Dfml.queryResult=confirm; 
CRASH_COUNT=5; 
CRASH_TIMER=600; 
RUN_FROM_BAD_FOLDER=0; 
IGNORE_OFFLINE=1; 
IGNORE_JAVA_CHECK=0; 
USE_SPONGE=0;
HIGH_CPU_PRIORITY=0;

MODPACK_NAME=Enigmatica 2: Expert - Extended;
MCVER=1.12.2;
FORGEVER=14.23.5.2860; 
FORGEURL=DISABLE; 
INFO: Loading variables from settings.cfg  
DEBUG: Starting variable definitions: 
DEBUG: MC_SERVER_MAX_RAM=10G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx10G -Xms5G -javaagent:authlib-injector-1.1.42.jar=https://littleskin.cn/api/yggdrasil -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.readTimeout=180 -Dfml.queryResult=confirm 
DEBUG: MC_SERVER_MAX_CRASH=5 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=1 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.12.2 
DEBUG: MC_SERVER_FORGEVER=14.23.5.2860 
DEBUG: MC_SERVER_FORGESHORT=2860 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_HIGH_PRIORITY=0 
DEBUG: MC_SERVER_PACKNAME=Enigmatica 2: Expert - Extended 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON=Unspecified 
DEBUG: MC_SERVER_TMP_FLAG= 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD= 周五/0/0 
DEBUG: MC_SERVER_CRASH_HHMMSS=112131 
DEBUG: Current directory file listing: 
 驱动器 G 中的卷没有标签。
 卷的序列号是 5049-2FF0

 G:\Minecraft\服务端\E2E-Extended_v0.61.1_server 的目录

2022/07/01  10:42    <DIR>          .
2022/07/01  10:42    <DIR>          ..
2022/04/15  10:54           317,282 authlib-injector-1.1.42.jar
2022/06/19  23:02    <DIR>          bansoukou
2022/06/19  23:02    <DIR>          config
2022/06/19  23:02    <DIR>          local
2022/07/01  11:21    <DIR>          logs
2022/07/01  10:33    <DIR>          mods
2022/06/19  23:02    <DIR>          patchouli_books
2022/06/19  23:02    <DIR>          schematics
2022/06/19  23:02    <DIR>          scripts
2022/06/19  21:15               788 server.properties
2022/01/20  02:12            12,200 ServerStart README.md
2022/07/01  11:21            42,807 ServerStart.bat
2022/01/20  02:12            10,249 ServerStartLinux.sh
2022/03/07  22:12             2,241 SERVER_GUIDE.md
2022/07/01  10:54             1,086 settings.cfg
2022/06/19  23:02    <DIR>          structures
               7 个文件        386,653 字节
              11 个目录 167,194,755,072 可用字节
DEBUG: JAVA version output (java -d64 -version): 
ERROR: Could not find 64-bit Java 1.8 installed or in PATH 
ERROR: Error flagged, reason is: ""JavaVersionOrPathError"" 
WARN: Server startup script is exiting. Dumping current vars: 
DEBUG: MC_SERVER_MAX_RAM=10G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx10G -Xms5G -javaagent:authlib-injector-1.1.42.jar=https://littleskin.cn/api/yggdrasil -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.readTimeout=180 -Dfml.queryResult=confirm 
DEBUG: MC_SERVER_MAX_CRASH=5 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=1 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.12.2 
DEBUG: MC_SERVER_FORGEVER=14.23.5.2860 
DEBUG: MC_SERVER_FORGESHORT=2860 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_HIGH_PRIORITY=0 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_PACKNAME=Enigmatica 2: Expert - Extended 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON="JavaVersionOrPathError" 
DEBUG: MC_SERVER_TMP_FLAG= 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD= 周五/0/0 
DEBUG: MC_SERVER_CRASH_HHMMSS=112131 
DEBUG: Current directory file listing: 
 驱动器 G 中的卷没有标签。
 卷的序列号是 5049-2FF0

 G:\Minecraft\服务端\E2E-Extended_v0.61.1_server 的目录

2022/07/01  10:42    <DIR>          .
2022/07/01  10:42    <DIR>          ..
2022/04/15  10:54           317,282 authlib-injector-1.1.42.jar
2022/06/19  23:02    <DIR>          bansoukou
2022/06/19  23:02    <DIR>          config
2022/06/19  23:02    <DIR>          local
2022/07/01  11:21    <DIR>          logs
2022/07/01  10:33    <DIR>          mods
2022/06/19  23:02    <DIR>          patchouli_books
2022/06/19  23:02    <DIR>          schematics
2022/06/19  23:02    <DIR>          scripts
2022/06/19  21:15               788 server.properties
2022/01/20  02:12            12,200 ServerStart README.md
2022/07/01  11:21            42,807 ServerStart.bat
2022/01/20  02:12            10,249 ServerStartLinux.sh
2022/03/07  22:12             2,241 SERVER_GUIDE.md
2022/07/01  10:54             1,086 settings.cfg
2022/06/19  23:02    <DIR>          structures
               7 个文件        386,653 字节
              11 个目录 167,194,755,072 可用字节
DEBUG: JAVA version output (java -d64 -version): 
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.

0 out of 0 jobs canceled.

**Comment by Krutoy242** [comment]
Are you able to launch any other modpack, for example, original `E2E` ?

**Comment by QingShuiMuYang** [comment]
No, I haven't tried it yet. All the problem is: I don't know how to set the java path so the jar can be detected by the program. And I tried to rewrite the startserver.bat to solve this problem, but I find it missing forge.jar, I cant install the forge correctly cause I'm in China. Sorry to bother you, but I have just no idea so I come to github hope you can help me.

**Comment by Krutoy242** [comment]
Could you try to launch vanilla minecraft server? Without modpack at all?

I mean, if this is a common problem, i bet there is lot of guides in your language in internet.

**Comment by QingShuiMuYang** [comment]
yeah, I have other servers in my computers, like All the mods6, VaultHunters. this isn't a common problem, but I just dont know how to solve this, I didn't find some guides in my country's web.

**Comment by QingShuiMuYang** [comment]
or can u download the forge and install that in your modpack and zip that to send me? Much grateful.

**Comment by Krutoy242** [comment]
> or can u download the forge and install that in your modpack and zip that to send me? Much grateful.

I think this would violate the forge rules.

If you have `All the mods 6` or other modpacks running, that means you already have forge somewhere.
I dont know how to fix that either! When i made server guide for this modpack, i just copied original `E2E` guide.
So, you can try to find in web how to launch `E2E`. I bet there is a lot of players why launched E2E server in China.

**Comment by Krutoy242** [comment]
So, how did you fix that?
