### ISSUE TITLE
Lots of FPS stuttering

### ISSUE THREAD

**Issue by Storyboard-MC** [Krutoy242/Enigmatica2Expert-Extended#74]
## Description

We are getting lots of FPS Stuttering while playing like we just started a world and I am getting 120FPS stable but it feels like 30FPS
I feel like this is some type of problems with a mod causing this issue, but cannot tell what one it could be

This is my current setup in my pc I5-7400 with GTX 1050 2GB
My friend has a 5700G and a 3060 and has the same exact issue that I got.

**Screenshots**

-->

**Modpack version** `v0.62.0`

Is there any mods that we can remove that are only used clientside that are known to be causing FPS issues? If so please tell me.

**Comment by thecodingchicken** [comment]
Hi!  I'm that friend.  I have a ryzen 7 5700g, 32GB of ram, and a 3060.  Running java version 1.8_292
Getting 200fps, but it feels like 40 for me.

**Comment by Krutoy242** [comment]
Thank you for report!

This issue sounds like caused by `Entity Culling` mod. Try to remove it along with its dependency `Render Lib`.

**Comment by thecodingchicken** [comment]
Removed them, I'll check again after work.  Will ask Storyboard to try it as well

**Comment by Storyboard-MC** [comment]
Can confirm that removing that mod helped quite a bit but also if you got optifine to remove animated terrain helped even more

Thank you for the help Krutoy!

**Comment by Krutoy242** [comment]
Thank you for report!
