### ISSUE TITLE
Failed to handle packet for IP:Port

### ISSUE THREAD

**Issue by Storyboard-MC** [Krutoy242/Enigmatica2Expert-Extended#75]
## Description

When a new player tries to login on the server, they get kicked instantly for Failed to handle packet for TheirIP:Port
With a java.lang.NullPointerException: null

We were required to remove TickCentral and LagGoggles from the server since it was causing the PacketError at first.

We are running this server on a Dedicated Server from ReliableSite with 128GB of ram (12GB Allocated) on a 5600x

**To Reproduce**
1: Just try to login on the server with a fresh install of the modpack.
2: The issue is happening

**Modpack version** `v0.62.0`

**`debug.log` or Crash report**
Debug log: https://gist.github.com/Storyboard-MC/e19ecbb2dc6210eec685a47e0653aeea

**Comment by Storyboard-MC** [comment]
I went on the discord and to fix this issue, we did what Krutoy242 said in the discord to remove Integrated Proxy and it worked.

**Comment by Krutoy242** [comment]
Yes, this is related to this issue https://github.com/shBLOCK/IntegratedProxy/issues/29

I'm gonna remove Integrated Proxy next patch if it would not be fixed soon.

**Comment by Krutoy242** [comment]
I removed **Integrated Proxy** in [latest releases](https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases) so you can safetly update client to fix issue 😉
