### ISSUE TITLE
Failed to run a server

### ISSUE THREAD

**Issue by coder-Zzx** [Krutoy242/Enigmatica2Expert-Extended#76]
Hi there. The server just keeps installing forge and server files, which were already in the same path. maybe there's something wrong with the server running scripts?
![image](https://user-images.githubusercontent.com/78394728/177842714-26e4560a-d045-4824-93ca-a27410246e53.png)

**Comment by Krutoy242** [comment]
Hi!
I didn't changed server run scripts from base E2E files.
Can you try to run E2E server and see if error still occur?

**Comment by coder-Zzx** [comment]
> 

i just tried but it was the same. it just said installing forge after the forge installed successfully over and over again.

**Comment by Krutoy242** [comment]
So, any luck with running server?

**Comment by coder-Zzx** [comment]
I've been work on it recently. I tried to put all the mods, configs, scripts and other stuffs in another sever folder and it worked, with many errors and warnings though. I think maybe it's caused by some fml libraries lost. But I still have no idea about the exact reason.

**Comment by Krutoy242** [comment]
Also, could you try in file `settings.cfg` set `IGNORE_JAVA_CHECK=0; ` to `IGNORE_JAVA_CHECK=1; ` ?

**Comment by Krutoy242** [comment]
Also, one of `E2E-E` player had issue with Java version too, there is his comment:
> I just tried launching a new Enigmatica2 Server like I did earlier today, with the only difference being I downloaded a java version from Adoptium (AdoptOpenJDK) and not from Oracle (supposed to be the original one xD)
Other than that, i didn't modify any settings from it, and the server is actually launching.
Here, the Java was clearly not recognized while Adoptium version of it was recognized 🤔 
It works even with E2E-E, and it saves me a lot of headaches

**Comment by coder-Zzx** [comment]
Yeah, I tried the first solution and it worked, now it's running steadily, thx a lot! (I replied a few days ago, but i don't know why you didn't receive that.)

**Comment by Krutoy242** [comment]
Great! Thank you for feedback.
