### ISSUE TITLE
Refined storage not actually included in modpack but is in documentation

### ISSUE THREAD

**Issue by zeelok1** [Krutoy242/Enigmatica2Expert-Extended#78]
## Description

When installing this modpack, refined storage isn't included but it (and several addons) are mentioned in the  [MODS.md](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/MODS.md) file. It also doesn't show up as a dependency on curseforge (https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended/relations/dependencies, alphabetically it should be on page 16 I think)

**To Reproduce**
Install the modpack using any launcher. refinedstorage.jar is not present, neither are the addons mentioned.

**Modpack version** `v0.64.0`

**Comment by Krutoy242** [comment]
Thank you for report, I will remove it from MODS.md
Anyway surprised someone actually read this file 😄
