### ISSUE TITLE
IE `Water Wheel` not working, *FluidloggedAPI* issue

### ISSUE THREAD

**Issue by Krutoy242** [Krutoy242/Enigmatica2Expert-Extended#84]
<img src="https://user-images.githubusercontent.com/936618/180601374-ba8d4fcb-630f-4aea-92a6-7ff8178dee55.png" width=300 align=right>
<img src="https://user-images.githubusercontent.com/936618/180601368-378f6840-c97c-4239-969e-9995f23a52f8.png" align=right>

Water can't make `Immersive Engineering` Wheel to turn. Water Wheel absorbs water because of *FluidloggedAPI*.

**Comment by danteesp** [comment]
you can fix this issue in the game by placing another water source block one block in front of the original ones. I don't know how efficient this would be in terms of power but it works just fine for my purposes in the early game.

**Comment by Krutoy242** [comment]
> you can fix this issue in the game by placing another water source block one block in front of the original ones. I don't know how efficient this would be in terms of power but it works just fine for my purposes in the early game.

Thank you! This information could be useful for other players before mod issue would be fixed.

**Comment by Krutoy242** [comment]
Fixed in next release
