### ISSUE TITLE
Visual glitch drawers and double chest so far.

### ISSUE THREAD

**Issue by JustaRandom** [Krutoy242/Enigmatica2Expert-Extended#85]
Hello,
I have a visual glitch as the title says only at eye level, I do have **optifine HD G5** ultra and did not add any mods.
Latest version 0.64.
![2022-07-23_12 51 32](https://user-images.githubusercontent.com/29123993/180602168-ef8efee3-1c27-42dd-a672-fc8dfcad71b2.png)
![2022-07-23_12 51 40](https://user-images.githubusercontent.com/29123993/180602169-2408d9c9-4d22-4ada-9a81-a8a376f39cd9.png)
![2022-07-23_12 51 45](https://user-images.githubusercontent.com/29123993/180602171-e95905a2-3b15-49c1-bc4a-b1553a902e86.png)

Tried fast render option on optifine.
Does anyone know a solution?
Thanks

**Comment by Krutoy242** [comment]
This is probablt cause by `Entity Culling` mod. Try next `v0.65.0` version when it released, or remove `Entity Culling` from your own setup, and then tell if anything changes.

**Comment by JustaRandom** [comment]
I disabled the mod and restarted the game. It was the problem, both instances of drawers and chest visual disappearance are gone.
For other users on the next version will try as well and post.
Thanks

**Comment by Krutoy242** [comment]
Next `v0.65.0` version comes without `Entity Culling`, so if it was the problem, this issue is fixed.
