### ISSUE TITLE
Change Morphing Tool recipe to not require silver

### ISSUE THREAD

**Issue by iimurpyh** [Krutoy242/Enigmatica2Expert-Extended#87]
The Morphing Tool recipe that gives it wrenches from every mod requires a silver gear. In normal E2E this is pretty simple to get, but since it's been removed from generation in E2EE it's a lot more expensive. Could it be changed to something like steel?
![image](https://user-images.githubusercontent.com/51100244/185756602-c116c2cb-0453-4bcf-a917-04f1221d540e.png)

**Comment by Krutoy242** [comment]
Actually good idea, thanks for suggestion!
