### ISSUE TITLE
Energetic Nitor impossible to craft in the Thaumatorium (server only)

### ISSUE THREAD

**Issue by Waisse** [Krutoy242/Enigmatica2Expert-Extended#89]
Clicking to initiate crafting does nothing, no matter what colored variant of nitor is used. This is insanely frustrating because the item is further used to make for the Causality Collapser and I have a few space tendrils violating my base **right now**. Making this item the archaic way in a crucible is anything but fun, please fix asap this is very important.

![image](https://user-images.githubusercontent.com/9310630/186083697-556d7315-3e6d-43a7-abfc-06709b5ab39f.png)

Modpack version v0.67.0

**Comment by Krutoy242** [comment]
Sorry, but i have no idea how to fix that.
Seems like one of the Thaumcraft addons ruin Thaumatorium and now its not working.

I will try to look for more information about this, but i doubt i can fix that 🙁

**Comment by Krutoy242** [comment]
Just tested and its working.
Cant reproduce.

https://user-images.githubusercontent.com/936618/190586879-83a3b67f-d256-4281-8d6c-c34e130a525b.mp4

![image](https://user-images.githubusercontent.com/936618/190586980-75f89acf-8a54-403b-8004-3b9454b9e7c7.png)

Could you try to use Lime Nitor? Maybe this was the problem?

**Comment by Krutoy242** [comment]
Actually, this happens serverside only.

**Comment by Krutoy242** [comment]
Seems like i don't know how exactly fix this issue, sorry 😞
