### ISSUE TITLE
Lootr replaces Ice and Fire Myrmex cocoons with chests workers can't interact with

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#90]
## Description

Ice and Fire jungle and desert Myrmex workers do not drop off items that they are carrying anywhere. This is most likely due to Lootr turning the cocoons they normally place items in into chests they can't interact with.
This makes it far more difficult to raise your reputation with them as all workers in a hive will most likely already be carrying something by the time you find the hive.

Adding the jungle/desert cocoons to Lootr's blacklist should the issue for future Myrmex hives.

**Modpack version** `v0.67.0`

**Comment by Krutoy242** [comment]
Thank you for the report!
Yes, I confirm this issue and would did next update.
