### ISSUE TITLE
Smelting purified crushed lead ore produces an invalid item.

### ISSUE THREAD

**Issue by stiffchub** [Krutoy242/Enigmatica2Expert-Extended#93]
## Description

Smelting purified crushed lead ore from IndustrialCraft 2 produces an invalid item.

![2022-08-31_09 03 10](https://user-images.githubusercontent.com/112094041/187684923-00891db2-1860-42aa-a801-8da22d11c130.png)

**Modpack version** `v0.68.0`

**Comment by Krutoy242** [comment]
Thank you for the report, i will check this out!
